### ISSUE TITLE
Can't open some forms

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1012]
#### Software and hardware versions 
Current master branch 

#### Problem description
I'm not able to open some forms:

> 05-08 16:30:51.211 7677-7677/org.odk.collect.android E/FormLoaderTask: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] org.odk.collect.android.logic.FormController.getLanguages()' on a null object reference
                                                                           at org.odk.collect.android.activities.FormEntryActivity.loadingComplete(FormEntryActivity.java:2480)
                                                                           at org.odk.collect.android.tasks.FormLoaderTask.onPostExecute(FormLoaderTask.java:529)
                                                                           at org.odk.collect.android.tasks.FormLoaderTask.onPostExecute(FormLoaderTask.java:73)
                                                                           at android.os.AsyncTask.finish(AsyncTask.java:632)
                                                                           at android.os.AsyncTask.access$600(AsyncTask.java:177)
                                                                           at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:145)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5951)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

#### Steps to reproduce the problem
Try to open this form:
[notice-and-name.txt](https://github.com/opendatakit/collect/files/983786/notice-and-name.txt)

#### Other information 
This pr is responsible https://github.com/opendatakit/collect/pull/1006

**Comment by lognaturel** [comment]
I have seen that as well. I took a couple of minutes to poke around thinking that it might be something taking too long to initialize but I found no evidence of that. 🤔 Would be good to get a sense of whether it's related to specific kinds of forms.

@shobhitagarwal1612 this might interest/puzzle you.
