### ISSUE TITLE
Wrong date pickers shown for no-calendar appearances in Android 7.0

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1161]
#### Software and hardware versions 
Collect v1.7.0-135-gfe674f323, Android v7.0, Motorola G4

#### Problem description
Dates with `no-calendar`, `month-year` or `year` appearances show the material design date picker and throw exceptions. Also, the time widget shows the material design dialog.

#### Steps to reproduce the problem
Use [dates.txt](https://github.com/opendatakit/collect/files/947023/dates.txt).

#### Expected behavior
They should all use dialogs with pickers. @mmarciniak90 can you please see if you can reproduce with any of your devices? @grzesiek2010 you might also have some ideas on this one.

#### Other information 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at org.odk.collect.android.widgets.DateWidget.hideDayFieldIfNotInFormat(DateWidget.java:101)
	at org.odk.collect.android.widgets.DateWidget.<init>(DateWidget.java:81)
	at org.odk.collect.android.widgets.WidgetFactory.createWidgetFromPrompt(WidgetFactory.java:59)
	at org.odk.collect.android.views.ODKView.<init>(ODKView.java:199)
	at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1286)
	at org.odk.collect.android.activities.FormEntryActivity.showNextView(FormEntryActivity.java:1440)
	at org.odk.collect.android.activities.FormEntryActivity.onFling(FormEntryActivity.java:2883)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:650)
	at org.odk.collect.android.activities.FormEntryActivity.dispatchTouchEvent(FormEntryActivity.java:1381)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:373)
	at android.view.View.dispatchPointerEvent(View.java:10162)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4446)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4314)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3861)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3914)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3880)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4007)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3888)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4064)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3861)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3914)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3880)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3888)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3861)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6257)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6196)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6157)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6360)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at org.odk.collect.android.widgets.DateWidget.hideDayFieldIfNotInFormat(DateWidget.java:101)
	at org.odk.collect.android.widgets.DateWidget.<init>(DateWidget.java:81)
	at org.odk.collect.android.widgets.WidgetFactory.createWidgetFromPrompt(WidgetFactory.java:59)
	at org.odk.collect.android.views.ODKView.<init>(ODKView.java:199)
	at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1286)
	at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1302)
	at org.odk.collect.android.activities.FormEntryActivity.showNextView(FormEntryActivity.java:1440)
	at org.odk.collect.android.activities.FormEntryActivity.onFling(FormEntryActivity.java:2883)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:650)
	at org.odk.collect.android.activities.FormEntryActivity.dispatchTouchEvent(FormEntryActivity.java:1381)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:373)
	at android.view.View.dispatchPointerEvent(View.java:10162)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4446)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4314)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3861)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3914)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3880)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4007)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3888)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4064)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3861)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3914)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3880)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3888)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3861)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6257)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6196)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6157)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6360)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Comment by lognaturel** [comment]
I think this is #992 again. I don't see any obvious reason why it would be back.

**Comment by lognaturel** [comment]
A beta tester reported something like this [on the forum](https://forum.opendatakit.org/t/where-is-odk-collect-1-7-1/6930). Hopefully he will let us know more about the Android version and device he's using.

**Comment by mmarciniak90** [comment]
I was able to reproduce this problem only on AVD with Android 7.0.
![screenshot_1497867281](https://user-images.githubusercontent.com/3907554/27280702-36575500-54e9-11e7-96c3-3f2bf9692ee9.png)

I tested also devices with Android 4.1, 4.2, 4.4, 5.1, 6.0 - problem was not visible.
