### ISSUE TITLE
Null pointer exception after refactoring

### ISSUE THREAD

**Issue by Angkirat** [getodk/collect#1179]
#### Software and hardware versions 
Collect v1.7.0, Android v8.0.0, Nexus (Emulator)

#### Problem description
I an getting a null pointer exception after refactoring the code. The code works perfectly fine without refactoring.

```
java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getCount()' on a null object reference
                                                                           at org.angkirat.fb.android.activities.FormDownloadList.isLocalFormSuperseded(FormDownloadList.java:572)
                                                                           at org.angkirat.fb.android.activities.FormDownloadList.selectSupersededForms(FormDownloadList.java:611)
                                                                           at org.angkirat.fb.android.activities.FormDownloadList.formListDownloadingComplete(FormDownloadList.java:681)
                                                                           at org.angkirat.fb.android.tasks.DownloadFormListTask.onPostExecute(DownloadFormListTask.java:279)
                                                                           at org.angkirat.fb.android.tasks.DownloadFormListTask.onPostExecute(DownloadFormListTask.java:49)
```
#### Steps to reproduce the problem
Refactored the code

**Comment by yanokwa** [comment]
In general, we can't really provide support for issues in someone else's fork. My recommendation is to start from a clean repo, refactor incrementally (and verify changes in each increment) and then go from there.

**Comment by yanokwa** [comment]
If you have more issues after that, you can find some of the other developers on http://slack.opendatakit.org in the #collect-code channel.
