### ISSUE TITLE
Crash when attempting to get device details

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1206]
#### Software and hardware versions 
Collect v1.4.10+, seen across devices and Android versions in Play Store console

#### Problem description
Collect crashes when trying to get the phone's serial number. I believe `telephonyManager.getDeviceId()` is the culprit.

#### Steps to reproduce the problem
I'm not able to reproduce this on my devices. Galaxy Note5, Galaxy S6 are common devices this happens on.

#### Expected behavior
No crash. The calls that can result in exceptions should be wrapped in try/catch blocks.

#### Other information 
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5973)
  at android.app.ActivityThread.-wrap3(ActivityThread.java:0)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6776)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
Caused by: java.lang.SecurityException: 
  at android.os.Parcel.readException(Parcel.java:1693)
  at android.os.Parcel.readException(Parcel.java:1646)
  at com.android.internal.telephony.IPhoneSubInfo$Stub$Proxy.getIccSerialNumberForSubscriber(IPhoneSubInfo.java:910)
  at android.telephony.TelephonyManager.getSimSerialNumber(TelephonyManager.java:2493)
  at android.telephony.TelephonyManager.getSimSerialNumber(TelephonyManager.java:2476)
  at org.odk.collect.android.logic.PropertyManager.<init>(PropertyManager.java:118)
  at org.odk.collect.android.application.Collect.onCreate(Collect.java:253)
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5970)
```

**Comment by grzesiek2010** [comment]
@lognaturel I also wasn't able to reproduce the issue so I added try/catch block https://github.com/opendatakit/collect/pull/1228

I tried vd Api 24 as it occurs only on Api 24 and I tried to revoke permissions but without success.
