### ISSUE TITLE
Frequent crash on version 1.4.10 from Play Store

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1251]
I was looking at crash reports and noticed [this one](https://play.google.com/apps/publish/?dev_acc=00659255839475882647#AndroidMetricsErrorsPlace:p=org.odk.collect.android&appVersion=PRODUCTION&lastReportedRange=LAST_30_DAYS&clusterName=apps/org.odk.collect.android/clusters/31f69dd8) (needs permissions) which happens really frequently and only on 1.4.10/1061. Some users are still on that version because of older devices. It happens often enough that I think it's worth doing a maintenance release for.

```
java.lang.RuntimeException: 
  at android.os.AsyncTask$3.done(AsyncTask.java:300)
  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
  at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
  at java.util.concurrent.FutureTask.run(FutureTask.java:242)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
  at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.RuntimeException: 
  at org.kxml2.kdom.Document.getRootElement(Unknown Source:0)
  at org.odk.collect.android.tasks.DownloadFormListTask.doInBackground(DownloadFormListTask.java:99)
  at org.odk.collect.android.tasks.DownloadFormListTask.doInBackground(DownloadFormListTask.java:44)
  at android.os.AsyncTask$2.call(AsyncTask.java:288)
  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
```

**Comment by grzesiek2010** [comment]
@lognaturel Looks like this bug has been fixed. We can close this issue.

**Comment by lognaturel** [comment]
It's been fixed in current versions but the issue is that some people can't update because of their devices. What this issue is about is creating a 1.4.11 release with some bug fixes for those people stuck on the old version.

**Comment by lognaturel** [comment]
😪 We probably can't use 1.4.11 because that was used for a minor version rather than a patch release. So I have no idea what we would call it but hopefully the concept is clear now @grzesiek2010.

**Comment by nribeka** [comment]
1.4.11.1 @lognaturel? Are you planning to have this available in github release page?

**Comment by lognaturel** [comment]
I think 1.4.10.1 would work! Good idea, @nribeka.

We haven't done this kind of patch release for an older version yet so there's no process in place. I was thinking we would treat it like any other release and show it on the GitHub release page.

**Comment by nribeka** [comment]
Ah I was trying to ask about the apk itself. Because I don't think you can use google play to distribute the apk because then 1.4.10.1 will be the default release, right?

**Comment by lognaturel** [comment]
Good question. The Play Store uses the version with the highest build number that is compatible with the device. We've been leaving gaps between release build numbers so that we can insert updates. I think 1062 is available and can be used.

**Comment by lognaturel** [comment]
Time has passed so this is not so relevant anymore.
