### ISSUE TITLE
d != java.lang.String error when adding manual value to external integer widget

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1281]
#### Software and hardware versions 
Collect v1.9.0 beta.0, Android v7.0, Motorola G4

#### Problem description
After manually inserting a value in the external integer widget, returning to it causes an error.

#### Steps to reproduce the problem
1. Open a form with an external integer widget such as the All Widgets form from the default server
1. Manually enter a value
1. Swipe to the next question
1. Swipe back to the external integer widget or jump to it
1. See "Error Occurred" dialog with "d != java.lang.String"

#### Expected behavior
No error.

#### Other information 
```
java.util.IllegalFormatConversionException: d != java.lang.String
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4135)
	at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2832)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2786)
	at java.util.Formatter.format(Formatter.java:2491)
	at java.util.Formatter.format(Formatter.java:2426)
	at java.lang.String.format(String.java:2670)
	at org.odk.collect.android.widgets.ExIntegerWidget.<init>(
	at org.odk.collect.android.widgets.WidgetFactory.createWidgetFromPrompt(
	at org.odk.collect.android.views.ODKView.<init>(ODKView.java:199)
	at org.odk.collect.android.activities.FormEntryActivity.createView(
	at org.odk.collect.android.activities.FormEntryActivity.showPreviousView(
	at org.odk.collect.android.activities.FormEntryActivity.onFling(
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:650)
```

**Comment by yanokwa** [comment]
On my Samsung Galaxy Tab SM-T285 - Android 5.1.1, I get this error..

```
java.util.IllegalFormatConversionException: %d can't format java.lang.String arguments
	at java.util.Formatter.badArgumentType(Formatter.java:1489)
	at java.util.Formatter.transformFromInteger(Formatter.java:1689)
	at java.util.Formatter.transform(Formatter.java:1461)
	at java.util.Formatter.doFormat(Formatter.java:1081)
	at java.util.Formatter.format(Formatter.java:1042)
	at java.util.Formatter.format(Formatter.java:1011)
	at java.lang.String.format(String.java:1803)
	at org.odk.collect.android.widgets.ExIntegerWidget.<init>(ExIntegerWidget.java:77)
	at org.odk.collect.android.widgets.WidgetFactory.createWidgetFromPrompt(WidgetFactory.java:75)
	at org.odk.collect.android.views.ODKView.<init>(ODKView.java:199)
	at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1237)
	at org.odk.collect.android.activities.FormEntryActivity.showPreviousView(FormEntryActivity.java:1455)
	at org.odk.collect.android.activities.FormEntryActivity.onFling(FormEntryActivity.java:2868)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:620)
	at org.odk.collect.android.activities.FormEntryActivity.dispatchTouchEvent(FormEntryActivity.java:1332)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2704)
	at android.view.View.dispatchPointerEvent(View.java:9397)
```
