### ISSUE TITLE
Crash when scanning for many instances

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1350]
#### Software and hardware versions 
Collect v1.9.1

#### Problem description
Crash when scanning for many instances. Discovered when trying out #1348.

#### Steps to reproduce the problem
1. Copy a bunch of instances into `/sdcard/odk/instances` (e.g. [backup1249.zip](https://github.com/opendatakit/collect/files/1155963/backup1249.zip) from @mmarciniak90)
1. Tap on "Edit Saved Form"

#### Expected behavior
No crash.

#### Other information 
I believe this is one we occasionally see in Firebase Crash.
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:318)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
	at android.content.ContentResolver.query(ContentResolver.java:549)
	at android.content.ContentResolver.query(ContentResolver.java:472)
	at org.odk.collect.android.tasks.InstanceSyncTask.doInBackground(InstanceSyncTask.java:144)
	at org.odk.collect.android.tasks.InstanceSyncTask.doInBackground(InstanceSyncTask.java:49)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
```

**Comment by lognaturel** [comment]
@srv-twry or @Yurii-Laguta, one of you may be interested in this one.

**Comment by yurilaguta** [comment]
@lognaturel it is probably caused by different thread accessing the database at the same time, I'll have a look on the weekend unless @srv-twry solves it before that.

**Comment by dr0pdb** [comment]
@lognaturel Sure i'll have a look tomorrow :smile:

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by mmarciniak90** [comment]
I was not able to reproduce this crash.
I checked on Collect v1.9.1 and v1.11.1
