### ISSUE TITLE
Crash when deleting many instances

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1351]
#### Software and hardware versions 
Collect v1.9.1

#### Problem description
Crash when deleting many instances. Discovered when verifying #1348. This doesn't happen every time but is reproducible.

#### Steps to reproduce the problem
1. Copy a bunch of instances into `/sdcard/odk/instances` (e.g. [backup1249.zip](https://github.com/opendatakit/collect/files/1155963/backup1249.zip) from @mmarciniak90)
1. Tap on "Delete Saved Form"
1. Select All Saved Forms, Delete

#### Expected behavior
No crash.

#### Other information 
```
android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
	at android.database.CursorWrapper.getCount(CursorWrapper.java:60)
	at org.odk.collect.android.activities.MainMenuActivity.updateButtons(MainMenuActivity.java:574)
	at org.odk.collect.android.activities.MainMenuActivity.access$100(MainMenuActivity.java:79)
	at org.odk.collect.android.activities.MainMenuActivity$IncomingHandler.handleMessage(MainMenuActivity.java:704)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
   Force finishing activity org.odk.collect.android/.activities.FileManagerTabs
```

**Comment by lognaturel** [comment]
@srv-twry or @Yurii-Laguta, one of you may be interested in this one.

**Comment by grzesiek2010** [comment]
Really strange. I asked @mmarciniak90 to check this scenario when she was testing https://github.com/opendatakit/collect/pull/1249 and everything was ok... I'm not sure but I think that I tested it too.

**Comment by yurilaguta** [comment]
@lognaturel given that crash happened in different activity: MainMenuActivity, the reproduction route doesn't seem to be correct.
A bit of looking at SO seems like it's a database access issue.
I've tried it few times on emulator and wasn't able to reproduce.

**Comment by lognaturel** [comment]
@Yurii-Laguta That's a good point. I know that the first time I saw the crash I tapped the back button while the instance scanning was happening. I thought I had reproduced it without tapping the back button but it's possible that wasn't the case. Could you try tapping the back button immediately when the scanning starts and seeing if you can trigger it that way?

**Comment by yurilaguta** [comment]
looks very similar to #1350 "disk I/O error (code 1802)"

**Comment by lognaturel** [comment]
@Yurii-Laguta I do think they're related and I did get them back to back. I wonder whether I may have initiated the delete while the scan was still ongoing?

Like I said, I do see a number of these kinds of errors in Firebase Crash. Is there a more graceful way to handle them across the board, perhaps?

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
@grzesiek2010 Were you able to reproduce this?

**Comment by grzesiek2010** [comment]
@lognaturel I took a quick look but I wasn't able I'll try again when I'm free.

**Comment by lognaturel** [comment]
This might be a good one to try with a slower device and fast activity changes when you have a chance, @grzesiek2010. If you can't reproduce like that we can close.

**Comment by grzesiek2010** [comment]
@lognaturel 
I wasn't able to reproduce it.

**Comment by mmarciniak90** [comment]
I also was not able to reproduce this crash. 
I checked on Collect v1.9.1 and v1.11.1
@lognaturel, maybe it is a good idea to add a progress dialog and block other actions when instances are scanned and loaded.

**Comment by shobhitagarwal1612** [comment]
Unable to reproduce the issue
