### ISSUE TITLE
The app crashes when I try to take a picture using the SelfieWidget

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1551]
#### Software and hardware versions 
Collect v1.10.2 Samsung Galaxy S7 Android 7.0 (it's visible on other devices too but less often)

#### Problem description
The app crashes when I try to take a picture using the SelfieWidget:

> FATAL EXCEPTION: CameraBackground
                                                                         Process: org.odk.collect.android, PID: 13237
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.camera2.CameraCaptureSession.capture(android.hardware.camera2.CaptureRequest, android.hardware.camera2.CameraCaptureSession$CaptureCallback, android.os.Handler)' on a null object reference
                                                                             at org.odk.collect.android.fragments.Camera2Fragment.unlockFocus(Camera2Fragment.java:839)
                                                                             at org.odk.collect.android.fragments.Camera2Fragment.access$1500(Camera2Fragment.java:79)
                                                                             at org.odk.collect.android.fragments.Camera2Fragment$6.onCaptureCompleted(Camera2Fragment.java:804)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
                                                                             at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
