### ISSUE TITLE
FileNotFoundException after cancelling and re-downloading a large form

### ISSUE THREAD

**Issue by dcbriccetti** [getodk/collect#1692]
#### Software and hardware versions 
Collect v1.11.0

#### Problem description
FileNotFoundException after cancelling and re-downloading a large form (that is already present on the device).

#### Steps to reproduce the problem
Download a large form successfully. Start, and then cancel a second download. Download it again right away. Wait for FileNotFoundException.

#### Other information 
After discussion here: https://opendatakit.slack.com/archives/C35ENHA64/p1517262884000576, it seems it is best to not start a new DownloadFormsTask (AsyncTask) until the previous one completes, since they are accessing the same forms, file system and database. Even after canceling a download, the task is blocked here: 
`parsedFields = FileUtils.parseXML(fileResult.file);`

Perhaps the progress dialog should change to `Canceling...` or something and continue to block until the download task is finished. We could also look at how to avoid the parsing blocking for a long time, perhaps by doing it in another thread, and abandoning it or killing it on cancellation.

**Comment by MrPKGupta** [comment]
Can i start working on this?

**Comment by lognaturel** [comment]
@mrgupta20 Sounds good! Please start by exploring the issue and once you have identified where you think the problem is coming from, please share your proposed approach for discussion here.

**Comment by MrPKGupta** [comment]
@dcbriccetti Not able to reproduce in Android 6.0 version. If you are still able to reproduce, please provide more details including device, android version and logs if possible. Is your device having sd card?

**Comment by grzesiek2010** [comment]
I was able to reproduce this issue on my Samsung Galaxy S4 Android 5.0.1

![ezgif com-video-to-gif 5](https://user-images.githubusercontent.com/3276264/33887975-e1567a52-df4b-11e7-8e79-e12855946860.gif)

**Comment by dr0pdb** [comment]
@mrgupta20 I was also able to reproduce it on Android 5.1.1 Oppo f1 without sd card.

#### Stacktrace
~~~
12-19 12:34:31.064 4099-4404/org.odk.collect.android E/FileUtils: java.io.FileNotFoundException: /storage/emulated/0/odk/forms/All widgets_2.xml: open failed: ENOENT (No such file or directory)
                                                                      at libcore.io.IoBridge.open(IoBridge.java:456)
                                                                      at java.io.FileInputStream.<init>(FileInputStream.java:76)
                                                                      at org.odk.collect.android.utilities.FileUtils.parseXML(FileUtils.java:298)
                                                                      at org.odk.collect.android.tasks.DownloadFormsTask.processOneForm(DownloadFormsTask.java:178)
                                                                      at org.odk.collect.android.tasks.DownloadFormsTask.doInBackground(DownloadFormsTask.java:113)
                                                                      at org.odk.collect.android.tasks.DownloadFormsTask.doInBackground(DownloadFormsTask.java:68)
                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1115)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:590)
                                                                      at java.lang.Thread.run(Thread.java:818)
                                                                   Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                      at libcore.io.Posix.open(Native Method)
                                                                      at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                                      at libcore.io.IoBridge.open(IoBridge.java:442)
                                                                      at java.io.FileInputStream.<init>(FileInputStream.java:76) 
                                                                      at org.odk.collect.android.utilities.FileUtils.parseXML(FileUtils.java:298) 
                                                                      at org.odk.collect.android.tasks.DownloadFormsTask.processOneForm(DownloadFormsTask.java:178) 
                                                                      at org.odk.collect.android.tasks.DownloadFormsTask.doInBackground(DownloadFormsTask.java:113) 
                                                                      at org.odk.collect.android.tasks.DownloadFormsTask.doInBackground(DownloadFormsTask.java:68) 
                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:292) 
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1115) 
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:590) 
                                                                      at java.lang.Thread.run(Thread.java:818)
~~~

**Comment by dr0pdb** [comment]
@lognaturel @dcbriccetti @grzesiek2010 @mrgupta20 While testing this, i found a weird behaviour.
The exception is only raised when you already have the form downloaded on your phone. I think that's why @mrgupta20 wasn't able to reproduce it.

### To raise the exception:  

1. First download the all widgets form completely in case you don't have it.
2. Then go to ```Get Blank Form``` and download the all widgets form again and cancel it instantly.
3. Now again download the all widgets form and the exception would be raised.

#### Visual
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/21277837/34146056-8cca4478-e4be-11e7-9f30-be91b702de43.gif)

### Without exception:

1. Erase the form if you have it.
2. Then go to ```Get Blank Form``` and download the form and cancel it.
3. Now again download the form and download will still succeed.

#### Visual 
![without](https://user-images.githubusercontent.com/21277837/34146164-e60af3c0-e4be-11e7-8e30-4112cdf0e7de.gif)

**Comment by dr0pdb** [comment]
@lognaturel Can i try and fix it because i guess @mrgupta20 isn't working on it anymore ?

**Comment by lognaturel** [comment]
That sounds fine to me, @srv-twry! Thanks to everyone who has looked into it.

**Comment by dr0pdb** [comment]
@opendatakit-bot claim

**Comment by lakshyagupta21** [comment]
@opendatakit-bot claim

**Comment by dcbriccetti** [comment]
Maybe the solution should be to not start a new DownloadFormsTask (AsyncTask) until the previous one stops. They can block quite a while parsing a large file.

**Comment by lakshyagupta21** [comment]
@dcbriccetti As discussed I added a cancel dialog which will be shown until the process gets terminated if user cancels the process.
I've added a delay just after the parsing so that things can be tested properly.

![ezgif-4-624852e7a2](https://user-images.githubusercontent.com/18495162/35589225-2a803cd2-0629-11e8-8696-21c87b802fc1.gif)

**Comment by dcbriccetti** [comment]
@lakshyagupta21, great, I look forward to seeing the code.
