### ISSUE TITLE
Error from CustomTabsClient.newSession results in NullPointerException

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1755]
#### Problem description
> org.odk.collect.android.utilities.CustomTabHelper$1.onCustomTabsServiceConnected (CustomTabHelper.java:43)
android.support.customtabs.CustomTabsServiceConnection.onServiceConnected (CustomTabsServiceConnection.java:32)
android.app.LoadedApk$ServiceDispatcher.doConnected (LoadedApk.java:1264)
android.app.LoadedApk$ServiceDispatcher$RunConnection.run (LoadedApk.java:1281)
android.os.Handler.handleCallback (Handler.java:815)
android.os.Handler.dispatchMessage (Handler.java:104)
android.os.Looper.loop (Looper.java:207)
android.app.ActivityThread.main (ActivityThread.java:5728)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:789)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:679)

#### Other information 
https://console.firebase.google.com/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/e54b6648?reportTypes=FATAL_JAVA&duration=2592000000

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "needs reproduction"

**Comment by lakshyagupta21** [comment]
@opendatakit-bot claim

**Comment by lakshyagupta21** [comment]
I'm not able to get the same stacktrace but I think the issue is same.

#### Software and hardware versions 
Collect v1.12.2 
Android 6.0.1

#### Problem description
If device doesn't have chrome installed on it.
#### Steps to reproduce the problem
Use Device that doesn't have Chrome app installed on it.

1. User goes to Main Menu Screen
2. Opens the Overflow menu
3. Opens 'About' Activity
4. User clicks on either 'Visit the ODK Website' or 'Join the ODK forum'

#### Expected behavior
If Chrome is not there on device then either open the url through browser or by using WebView
#### Other information 
The issue can be fixed by adding a check before opening a ChromeCustomTabs whether Chrome support is there or not on device then handling it by either webview or by opening it in browser.
```
01-27 12:55:13.954 16330-16330/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: org.odk.collect.android, PID: 16330
                                                   android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://opendatakit.org/... }
                                                       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
                                                       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1514)
                                                       at android.app.Activity.startActivityForResult(Activity.java:3963)
                                                       at android.app.Activity.startActivityForResult(Activity.java:3924)
                                                       at android.app.Activity.startActivity(Activity.java:4247)
                                                       at android.app.Activity.startActivity(Activity.java:4215)
                                                       at org.odk.collect.android.utilities.CustomTabHelper.openUri(CustomTabHelper.java:97)
                                                       at org.odk.collect.android.preferences.AboutPreferencesFragment.onPreferenceClick(AboutPreferencesFragment.java:85)
                                                       at android.preference.Preference.performClick(Preference.java:996)
                                                       at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
                                                       at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                                                       at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
                                                       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
                                                       at android.widget.AbsListView.onTouchUp(AbsListView.java:3915)
                                                       at android.widget.AbsListView.onTouchEvent(AbsListView.java:3680)
                                                       at android.view.View.dispatchTouchEvent(View.java:9311)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2548)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2241)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                       at android.app.Activity.dispatchTouchEvent(Activity.java:2805)
                                                       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                       at android.view.View.dispatchPointerEvent(View.java:9531)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4283)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4098)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3644)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3697)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3663)
                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3789)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3671)
                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3846)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3644)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3697)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3663)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3671)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3644)
                                                       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5975)
                                                       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5949)
                                                       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5910)
                                                       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6078)
                                                       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                       at android.os.MessageQueue.nativePollOnce(Native Method)
                                                       at android.os.MessageQueue.next(MessageQueue.java:323)
                                                   	at android.os.Looper.loop(Loop

```

**Comment by lakshyagupta21** [comment]
@grzesiek2010 How many instances of this error are there, I tried to reproduce this error on devices by installing/uninstalling various browsers like Chrome, Mozilla. It works perfectly fine for devices having Android versions 4.4, 5.0, 6.0.

It seems like sometimes the chrome custom tab returns null for sessions.
We can handle null pointer before launching the URL.
What do you say?

**Comment by grzesiek2010** [comment]
It's not really common 96 instances mostly from v1.12.2, 63 users impacted. I guess it might be something wrong with our implementation. Null check is the last resort.

**Comment by grzesiek2010** [comment]
Duplication of https://github.com/opendatakit/collect/issues/2316 we can close this issue.

**Comment by grzesiek2010** [comment]
Solved in https://github.com/opendatakit/collect/pull/2318

Las appearances visible on versions v1.15.x
https://play.google.com/apps/publish/?account=6923365842552008664&dev_acc=00659255839475882647#AndroidMetricsErrorsPlace:p=org.odk.collect.android&appVersion&lastReportedRange=LAST_60_DAYS&installSource=INSTALLED_FROM_ANYWHERE&clusterName=apps/org.odk.collect.android/clusters/e54b6648&detailsAppVersion&detailsInstallSource=INSTALLED_FROM_ANYWHERE

https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b11323b6007d59fcd966d2a?time=last-seven-days&sessionId=5BA2145200FE00015634B9B9B7347861_DNE_0_v2

so we can close.

**Comment by Arsenalist** [comment]
I'm getting something very similar here:

https://stackoverflow.com/questions/54831881/nullpointerexception-when-using-trusted-web-activities-on-android-multiple-devi

Can we reopen?
