### ISSUE TITLE
User is not able to see the form download results when app is minimized

### ISSUE THREAD

**Issue by lakshyagupta21** [getodk/collect#2167]
#### Software and hardware versions 
Collect v1.14.x.

#### Problem description
User is not able to see dialog showing form download results when Google Sheets is selected as server. App crashes but the user is not able to notice. I'm able to notice this through logs and then comparing form downloading behaviour when the Aggregate server is used.
#### Steps to reproduce the problem

1. Set Platform as `Google Drive, Google Sheets`
2. `Get Blank Form`
3. Select any form
4. Tap on `Download Selected`
5. Tap on `Home button` or `Switch app` to minimize the `Collect app`
6. Open app again

The user is not able to see the dialog showing the form download result as it is shown when the aggregate server is selected.

#### Expected behavior
User should be able to see the dialog showing form download result.
#### Other information 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/18495162/39650962-b7a092b0-5007-11e8-9d91-ac04fd19a773.gif)

```
05-05 01:23:41.945 13324-13324/org.odk.collect.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: org.odk.collect.android, PID: 13324
                                                                         java.lang.NullPointerException: Attempt to invoke interface method 'void org.odk.collect.android.listeners.GoogleDriveFormDownloadListener.formDownloadComplete(java.util.HashMap)' on a null object reference
                                                                             at org.odk.collect.android.activities.GoogleDriveActivity$GetFileTask.onPostExecute(GoogleDriveActivity.java:863)
                                                                             at org.odk.collect.android.activities.GoogleDriveActivity$GetFileTask.onPostExecute(GoogleDriveActivity.java:801)
                                                                             at android.os.AsyncTask.finish(AsyncTask.java:667)
                                                                             at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                             at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:163)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6221)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
```

**Comment by lognaturel** [comment]
Ohh, good catch, @lakshyagupta21!

**Comment by lakshyagupta21** [comment]
@opendatakit-bot claim
