### ISSUE TITLE
IOException while uploading instances to aggregate

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#2249]
#### Problem description
The following error is logged everytime an instance is uploaded.

```
05-27 13:22:35.686 16707-21134/org.odk.collect.android I/WebUtils: java.io.IOException: Attempted read from closed stream.
        at org.opendatakit.httpclientandroidlib.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:133)
        at org.opendatakit.httpclientandroidlib.conn.EofSensorInputStream.read(EofSensorInputStream.java:120)
        at org.odk.collect.android.utilities.WebUtils.discardEntityBytes(WebUtils.java:252)
        at org.odk.collect.android.tasks.InstanceServerUploader.uploadOneSubmission(InstanceServerUploader.java:438)
        at org.odk.collect.android.tasks.InstanceServerUploader.processChunk(InstanceServerUploader.java:556)
        at org.odk.collect.android.tasks.InstanceServerUploader.doInBackground(InstanceServerUploader.java:580)
        at org.odk.collect.android.tasks.InstanceServerUploader.doInBackground(InstanceServerUploader.java:74)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

#### Steps to reproduce the problem
Upload any instance to aggregate server.

#### Expected behavior
No error should be logged as the instance is uploaded successfully

@opendatakit-bot claim

**Comment by lognaturel** [comment]
On hold until #2257 is merged.

**Comment by grzesiek2010** [comment]
We can close this issue since it's related to httpclientandroidlib that we replaced with okhttp.
