### ISSUE TITLE
NullPointerException on FormEntryActivity pause

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#225]
As of build 1062 (1.4.11):
```
java.lang.RuntimeException: Unable to pause activity {org.odk.collect.android/org.odk.collect.android.activities.FormEntryActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3242)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3193)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3171)
	at android.app.ActivityThread.access$1000(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5292)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at org.odk.collect.android.activities.FormEntryActivity.onSaveInstanceState(FormEntryActivity.java:542)
	at android.app.Activity.performSaveInstanceState(Activity.java:1153)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1229)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3219)
```

**Comment by Bastiantheone** [comment]
Have you tried replacing the android support library with a newer version?

**Comment by MukundAnanthu** [comment]
@lognaturel @yanokwa I was not able to reproduce the error. Could you provide more details on how to do the same, and let me know how you intend to handle this issue. I am interested in taking it up..

**Comment by lognaturel** [comment]
This is something that we see at a pretty high frequency in crash logs. Unfortunately, I don't have any more information about what might be causing it. It would be great to try to narrow down some possible causes and try to reproduce it.

@Bastiantheone's comment is an interesting one. It might be that there's something missing in the current implementation.

Another thing to look into -- @grzesiek2010 has been finding some bad behavior when the app goes out of memory. #1014 and #998.

**Comment by grzesiek2010** [comment]
@lognaturel I think we can close this issue since I wasn't able to reproduce it and I'm not even able to find similar logs now on Firebase or Google play console.

**Comment by lognaturel** [comment]
We recently fixed a bunch of NPEs in `FormEntryActivity` so seems we probably addressed it then.

Last time I did an IntelliJ inspection to identify possible NPEs, there were a LOT in `FormEntryActivity` so that might be a good thing to look further into.
