### ISSUE TITLE
FileUriExposedException when taking a picture for an image question

### ISSUE THREAD

**Issue by jd-alexander** [getodk/collect#2263]
#### Software and hardware versions 
All Collect versions, Android API 24, Google Nexus 6

#### Problem description
Once the target API is set for API level 24 or greater the app crashes when you try to take a picture i.e when a file created for the image is being passed to the camera app.

` Process: org.odk.collect.android, PID: 4311
    android.os.FileUriExposedException: file:///storage/emulated/0/odk/.cache/tmp.jpg exposed beyond app through ClipData.Item.getUri()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
        at android.net.Uri.checkFileUriExposed(Uri.java:2346)`

#### Steps to reproduce the problem
Set the target API version to 24 or higher and attempt to take a picture.
#### Expected behavior
The app should launch the camera app and accept the picture that's taken as an answer.

**Comment by jd-alexander** [comment]
@opendatakit-bot claim
