### ISSUE TITLE
IllegalInstantException due to time zone offset transition

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#227]
As of build 1062 (1.4.11):
```
org.joda.time.IllegalInstantException: Illegal instant due to time zone offset transition (daylight savings time 'gap'): 2016-10-16T00:00:00.000 (America/Sao_Paulo)
	at org.joda.time.chrono.ZonedChronology.localToUTC(ZonedChronology.java:157)
	at org.joda.time.chrono.ZonedChronology.getDateTimeMillis(ZonedChronology.java:122)
	at org.joda.time.chrono.AssembledChronology.getDateTimeMillis(AssembledChronology.java:133)
	at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:257)
	at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:198)
	at org.joda.time.DateTime.<init>(DateTime.java:323)
	at org.odk.collect.android.widgets.DateWidget.getAnswer(DateWidget.java:247)
	at org.odk.collect.android.views.ODKView.getAnswers(ODKView.java:248)
	at org.odk.collect.android.activities.FormEntryActivity.saveAnswersForCurrentScreen(FormEntryActivity.java:890)
	at org.odk.collect.android.activities.FormEntryActivity.showNextView(FormEntryActivity.java:1287)
	at org.odk.collect.android.activities.FormEntryActivity.onFling(FormEntryActivity.java:2743)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:1428)
	at org.odk.collect.android.activities.FormEntryActivity.dispatchTouchEvent(FormEntryActivity.java:1260)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2254)
	at android.view.View.dispatchPointerEvent(View.java:7888)
	at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3977)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3861)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5101)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5080)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5179)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:174)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5151)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5198)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
	at android.view.Choreographer.doFrame(Choreographer.java:559)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5365)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by dizzley** [comment]
I'll take this one.
Is the issue that the user can enter invalid date/time in respect of time zone? E.g. entering 02.35 GMT on the morning when daylight savings comes in. Steps to reproduce? Thx,

**Comment by lognaturel** [comment]
@dizzley So sorry about the radio silence, I guess none of us saw this message slip in!

The trace is from Play Store and it shows up with some frequency. Reproducing the crash would be a great first step!

**Comment by grzesiek2010** [comment]
Hi @dizzley do you still work on this? any results?

**Comment by grzesiek2010** [comment]
I reproduced this issue.
Steps:

**Steps to reproduce the problem**

1. Change time zone to Sao Paulo
2. Use DateWidget or DateTimeWidget (if you use DateTimeWidget you have to set time to 00:00)
3. Enter "16 Oct 2016" (Select second 15th of Oct - look below)

**Actual behavior**
ODK crashes.

but I noticed another strange behaviour. 15.10 occurs two times in the calendar: 
![screenshot_2017-01-25-22-02-00](https://cloud.githubusercontent.com/assets/3276264/22314854/b179cc9c-e363-11e6-9cfc-c7f9002a7f85.png)

So to select 16.10 I have to click on the second 15.10 then to select 17.10 I have to click on 16.10 etc till to 21.10 then it works well but another one strange thing - 22.10 doesn't exists.

**Comment by lognaturel** [comment]
Unifying with #356.
