### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.Preference.setEnabled(boolean)' on a null object reference

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2274]
#### Software and hardware versions 
Collect v1.15.0

#### Steps to reproduce the problem
1. Go to `Admin Settings` -> `User Interface` and unselect `Automatic download`
2. Go to `General Settings` -> `Form management` and select `never` in `Periodic form updates check`

#### Other information 
> FATAL EXCEPTION: ControllerMessenger
Process: org.odk.collect.android, PID: 15091
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.Preference.setEnabled(boolean)' on a null object reference
	at org.odk.collect.android.preferences.FormManagementPreferences.lambda$initListPref$0$FormManagementPreferences(FormManagementPreferences.java:75)
	at org.odk.collect.android.preferences.FormManagementPreferences$$Lambda$0.onPreferenceChange(Unknown Source)
	at android.preference.Preference.callChangeListener(Preference.java:939)
	at android.preference.ListPreference.onDialogClosed(ListPreference.java:282)
	at android.preference.DialogPreference.onDismiss(DialogPreference.java:395)
	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1384)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.support.test.espresso.base.Interrogator.a(Interrogator.java:19)
	at android.support.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:142)
	at android.support.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:134)
	at android.support.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:114)
	at android.support.test.espresso.action.Tap$1.b(Tap.java:6)
	at android.support.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:22)
	at android.support.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:9)
	at android.support.test.espresso.ViewInteraction.a(ViewInteraction.java:78)
	at android.support.test.espresso.ViewInteraction.a(ViewInteraction.java:94)
	at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6316)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "bug"
