### ISSUE TITLE
Crash due to toggling between SMS and Internet submissions

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#2401]
#### Software and hardware versions 
Collect v1.16

#### Steps to reproduce the problem
Build a form that isn't on a server
Switch to SMS transport
Send an SMS submission with no SIM card (fails, no sim card)
Switch to Internet transport
Send the failed SMS submission (fails, no end point)
Switch to SMS transport
Send the failed SMS submission (crash)

#### Other information 
```
PlatformAlarmService: Finished job, request{id=2, tag=smsSenderJob, transient=false} FAILURE
System.err: io.reactivex.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object 
System.err: 	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
System.err: 	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
System.err: 	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
System.err: 	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
System.err: 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
System.err: 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
System.err: 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:154)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6123)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
System.err: 	at java.util.Calendar.setTime(Calendar.java:1089)
System.err: 	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:953)
System.err: 	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:946)
System.err: 	at java.text.DateFormat.format(DateFormat.java:337)
System.err: 	at org.odk.collect.android.tasks.sms.SmsService.getDisplaySubtext(SmsService.java:391)
System.err: 	at org.odk.collect.android.adapters.InstanceUploaderAdapter.setDisplaySubTextView(InstanceUploaderAdapter.java:188)
System.err: 	at org.odk.collect.android.adapters.InstanceUploaderAdapter.lambda$bindView$2$InstanceUploaderAdapter(InstanceUploaderAdapter.java:148)
System.err: 	at org.odk.collect.android.adapters.InstanceUploaderAdapter$$Lambda$2.accept(Unknown Source)
System.err: 	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)





```

**Comment by jd-alexander** [comment]
Checking this out.

**Comment by jd-alexander** [comment]
@yanokwa when you say it fails due to no endpoint how did you get that error to occur? I cant clear the current `Server` endpoint because it says that's an invalid URL.

**Comment by lognaturel** [comment]
I don’t think that part matters. I got the crash even after a successful http send (by showing sent and unsent). But you can have it fail with something like https://goooooooo.appspot.com

**Comment by jd-alexander** [comment]
Okay, still trying to reproduce the crash. Are you using a physical device to get the crash or it's via an emulator?

**Comment by lognaturel** [comment]
It was on a physical device.

**Comment by jd-alexander** [comment]
Okay just reproduced it.

**Comment by lognaturel** [comment]
And here it is "in the wild"! https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b55f9176007d59fcd7fca8d?time=last-seven-days&sessionId=5B55F944032400014A7E668B20F017D1_DNE_0_v2
