### ISSUE TITLE
attempt to re-open an already-closed object

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2583]
#### Software and hardware versions 
Collect v1.17.0 and older versions

#### Problem description
[From Crashlytics](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b0df3f56007d59fcd5762e7?time=last-seven-days&sessionId=5BAB742503D8000130A8297D7B912CBA_DNE_0_v2) (requires auth):

```
Fatal Exception: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteQuery: SELECT canEditWhenComplete, deletedDate, status, jrVersion, jrFormId, instanceFilePath, date, submissionUri, displayName, _id, displaySubtext FROM instances WHERE (status =? ) ORDER BY displayName COLLATE NOCASE ASC, status DESC
       at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:58)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:162)
       at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:134)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:236)
       at android.database.CursorWrapper.moveToPosition(CursorWrapper.java:197)
       at android.widget.CursorAdapter.getView(CursorAdapter.java:280)
       at org.odk.collect.android.adapters.ViewSentListAdapter.getView(ViewSentListAdapter.java:46)
       at android.widget.AbsListView.obtainView(AbsListView.java:2491)
       at android.widget.ListView.makeAndAddView(ListView.java:2017)
       at android.widget.ListView.fillDown(ListView.java:721)

```

**Comment by grzesiek2010** [comment]
The issue still exists so I'm reopening.
