### ISSUE TITLE
I/O error during system call, Broken pipe

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2593]
#### Software and hardware versions 
Collect v1.17.0 and older versions

#### Problem description
Trying to reproduce https://forum.opendatakit.org/t/submission-upload-error-premature-end-of-content-length-delimited-message-body/15443/4 I ran into this issue.

I used this form: 
[Media_files.xml.txt](https://github.com/opendatakit/collect/files/2429619/Media_files.xml.txt)

When it comes to files I attached:
Photos ~5mb
Video like 40s

```
09-28 21:59:17.083 4622-5952/org.odk.collect.android E/HttpClientConnection: javax.net.ssl.SSLException: Write error: ssl=0x9ab29e00: I/O error during system call, Broken pipe
        at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:794)
        at org.opendatakit.httpclientandroidlib.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:126)
        at org.opendatakit.httpclientandroidlib.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:138)
        at org.opendatakit.httpclientandroidlib.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:169)
        at org.opendatakit.httpclientandroidlib.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:115)
        at org.opendatakit.httpclientandroidlib.entity.mime.content.FileBody.writeTo(FileBody.java:121)
        at org.opendatakit.httpclientandroidlib.entity.mime.AbstractMultipartForm.doWriteTo(AbstractMultipartForm.java:134)
        at org.opendatakit.httpclientandroidlib.entity.mime.AbstractMultipartForm.writeTo(AbstractMultipartForm.java:157)
        at org.opendatakit.httpclientandroidlib.entity.mime.MultipartFormEntity.writeTo(MultipartFormEntity.java:113)
        at org.opendatakit.httpclientandroidlib.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:158)
        at org.opendatakit.httpclientandroidlib.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:162)
        at org.opendatakit.httpclientandroidlib.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:237)
        at org.opendatakit.httpclientandroidlib.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:122)
        at org.opendatakit.httpclientandroidlib.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
        at org.opendatakit.httpclientandroidlib.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.opendatakit.httpclientandroidlib.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.opendatakit.httpclientandroidlib.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.opendatakit.httpclientandroidlib.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.opendatakit.httpclientandroidlib.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.opendatakit.httpclientandroidlib.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at org.odk.collect.android.http.HttpClientConnection.uploadSubmissionFile(HttpClientConnection.java:382)
        at org.odk.collect.android.tasks.InstanceServerUploader.uploadSubmissionFile(InstanceServerUploader.java:327)
        at org.odk.collect.android.tasks.InstanceServerUploader.processChunk(InstanceServerUploader.java:142)
        at org.odk.collect.android.tasks.InstanceServerUploader.doInBackground(InstanceServerUploader.java:435)
        at org.odk.collect.android.tasks.InstanceServerUploader.doInBackground(InstanceServerUploader.java:61)
        at android.os.AsyncTask$2.call(AsyncTask.java:288)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
```
![screenshot_2018-09-28-22-12-51](https://user-images.githubusercontent.com/3276264/46231762-6b121980-c36d-11e8-8bd3-02e8ed98fbe5.png)

**Comment by grzesiek2010** [comment]
Since we switched to okhttp and I'm not able to reproduce the issue again, we can close it.
