### ISSUE TITLE
Crash when device rotates in Rank widget

### ISSUE THREAD

**Issue by akshay-ap** [getodk/collect#2742]
#### Software and hardware versions 
Collect v1.18.1, Android v7.0, device used : Moto m

#### Steps to reproduce the problem
1. Open ODK collect, download `All widgets` form.
2. Click `Fill Blank Form` and choose `All widgets`.
3. Go to Rank widget.
4. Click `Rank items` button.
5. Rotate device. (Make sure auto rotation setting is ON).
6. App crashes.

#### Expected behavior
No crash.

#### Other information 
Logs from android studio:
```
2018-11-26 19:26:23.064 17757-17757/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.odk.collect.android, PID: 17757
    java.lang.RuntimeException: Invalid query for Question prompt. Non-Question object at the form index
        at org.javarosa.form.api.FormEntryModel.getQuestionPrompt(FormEntryModel.java:170)
        at org.odk.collect.android.logic.FormController.getQuestionPrompt(FormController.java:864)
        at org.odk.collect.android.adapters.RankingListAdapter.onBindViewHolder(RankingListAdapter.java:61)
        at org.odk.collect.android.adapters.RankingListAdapter.onBindViewHolder(RankingListAdapter.java:41)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3336)
        at android.view.View.measure(View.java:20110)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6286)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1705)
        at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1279)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:659)
        at android.view.View.measure(View.java:20110)
        at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1320)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:214)
        at android.widget.ScrollView.onMeasure(ScrollView.java:345)
        at android.view.View.measure(View.java:20110)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6286)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:214)
        at android.view.View.measure(View.java:20110)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6286)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:214)
        at android.view.View.measure(View.java:20110)
        at android.support.v7.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:134)
        at android.support.v7.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:64)
        at android.view.View.measure(View.java:20110)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6286)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:214)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:20110)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6286)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:214)
        at android.view.View.measure(View.java:20110)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6286)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:214)
        at android.view.View.measure(View.java:20110)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6286)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1705)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:797)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
        at android.view.View.measure(View.java:20110)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6286)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:214)
2018-11-26 19:26:23.064 17757-17757/? E/AndroidRuntime:     at com.android.internal.policy.DecorView.onMeasure(DecorView.java:714)
        at android.view.View.measure(View.java:20110)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2649)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1557)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1855)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1471)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7009)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:907)
        at android.view.Choreographer.doCallbacks(Choreographer.java:709)
        at android.view.Choreographer.doFrame(Choreographer.java:644)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6293)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1065)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)

```

**Comment by akshay-ap** [comment]
<img src="https://user-images.githubusercontent.com/16358982/49018393-54434400-f1b1-11e8-9fb0-4ceaf899c551.gif" width=35%></img>

**Comment by ajwad-shaikh** [comment]
@opendatakit-bot claim

**Comment by ajwad-shaikh** [comment]
@shobhitagarwal1612  Need some help. I want my fork rebased to work on this issue but I'm worried that it will add unnecessary commits to my open PR #2736 . Is there a workaround? The PR is behavior verified and ready for merge, I guess. That if you merge is one way. Am I missing something else?

**Comment by ajwad-shaikh** [comment]
@shobhitagarwal1612 
I added the fixing commits to my earlier PR.
I understood that I should work on different branches for each issue and then send a PR accordingly.
It was too late though. I am slowly getting comfortable with Git. I apologise for being such a novice.
Let me know if there's anything I can do to sort this out. Rest assured, the issues have been fixed.
Thanks.
