### ISSUE TITLE
App crashes if the user opens some GeoWidget with Google Map and immediately changes device orientation

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2979]
#### Software and hardware versions 
Collect v1.21 beta 0

#### Problem description
App crashes if the user opens some GeoWidget with Google Map and immediately changes device orientation

#### Steps to reproduce the problem
1. User opens some Geo Widget with map 
2. User immediately changes device orientation
3. App crashes

[crashGeoPoint2.txt](https://github.com/opendatakit/collect/files/3029551/crashGeoPoint2.txt)

#### Expected behavior
* Collect does not crash

**Comment by zestyping** [comment]
Relevant stack trace:

<pre>
Process: org.odk.collect.android, PID: 14731
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.content.Context.getDrawable(int)' on a null object reference
 	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:463)
 	at org.odk.collect.android.utilities.IconUtils.getBitmap(IconUtils.java:41)
 	at org.odk.collect.android.map.GoogleMapFragment.getBitmapDescriptor(GoogleMapFragment.java:503)
 	at org.odk.collect.android.map.GoogleMapFragment.updateLocationIndicator(GoogleMapFragment.java:340)
 	at org.odk.collect.android.map.GoogleMapFragment.onLocationChanged(GoogleMapFragment.java:330)
 	at org.odk.collect.android.location.client.AndroidLocationClient.onLocationChanged(AndroidLocationClient.java:156)
 	at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:297)
</pre>
