### ISSUE TITLE
Column 'MAX(date)' does not exist

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#3222]
This issue happened in the pre-launch report on an Android 6.0 device running French. 

**Devices tested**
<img width="978" alt="Screen Shot 2019-07-18 at 9 31 40 AM" src="https://user-images.githubusercontent.com/32369/61475090-e6fe4200-a93e-11e9-9926-83c4850a8a50.png">

**Device with the failure**
<img width="986" alt="Screen Shot 2019-07-18 at 9 31 52 AM" src="https://user-images.githubusercontent.com/32369/61475091-e796d880-a93e-11e9-877e-3cc78a930a16.png">

**Stack trace**
```
FATAL EXCEPTION: ControllerMessenger
Process: org.odk.collect.android, PID: 29336
java.lang.IllegalArgumentException: column 'MAX(date)' does not exist
	at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:333)
	at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:87)
	at android.widget.SimpleCursorAdapter.findColumns(SimpleCursorAdapter.java:333)
	at android.widget.SimpleCursorAdapter.swapCursor(SimpleCursorAdapter.java:345)
	at org.odk.collect.android.activities.FormChooserList.onLoadFinished(SourceFile:232)
	at org.odk.collect.android.activities.FormChooserList.onLoadFinished(SourceFile:55)
	at androidx.loader.app.LoaderManagerImpl$LoaderObserver.onChanged(SourceFile:250)
	at androidx.lifecycle.LiveData.considerNotify(SourceFile:131)
	at androidx.lifecycle.LiveData.dispatchingValue(SourceFile:149)
	at androidx.lifecycle.LiveData.setValue(SourceFile:307)
	at androidx.lifecycle.MutableLiveData.setValue(SourceFile:50)
	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setValue(SourceFile:189)
	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(SourceFile:174)
	at androidx.loader.content.Loader.deliverResult(SourceFile:132)
	at androidx.loader.content.CursorLoader.deliverResult(SourceFile:109)
	at androidx.loader.content.CursorLoader.deliverResult(SourceFile:41)
	at androidx.loader.content.AsyncTaskLoader.dispatchOnLoadComplete(SourceFile:258)
	at androidx.loader.content.AsyncTaskLoader$LoadTask.onPostExecute(SourceFile:83)
	at androidx.loader.content.ModernAsyncTask.finish(SourceFile:490)
	at androidx.loader.content.ModernAsyncTask$InternalHandler.handleMessage(SourceFile:507)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:19)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:166)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:158)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:34)
	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:77)
	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:52)
	at androidx.test.espresso.action.Tap.c(Tap.java:8)
	at androidx.test.espresso.action.Tap.b(Tap.java:18)
	at androidx.test.espresso.action.Tap$1.a(Tap.java:3)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:20)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:9)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:79)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:96)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5585)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

**Comment by yanokwa** [comment]
I've seen the crashes in Firebase as well on an Android 9 device.

```
Fatal Exception: java.lang.IllegalArgumentException: column 'MAX(date)' does not exist. Available columns: [jrFormId, date, displayName, description, language, formFilePath, lastDetectedFormVersionHash, autoSubmit, md5Hash, autoDelete, jrVersion, formMediaPath, _id, jrcacheFilePath, submissionUri, base64RsaPublicKey]
       at android.database.AbstractCursor.getColumnIndexOrThrow + 340(AbstractCursor.java:340)
       at android.database.CursorWrapper.getColumnIndexOrThrow + 87(CursorWrapper.java:87)
       at android.widget.SimpleCursorAdapter.findColumns + 333(SimpleCursorAdapter.java:333)
       at android.widget.SimpleCursorAdapter.swapCursor + 345(SimpleCursorAdapter.java:345)
       at org.odk.collect.android.activities.FormChooserList.onLoadFinished + 232(FormChooserList.java:232)
       at org.odk.collect.android.activities.FormChooserList.onLoadFinished + 55(FormChooserList.java:55)
       at androidx.loader.app.LoaderManagerImpl$LoaderObserver.onChanged + 250(LoaderManagerImpl.java:250)
       at androidx.lifecycle.LiveData.considerNotify + 131(LiveData.java:131)
       at androidx.lifecycle.LiveData.dispatchingValue + 149(LiveData.java:149)
       at androidx.lifecycle.LiveData.setValue + 307(LiveData.java:307)
       at androidx.lifecycle.MutableLiveData.setValue + 50(MutableLiveData.java:50)
       at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setValue + 189(LoaderManagerImpl.java:189)
       at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onLoadComplete + 174(LoaderManagerImpl.java:174)
       at androidx.loader.content.Loader.deliverResult + 132(Loader.java:132)
       at androidx.loader.content.CursorLoader.deliverResult + 109(CursorLoader.java:109)
       at androidx.loader.content.CursorLoader.deliverResult + 41(CursorLoader.java:41)
       at androidx.loader.content.AsyncTaskLoader.dispatchOnLoadComplete + 258(AsyncTaskLoader.java:258)
       at androidx.loader.content.AsyncTaskLoader$LoadTask.onPostExecute + 83(AsyncTaskLoader.java:83)
       at androidx.loader.content.ModernAsyncTask.finish + 490(ModernAsyncTask.java:490)
       at androidx.loader.content.ModernAsyncTask$InternalHandler.handleMessage + 507(ModernAsyncTask.java:507)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 214(Looper.java:214)
       at android.app.ActivityThread.main + 7045(ActivityThread.java:7045)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 493(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main + 965(ZygoteInit.java:965)
```

The commit that revealed this bug is at https://github.com/opendatakit/collect/commit/20cc113f885b653c8d3b418f9e31a34e7ac0bb04

**Comment by grzesiek2010** [comment]
I was able to reproduce the issue.
Steps:
1. Go to `General Settings` -> `Form management` and unselect `Hide old form versions` option.
2. Click on `Fill Blank Form` from the main menu.
