### ISSUE TITLE
Crash when user loads form with rating widgets

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3384]
#### Software and hardware versions 
Collect master
Crash does not occur on v1.23.3

#### Problem description
Crash when user loads form with rating widgets

#### Steps to reproduce the problem
1.  User loads form
[TestRatingWidget.xml.txt](https://github.com/opendatakit/collect/files/3711553/TestRatingWidget.xml.txt)

#### Expected behavior
* User is able to fill the form

#### Other information 
2019-10-10 11:25:28.039 16517-16517/org.odk.collect.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.odk.collect.android, PID: 16517
    java.lang.ClassCastException: android.widget.ImageButton cannot be cast to android.view.ViewGroup
        at androidx.fragment.app.FragmentManager.getFragmentContainer(FragmentManager.java:2612)
        at androidx.fragment.app.FragmentManager.setVisibleRemovingFragment(FragmentManager.java:2596)
        at androidx.fragment.app.FragmentManager.removeFragment(FragmentManager.java:1911)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:408)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2584)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2372)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2327)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2230)
        at androidx.fragment.app.FragmentManager$3.run(FragmentManager.java:414)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by mmarciniak90** [comment]
@opendatakit-bot label "regression"
