### ISSUE TITLE
Collect crashes when use range picker integer widget on fieldlist form

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#3388]
#### Software and hardware versions 
Collect v1.24.x, Android v5.1, 7.0, other versions probably too, device used...

#### Problem description
Collects crashes after choosing an answer on number picker of range picker integer widget on fieldlist type of form. 
logs:
`2019-10-11 15:51:22.821 27776-27776/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.odk.collect.android, PID: 27776
    java.lang.ClassCastException: android.widget.ImageButton cannot be cast to android.view.ViewGroup
        at androidx.fragment.app.FragmentManager.getFragmentContainer(SourceFile:2612)
        at androidx.fragment.app.FragmentManager.setVisibleRemovingFragment(SourceFile:2596)
        at androidx.fragment.app.FragmentManager.removeFragment(SourceFile:1911)
        at androidx.fragment.app.BackStackRecord.executeOps(SourceFile:408)
        at androidx.fragment.app.FragmentManager.executeOps(SourceFile:2584)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:2372)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:2327)
        at androidx.fragment.app.FragmentManager.execPendingActions(SourceFile:2230)
        at androidx.fragment.app.FragmentManager$3.run(SourceFile:414)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6165)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
2019-10-11 15:51:22.825 1971-5829/? W/ActivityManager:   Force finishing activity org.odk.collect.android/.activities.FormEntryActivity
2019-10-11 15:51:22.831 2745-8399/? D/ProcSpeedReader: Failed to read freq stats from null
2019-10-11 15:51:22.840 27776-27797/? D/FA: Logging event (FE): app_exception(_ae), Bundle[{ga_event_origin(_o)=clx, _r=1, ga_screen_class(_sc)=FormEntryActivity, ga_screen_id(_si)=351454521024416429, timestamp=1570801882690, fatal=1}]
2019-10-11 15:51:22.899 27776-27797/? V/FA: Connecting to remote service
2019-10-11 15:51:22.908 1971-32605/? I/OpenGLRenderer: Initialized EGL, version 1.4
2019-10-11 15:51:22.908 1971-32605/? D/OpenGLRenderer: Swap behavior 1
2019-10-11 15:51:22.910 27776-27797/? V/FA: Recording user engagement, ms: 21132
2019-10-11 15:51:22.958 27776-27797/? D/FA: Logging event (FE): user_engagement(_e), Bundle[{ga_event_origin(_o)=auto, engagement_time_msec(_et)=21132, ga_screen_class(_sc)=FormEntryActivity, ga_screen_id(_si)=351454521024416429}]
2019-10-11 15:51:22.997 27776-27797/? V/FA: Connection attempt already in progress
2019-10-11 15:51:23.331 1971-2042/? W/ActivityManager: Activity pause timeout for ActivityRecord{81d424c u0 org.odk.collect.android/.activities.FormEntryActivity t353 f}
2019-10-11 15:51:23.344 2745-8399/? D/ProcSpeedReader: Failed to read freq stats from null
2019-10-11 15:51:23.701 27776-27814/? I/CrashlyticsCore: Crashlytics report upload complete: 5DA0889B034E-0001-6C80-912E33D373F2
2019-10-11 15:51:28.373 347-557/? I/SFPerfTracer:      triggers: (rate: 0:0) (9379 sw vsyncs) (0 skipped) (339:157152 vsyncs) (341:209922)
2019-10-11 15:51:28.386 347-347/? I/SFPerfTracer:      triggers: (rate: 83:5445) (compose: 10:477) (post: 1:337) (render: 47:1653) (320:149246 frames) (321:206976)
2019-10-11 15:51:28.387 347-347/? D/SFPerfTracer:        layers: (5:11) (StatusBar (0xa6f9d400): 321:84446) (com.android.systemui.ImageWallpaper (0xa6f92400): 321:63300)* (DimLayerController/Stack=0 (0xa6f9fc00): 9:9416) (animation background stackId=1 (0xa6f9e800): 0:686)* (Sprite (0xa7b40400): 0:14)* (com.google.android.apps.docs/com.google.android.apps.docs.doclist.documentopener.DocumentOpenerActivityDelegate (0xa6f94c00): 321:22290)* (com.google.android.apps.docs/com.google.android.apps.docs.doclist.activity.DocListActivity (0xa6f9c000): 321:22303)* (NavigationBar (0xa6f91000): 321:2226) (org.odk.collect.android/org.odk.collect.android.activities.FormEntryActivity (0xa7b41800): 321:762) (org.odk.collect.android/org.odk.collect.android.activities.FormEntryActivity (0xa6f93800): 0:100)- (Application Error: org.odk.collect.android (0xa6f93800): 321:328) `

#### Steps to reproduce the problem
1. Open attached form
2. Go to range picker integer widget question, open number picker, choose an answer

#### Expected behavior
App should not crash. 

#### Other information 
Form that I have used for testing: 
[all-widgets-fieldlist-noosm.xml.txt](https://github.com/opendatakit/collect/files/3717903/all-widgets-fieldlist-noosm.xml.txt)
App does not crash when use that wigdet in regular All widgets form.

**Comment by mmarciniak90** [comment]
@opendatakit-bot label "regression"
