### ISSUE TITLE
RuntimeException: Dependency cycles amongst the xpath expressions in relevant/calculate

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3398]
#### Software and hardware versions 
Collect v1.24.0-beta

#### Problem description
https://console.firebase.google.com/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/4788f4010fa43b71da174536467e7b4a?time=last-seven-days&sessionId=5DA6F10300770001699B912E33D373F2_DNE_0_v2

`Caused by java.lang.RuntimeException: Dependency cycles amongst the xpath expressions in relevant/calculate
       at org.javarosa.core.model.IDag.reportDependencyCycles(IDag.java:473)
       at org.javarosa.core.model.FormDef.reportDependencyCycles(FormDef.java:723)
       at org.javarosa.xform.parse.XFormParser.checkDependencyCycles(XFormParser.java:2161)
       at org.javarosa.xform.parse.XFormParser.addMainInstanceToFormDef(XFormParser.java:1933)
       at org.javarosa.xform.parse.XFormParser.parseDoc(XFormParser.java:532)
       at org.javarosa.xform.parse.XFormParser.parse(XFormParser.java:387)
       at org.javarosa.xform.util.XFormUtils.getFormFromFormXml(XFormUtils.java:123)
       at org.odk.collect.android.tasks.FormLoaderTask.createFormDefFromCacheOrXml(FormLoaderTask.java:244)
       at org.odk.collect.android.tasks.FormLoaderTask.doInBackground(FormLoaderTask.java:147)
       at org.odk.collect.android.tasks.FormLoaderTask.doInBackground(FormLoaderTask.java:68)
       at android.os.AsyncTask$2.call(AsyncTask.java:305)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)`

#### Steps to reproduce the problem
Try to use this form: 
[asasas.txt](https://github.com/opendatakit/collect/files/3738390/asasas.txt)

#### Expected behavior
The exception should be caught.

**Comment by grzesiek2010** [comment]
@lognaturel 
This and https://github.com/opendatakit/collect/pull/3397 and https://github.com/opendatakit/collect/pull/3396 and probably something else is caused by https://github.com/opendatakit/collect/pull/3272 and removed try/catch

I think the right solution would be to keep only this pr https://github.com/opendatakit/collect/pull/3396 but catch `Exception | Error e` there instead of just `XFormParseException` that would allow us to catch all exceptions. Do you agree?

**Comment by lognaturel** [comment]
> keep only this pr #3396 but catch `Exception | Error e` there instead of just XFormParseException

That sounds good to me, please Make It So. I think letting any problems propagate all the way to `doInBackground` makes a lot of sense.

For some reason I thought that Android Studio provided more feedback when calling a method that is explicitly declared to throw. I'm currently not seeing any warning and I think that's why I removed the try/catch block in the first place -- I didn't see any IDE hints and so I thought that the call was safe.
