### ISSUE TITLE
Three OkHttpOpenRosaServerClientProviderTest fail under some circumstances

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3453]
There are 4 `OkHttpOpenRosaServerClientProviderTest` that use `MockWebServer`. Three of them fail for some configurations. I can get them to fail when running `./gradlew testDebugUnitTest` but not when running from Android Studio.

Changing `httpsMockWebServer.start(8443)` to `httpsMockWebServer.start()` in the mock makes the tests pass but it points to a possible cleanup issue that would be good to understand and fix.

```
java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:8443
    at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:249)
    at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:167)
    at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
    at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
    at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
    at com.burgstaller.okhttp.AuthenticationCacheInterceptor.intercept(AuthenticationCacheInterceptor.java:50)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:250)
    at okhttp3.RealCall.execute(RealCall.java:93)
    at org.odk.collect.android.http.openrosa.okhttp.OkHttpOpenRosaServerClientProvider$OkHttpOpenRosaServerClient.makeRequest(OkHttpOpenRosaServerClientProvider.java:105)
    at org.odk.collect.android.http.OpenRosaServerClientProviderTest.withCredentials_onceBasicChallenged_whenHttps_proactivelySendsCredentials(OpenRosaServerClientProviderTest.java:149)
```

Slack conversation at https://opendatakit.slack.com/archives/C35ENHA64/p1573167021119600

CC @shouryaj

**Comment by breakbusyloop** [comment]
I have not once seen this in my Windows development environment since it was originally reported on Slack. Today I've run `gradlew testDebugUnitTest` three times and didn't see the test failures.

**Comment by seadowg** [comment]
Looks like these tests are still a problem (from https://app.circleci.com/pipelines/github/opendatakit/collect/139/workflows/a8fe11bb-8bb9-4fe3-9e2a-fdca7ffba8ea/jobs/8502):

```
org.odk.collect.android.openrosa.OkHttpOpenRosaServerClientProviderTest > withCredentials_onceDigestChallenged_whenHttps_proactivelySendsCredentials FAILED
    javax.net.ssl.SSLHandshakeException at Alerts.java:192
        Caused by: sun.security.validator.ValidatorException at PKIXValidator.java:380
            Caused by: sun.security.validator.ValidatorException at PKIXValidator.java:404



org.odk.collect.android.openrosa.OkHttpOpenRosaServerClientProviderTest > withCredentials_onceBasicChallenged_whenHttps_proactivelySendsCredentials FAILED
    javax.net.ssl.SSLHandshakeException at Alerts.java:192
        Caused by: sun.security.validator.ValidatorException at PKIXValidator.java:380
            Caused by: sun.security.validator.ValidatorException at PKIXValidator.java:404



org.odk.collect.android.openrosa.OkHttpOpenRosaServerClientProviderTest > withCredentials_whenDigestChallengeReceived_whenHttps_retriesWithCredentials FAILED
    javax.net.ssl.SSLHandshakeException at Alerts.java:192
        Caused by: sun.security.validator.ValidatorException at PKIXValidator.java:380
            Caused by: sun.security.validator.ValidatorException at PKIXValidator.java:404
```

**Comment by seadowg** [comment]
Not seeing this at all anymore. I'm guessing an update to OkHttp fixed it.
