### ISSUE TITLE
Downloading forms from Google Drive fails 

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#3468]
At first, I thought the failure was because of the new google-services.json file we are using, so I went back to v1.24 to try to get a working example.

v1.24 works great with the old JSON file. v1.25 fails with that same file. 

I’ve narrowed it down to this commit: https://github.com/opendatakit/collect/commit/2463cfe567aeb059f2908791c336e401670c956d  that puts this error in the logs.

```
com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "usageLimits",
    "reason" : "dailyLimitExceededUnreg",
    "message" : "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp" : "https://code.google.com/apis/console"
  } ],
  "message" : "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
}
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(SourceFile:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(SourceFile:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(SourceFile:443)
	at com.google.api.client.http.HttpRequest.execute(SourceFile:1092)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(SourceFile:541)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(SourceFile:474)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(SourceFile:591)
	at org.odk.collect.android.utilities.gdrive.DriveHelper$DriveService.getFileId(SourceFile:278)
	at org.odk.collect.android.utilities.gdrive.DriveHelper.getRootFolderId(SourceFile:67)
	at org.odk.collect.android.activities.GoogleDriveActivity$RetrieveDriveFileContentsAsyncTask.doInBackground(SourceFile:647)
	at org.odk.collect.android.activities.GoogleDriveActivity$RetrieveDriveFileContentsAsyncTask.doInBackground(SourceFile:616)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Unable to fetch drive contents
```

**Comment by yanokwa** [comment]
@grzesiek2010 I played around with this on Friday. I believe the problem is that in the google-services.json files we have in the repo, we don't have the oauth_client details either set correctly in the file or set correctly in Google Cloud Console or Firebase. 

I'd recommend you start with the v1.25.0-beta tag and see if you can get either the debug or release build working with Google Drive. If you can get that working, it should be easy to do it for the odkrelease build.
