### ISSUE TITLE
IllegalArgumentException in FormEntryActivity:2550

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#3547]
#### Software and hardware versions 
Collect v1.25.0

#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/a6190e498dbd71af76c7d825dbd1bb56?time=last-seven-days&sessionId=5DFA2430019C0001345DECEDA34F01BD_DNE_0_v2

`Fatal Exception: java.lang.IllegalArgumentException: no dialog with id 2 was ever shown via Activity#showDialog
       at android.app.Activity.missingDialog(Activity.java:4232)
       at android.app.Activity.dismissDialog(Activity.java:4217)
       at org.odk.collect.android.activities.FormEntryActivity.savingComplete(FormEntryActivity.java:2550)
       at org.odk.collect.android.tasks.SaveToDiskTask.onPostExecute(SaveToDiskTask.java:582)
       at org.odk.collect.android.tasks.SaveToDiskTask.onPostExecute(SaveToDiskTask.java:72)
       at android.os.AsyncTask.finish(AsyncTask.java:695)
       at android.os.AsyncTask.access$600(AsyncTask.java:180)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7135)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)`

**Comment by seadowg** [comment]
PR just waiting for QA!
