### ISSUE TITLE
ODK crashes after entering "1 Jan 1960" in Nairobi time zone

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#356]
#### Software and hardware versions 
Discovered on Collect v1.4.12, Android v5.0.1, Samsung Galaxy S4

#### Problem description
ODK crashes after entering "1 Jan 1960" in Nairobi time zone

#### Steps to reproduce the problem
1. Change time zone to Nairobi (East Africa Time Zone (GMT+03:00))
2. Use DateWidget or DateTimeWidget (if you use DateTimeWidget you have to set time to 00:00)
3. Enter "1 Jan 1960"

#### Actual behavior
ODK crashes.
#### Other information 
> org.joda.time.IllegalInstantException: Illegal instant due to time zone offset transition (daylight savings time 'gap'): 1960-01-01T00:00:00.000 (Africa/Nairobi)
                                                                           at org.joda.time.chrono.ZonedChronology.localToUTC(ZonedChronology.java:157)
                                                                           at org.joda.time.chrono.ZonedChronology.getDateTimeMillis(ZonedChronology.java:122)
                                                                           at org.joda.time.chrono.AssembledChronology.getDateTimeMillis(AssembledChronology.java:133)
                                                                           at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:257)
                                                                           at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:198)
                                                                           at org.joda.time.DateTime.<init>(DateTime.java:397)
                                                                           at org.odk.collect.android.widgets.DateTimeWidget.getAnswer(DateTimeWidget.java:295)
                                                                           at org.odk.collect.android.views.ODKView.getAnswers(ODKView.java:265)
                                                                           at org.odk.collect.android.activities.FormEntryActivity.saveAnswersForCurrentScreen(FormEntryActivity.java:918)
                                                                           at org.odk.collect.android.activities.FormEntryActivity.showNextView(FormEntryActivity.java:1282)
                                                                           at org.odk.collect.android.activities.FormEntryActivity.onFling(FormEntryActivity.java:2789)
                                                                           at android.view.GestureDetector.onTouchEvent(GestureDetector.java:620)
                                                                           at org.odk.collect.android.activities.FormEntryActivity.dispatchTouchEvent(FormEntryActivity.java:1255)

This has also been reproduced with:
- the Sao Paulo time zone and "16 Oct 2016" as the date ([here](https://github.com/opendatakit/collect/issues/227#issuecomment-275272870), note also the crazy calendar issues which may or may not be related)
- an unspecified time zone and May 01 1990 in issue #145 
- the Peru time zone and "1 Jan 1990/1994/1986/1987" in #217

**Comment by lognaturel** [comment]
Is it only 1/1/1960 that crashes or all dates before 1/1/1970 (epoch)? Could it be related to #150? It sounds like that one is more related to device settings but perhaps there's some connection.

**Comment by lognaturel** [comment]
Actually, it doesn't seem related to #150. 

It's the same stack trace as #227, #145, and #217 and I think all 4 are the same issue.

**Comment by grzesiek2010** [comment]
Yes I think we should gather this issue and #227 #145 #217 in a one issue.

**Comment by lognaturel** [comment]
We're currently using Joda 2.9.3 but 2.9.7 is available. I think we should start by updating Joda (from Maven so we can delete the jar) and seeing if by any chance this could be fixed.

If not, it would be good to throw up an error to the effect of "Due to a timezone bug, this date and timezone combination cannot be used." Even better if it can show the current timezone to the user. [This Stackoverflow](http://stackoverflow.com/questions/5451152/how-to-handle-jodatime-illegal-instant-due-to-time-zone-offset-transition) thread might also have some ideas.

**Comment by lognaturel** [comment]
Also, if the crazy calendar issue in #227 doesn't end up being related, it should be separately filed.

**Comment by grzesiek2010** [comment]
Yes this calendar issue still occurs. I created new issue for that: #383
