### ISSUE TITLE
Collect crashes when the map button is clicked if at least one point is set

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3651]
#### Software and hardware versions 
Collect master

#### Problem description
Collect crashes when the map button is clicked if at least one point is set

#### Steps to reproduce the problem
1. User fills `All widgets` form 
2. User adds a location to Geopoint question 
3. User leaves jobs (completed or not)
4. User goes to `Fill Blank Form` and clicks on the map button 
5. Collect crashes

#### Expected behavior
The map view is opened and added point is visible

**Comment by mmarciniak90** [comment]
2020-02-25 11:18:03.066 29963-29963/org.odk.collect.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.odk.collect.android, PID: 29963
    java.lang.RuntimeException: Unable to resume activity {org.odk.collect.android/org.odk.collect.android.activities.FormMapActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.maps.model.Marker.setIcon(com.google.android.gms.maps.model.BitmapDescriptor)' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3788)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3828)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2991)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.maps.model.Marker.setIcon(com.google.android.gms.maps.model.BitmapDescriptor)' on a null object reference
        at org.odk.collect.android.geo.GoogleMapFragment$MarkerFeature.setIcon(GoogleMapFragment.java:637)
        at org.odk.collect.android.geo.GoogleMapFragment.setMarkerIcon(GoogleMapFragment.java:240)
        at org.odk.collect.android.activities.FormMapActivity.updateMapFeatures(FormMapActivity.java:206)
        at org.odk.collect.android.activities.FormMapActivity.updateInstanceGeometry(FormMapActivity.java:182)
        at org.odk.collect.android.activities.FormMapActivity.onResume(FormMapActivity.java:130)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1277)
        at android.app.Activity.performResume(Activity.java:7058)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3765)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3828) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2991) 
        at android.app.ActivityThread.-wrap14(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6692) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by lognaturel** [comment]
I talked to @grzesiek2010 and said I'd take this on since it's code I recently touched. He pointed me in the right direction.
