### ISSUE TITLE
Crash on showing dialog in `FormEntryActivity`

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#3716]
#### Software and hardware versions

Collect v1.26.0

#### Problem description

Crash seen here: https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/bf051feb273e3d30681ddb9a2ddd904e?time=last-seven-days&sessionId=5E708A2A032800013C6E3F1318645699_DNE_2_v2

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=42, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {org.odk.collect.android/com.karumi.dexter.DexterActivity}: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5004)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5047)
       at android.app.ActivityThread.access$1600(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7406)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Caused by java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1536)
       at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1558)
       at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:317)
       at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:282)
       at androidx.fragment.app.DialogFragment.show(DialogFragment.java:172)
       at org.odk.collect.android.utilities.DialogUtils.showIfNotShowing(DialogUtils.java:159)
       at org.odk.collect.android.activities.FormEntryActivity.loadFromIntent(FormEntryActivity.java:628)
       at org.odk.collect.android.activities.FormEntryActivity.loadForm(FormEntryActivity.java:504)
       at org.odk.collect.android.activities.FormEntryActivity.access$200(FormEntryActivity.java:202)
       at org.odk.collect.android.activities.FormEntryActivity$9.granted(FormEntryActivity.java:2339)
       at org.odk.collect.android.utilities.PermissionUtils$8.granted(PermissionUtils.java:233)
       at org.odk.collect.android.utilities.PermissionUtils$10.onPermissionGranted(PermissionUtils.java:283)
       at com.karumi.dexter.MultiplePermissionsListenerToPermissionListenerAdapter.onPermissionsChecked(MultiplePermissionsListenerToPermissionListenerAdapter.java)
       at com.karumi.dexter.MultiplePermissionListenerThreadDecorator$1.run(MultiplePermissionListenerThreadDecorator.java)
       at com.karumi.dexter.MainThread.execute(MainThread.java)
       at com.karumi.dexter.MultiplePermissionListenerThreadDecorator.onPermissionsChecked(MultiplePermissionListenerThreadDecorator.java)
       at com.karumi.dexter.DexterInstance.onPermissionsChecked(DexterInstance.java)
       at com.karumi.dexter.DexterInstance.updatePermissionsAsGranted(DexterInstance.java)
       at com.karumi.dexter.DexterInstance.onPermissionRequestGranted(DexterInstance.java)
       at com.karumi.dexter.Dexter.onPermissionsRequested(Dexter.java)
       at com.karumi.dexter.DexterActivity.onRequestPermissionsResult(DexterActivity.java)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7291)
       at android.app.Activity.dispatchActivityResult(Activity.java:7169)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5000)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5047)
       at android.app.ActivityThread.access$1600(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7406)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

#### Steps to reproduce the problem

Will investigate and see if I can work out a way to repoduce.

#### Expected behavior

No crash!

**Comment by grzesiek2010** [comment]
This is how we used to deal with such problems:
https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/GoogleSheetsUploaderProgressDialog.java#L70

**Comment by seadowg** [comment]
@grzesiek2010 ah cool thanks. So weird that you'd have to do that! I'll have a play and see if I can reproduce (it looks like it could have something to do with granting/denying permissions and closing an activity) but we can always just incorporate that in our `showIfNotShowing`

**Comment by grzesiek2010** [comment]
> but we can always just incorporate that in our showIfNotShowing

yeah it's not harmful at all so we can add it just in case.
