### ISSUE TITLE
Unable to Save to Drive/Attach to Mail QR Code on Android 5.1 Huawei Y560-L01

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#3826]
#### Software and hardware versions 
Collect v1.26.x, Android v5.1.x, device used: Huawei Y560-L01

#### Problem description
I have noticed a problem with sharing QR code on my device with Android 5.1.
Google drive seem to crash when try to save file with QR code on Huawei Y560-L01 device. 
stacktrace:
`05-13 12:44:55.935 11606-11606/? E/CAKEMIX_CRASHED: [main] java.lang.SecurityException: Uid 10050 does not have permission to uri 0 @ content://org.odk.collect.android.provider/external_files/Android/data/org.odk.collect.android/files/settings/collect-settings.png
        at android.os.Parcel.readException(Parcel.java:1546)
        at android.os.Parcel.readException(Parcel.java:1499)
        at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2448)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1496)
        at android.app.Activity.startActivityForResult(Activity.java:3794)
        at ci.startActivityForResult(PG:3)
        at ltq.startActivityForResult(PG:2)
        at android.app.Activity.startActivityForResult(Activity.java:3755)
        at ci.startActivityForResult(PG:1)
        at ltq.startActivityForResult(PG:1)
        at android.app.Activity.startActivity(Activity.java:4065)
        at ltq.startActivity(PG:2)
        at android.app.Activity.startActivity(Activity.java:4033)
        at ltq.startActivity(PG:1)
        at hjz.onClick(PG:34)
        at android.support.v7.app.AlertController$b.handleMessage(PG:3)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5298)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
05-13 12:44:56.124 831-857/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
05-13 12:44:56.243 831-2882/? E/InputDispatcher: channel 'd0e9813 com.google.android.apps.docs/com.google.android.apps.docs.shareitem.UploadMenuActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
05-13 12:44:56.612 11856-11856/? E/art: ClassLinker::FindClass not found:Landroid/provider/DocumentsContract$Path;
05-13 12:44:56.627 11856-11856/? E/art: ClassLinker::FindClass not found:Landroid/provider/DocumentsContract$Path;
05-13 12:44:56.629 11856-11856/? E/art: ClassLinker::FindClass not found:Landroid/provider/DocumentsContract$Path;
05-13 12:44:56.631 11856-11856/? E/art: ClassLinker::FindClass not found:Landroid/provider/DocumentsContract$Path;
05-13 12:44:56.633 11856-11856/? E/art: ClassLinker::FindClass not found:Landroid/provider/DocumentsContract$Path;
05-13 12:44:56.687 11856-11856/? E/art: ClassLinker::FindClass not found:Landroid/app/NotificationChannel;
05-13 12:44:56.718 11856-11856/? E/art: ClassLinker::FindClass not found:Lcom/google/protobuf/DescriptorMessageInfoFactory;
05-13 12:44:56.721 11856-11856/? E/art: ClassLinker::FindClass not found:Lcom/google/protobuf/GeneratedMessage;
05-13 12:44:56.722 11856-11856/? E/art: ClassLinker::FindClass not found:Lcom/google/protobuf/UnknownFieldSetSchema;
05-13 12:44:56.723 11856-11856/? E/art: ClassLinker::FindClass not found:Lcom/google/protobuf/UnknownFieldSetSchema;
05-13 12:44:56.726 11856-11856/? E/art: ClassLinker::FindClass not found:Lcom/google/protobuf/NewInstanceSchemaFull;
05-13 12:44:56.730 11856-11856/? E/art: ClassLinker::FindClass not found:Lcom/google/protobuf/ExtensionSchemaFull;
05-13 12:44:56.731 11856-11856/? E/art: ClassLinker::FindClass not found:Lcom/google/protobuf/MapFieldSchemaFull;
05-13 12:44:56.735 11856-11856/? E/art: ClassLinker::FindClass not found:Lorg/robolectric/Robolectric;
05-13 12:44:57.216 11856-11856/? E/art: ClassLinker::FindClass not found:Lsun/misc/SharedSecrets;
05-13 12:44:57.275 11856-11856/? E/art: ClassLinker::FindClass not found:Landroid/app/NotificationChannel;
05-13 12:44:57.276 11856-11856/? E/art: ClassLinker::FindClass not found:Landroid/app/NotificationChannelGroup;
05-13 12:44:57.279 11856-11856/? E/art: ClassLinker::FindClass not found:Landroid/app/NotificationChannel;
05-13 12:44:57.280 11856-11856/? E/art: ClassLinker::FindClass not found:Landroid/app/NotificationChannelGroup;
05-13 12:44:57.283 11856-11856/? E/art: ClassLinker::FindClass not found:Landroid/app/NotificationChannel;
05-13 12:44:57.351 11856-11856/? E/art: ClassLinker::FindClass not found:Landroid/app/NotificationChannel;
05-13 12:44:57.363 11856-11856/? E/art: ClassLinker::FindClass not found:Landroid/app/NotificationChannel;
05-13 12:44:57.385 11856-11856/? E/art: ClassLinker::FindClass not found:Landroid/app/NotificationChannel;
05-13 12:44:57.627 11856-11856/? E/ErrorNotificationActivity: [main] Drive has stopped unexpectedly. Report this issue to help us determine what went wrong.
05-13 12:44:57.634 11856-11856/? E/art: ClassLinker::FindClass not found:Landroid/widget/ViewStub;
05-13 12:44:57.635 11856-11856/? E/art: ClassLinker::FindClass not found:Landroid/webkit/ViewStub;
05-13 12:44:57.635 11856-11856/? E/art: ClassLinker::FindClass not found:Landroid/app/ViewStub;
05-13 12:44:57.644 11856-11856/? E/art: ClassLinker::FindClass not found:Landroid/widget/View;
05-13 12:44:57.644 11856-11856/? E/art: ClassLinker::FindClass not found:Landroid/webkit/View;
05-13 12:44:57.651 11856-11856/? E/art: ClassLinker::FindClass not found:Landroid/app/View;
05-13 12:44:57.801 11728-12056/? E/amqy: Phenotype API error. Event # byvj@31bad748, EventCode: 32 [CONTEXT service_id=51 ]
    amqc: 29503
        at amsd.b(:com.google.android.gms@201516007@20.15.16 (020304-309763488):7)
        at amqy.a(:com.google.android.gms@201516007@20.15.16 (020304-309763488):84)
        at amqy.a(:com.google.android.gms@201516007@20.15.16 (020304-309763488):71)
        at zqr.run(:com.google.android.gms@201516007@20.15.16 (020304-309763488):8)
        at bkgs.run(:com.google.android.gms@201516007@20.15.16 (020304-309763488):2)
        at sgc.b(:com.google.android.gms@201516007@20.15.16 (020304-309763488):12)
        at sgc.run(:com.google.android.gms@201516007@20.15.16 (020304-309763488):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at slw.run(:com.google.android.gms@201516007@20.15.16 (020304-309763488):0)
        at java.lang.Thread.run(Thread.java:818)
05-13 12:44:57.802 11728-12056/? E/AsyncOperation: serviceID=51, operation=SetAppSpecificPropertiesOperationCall
    OperationException[Status{statusCode=unknown status code: 29503, resolution=null}]
        at amqy.a(:com.google.android.gms@201516007@20.15.16 (020304-309763488):86)
        at amqy.a(:com.google.android.gms@201516007@20.15.16 (020304-309763488):71)
        at zqr.run(:com.google.android.gms@201516007@20.15.16 (020304-309763488):8)
        at bkgs.run(:com.google.android.gms@201516007@20.15.16 (020304-309763488):2)
        at sgc.b(:com.google.android.gms@201516007@20.15.16 (020304-309763488):12)
        at sgc.run(:com.google.android.gms@201516007@20.15.16 (020304-309763488):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at slw.run(:com.google.android.gms@201516007@20.15.16 (020304-309763488):0)
        at java.lang.Thread.run(Thread.java:818)`

when try to save qr code to email message I can see a toast informing: Could not attach a file, stacktrace:
`05-13 12:46:41.461 9046-9046/? E/Gmail: LiveListLoader:Attempting to shut down a LiveList with id snoozed-alarm-itemlist when it hasn't been started yet
    java.lang.Throwable
        at epi.d(PG:1)
        at epj.b(PG:2)
        at eub.f(PG:4)
        at fbb.g(PG:1)
        at fbb.a(PG:230)
        at fpm.a(PG:50)
        at ewo.onLoadFinished(PG:38)
        at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:483)
        at android.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:451)
        at android.content.Loader.deliverResult(Loader.java:144)
        at dsz.a(PG:5)
        at dsz.deliverResult(PG)
        at dsw.onPostExecute(PG:4)
        at android.os.AsyncTask.finish(AsyncTask.java:636)
        at android.os.AsyncTask.access$500(AsyncTask.java:177)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5298)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)`

#### Steps to reproduce the problem
1. Try to save qr code to Google Drive/attach qr code to email message on Android 5.1 Huawei Y560-L01 device.

#### Expected behavior
User should be able to share qr code in both ways.

#### Other information 
I am aware that the issue won't be probably fixed as it looks like it's specific to a device - reporting in case any user would encounter a similar problem.

**Comment by mmarciniak90** [comment]
@getodk-bot label "Specific to Android version"

**Comment by seadowg** [comment]
Closing this due to #5296
