### ISSUE TITLE
NPE in MapboxMapFragment.java line 904

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3879]
#### Software and hardware versions 
Collect v1.27.0 and older versions

#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/71cf05a1083f68497a29ed76e47b8a5c?time=last-seven-days&sessionId=5ECF7867028400014DC482A245EAE022_DNE_0_v2

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void org.odk.collect.android.geo.MapFragment$FeatureListener.onFeature(int)' on a null object reference
       at org.odk.collect.android.geo.MapboxMapFragment$PolyFeature$LineClickListener.onAnnotationClick(MapboxMapFragment.java:904)
       at org.odk.collect.android.geo.MapboxMapFragment$PolyFeature$LineClickListener.onAnnotationClick(MapboxMapFragment.java:901)
       at com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager$MapClickResolver.onMapClick(AnnotationManager.java:380)
       at com.mapbox.mapboxsdk.maps.MapGestureDetector.notifyOnMapClickListeners(MapGestureDetector.java:998)
       at com.mapbox.mapboxsdk.maps.MapGestureDetector$StandardGestureListener.onSingleTapConfirmed(MapGestureDetector.java:360)
       at com.mapbox.android.gestures.StandardGestureDetector$1.onSingleTapConfirmed(StandardGestureDetector.java:83)
       at android.view.GestureDetector.onTouchEvent(GestureDetector.java:758)
       at androidx.core.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2.onTouchEvent(GestureDetectorCompat.java:480)
       at androidx.core.view.GestureDetectorCompat.onTouchEvent(GestureDetectorCompat.java:543)
       at com.mapbox.android.gestures.StandardGestureDetector.analyzeEvent(StandardGestureDetector.java:147)
```

**Comment by grzesiek2010** [comment]
There are similar reports probably caused by the same bug:
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/693784ddaf1619d825d68c6d381df76b?time=last-seven-days&sessionId=5ECF4DDA012000017766274B1C49B759_DNE_0_v2

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void org.odk.collect.android.geo.MapFragment$FeatureListener.onFeature(int)' on a null object reference
       at org.odk.collect.android.geo.MapboxMapFragment$PolyFeature$SymbolClickListener.onAnnotationClick(MapboxMapFragment.java:894)
       at org.odk.collect.android.geo.MapboxMapFragment$PolyFeature$SymbolClickListener.onAnnotationClick(MapboxMapFragment.java:890)
       at com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager$MapClickResolver.onMapClick(AnnotationManager.java:380)
       at com.mapbox.mapboxsdk.maps.MapGestureDetector.notifyOnMapClickListeners(MapGestureDetector.java:998)
       at com.mapbox.mapboxsdk.maps.MapGestureDetector$StandardGestureListener.onSingleTapConfirmed(MapGestureDetector.java:360)
       at com.mapbox.android.gestures.StandardGestureDetector$1.onSingleTapConfirmed(StandardGestureDetector.java:83)
       at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
```

**Comment by grzesiek2010** [comment]
I was able to reproduce the issue so here are the steps:

1. Select Mapbox in General Settings -> Maps
2. Open any form with GeoTrace/GeoShape widgets
3. Add some points on the map.
4. Try to click on any point.
