### ISSUE TITLE
IllegalArgumentException in ResetDialogPreference.java:141

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3890]
#### Software and hardware versions 
Collect v1.27.0 and older version

#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/431bd8f8955611372dbd6bf8412fd57d?time=last-seven-days&sessionId=5ED1C11F031E0001490DC1C6E76B1BA9_DNE_1_v2

```
Fatal Exception: java.lang.IllegalArgumentException: View=DecorView@5a869cd[Por favor, espere un momento] not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:497)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:404)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
       at android.app.Dialog.dismissDialog(Dialog.java:367)
       at android.app.Dialog.dismiss(Dialog.java:346)
       at org.odk.collect.android.preferences.ResetDialogPreference.hideProgressDialog(ResetDialogPreference.java:141)
       at org.odk.collect.android.preferences.ResetDialogPreference.access$100(ResetDialogPreference.java:45)
       at org.odk.collect.android.preferences.ResetDialogPreference$1.onPostExecute(ResetDialogPreference.java:126)
       at org.odk.collect.android.preferences.ResetDialogPreference$1.onPostExecute(ResetDialogPreference.java:113)
       at android.os.AsyncTask.finish(AsyncTask.java:660)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
```

**Comment by grzesiek2010** [comment]
This is an old report so let's close for now and reopen later if needed.
