### ISSUE TITLE
NPE in SortDialogAdapter.java line 77

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3893]
#### Software and hardware versions 
Collect v1.27.0 and older versions

#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/e2f5d6f6136e49bcc97d10d3670262fa?time=last-ninety-days&sessionId=5ECFAB2F00DD000117D60E3CE6BD44B2_DNE_0_v2

```
Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
       at org.odk.collect.android.adapters.SortDialogAdapter.getItemCount(SortDialogAdapter.java:77)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4044)
       at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3534)
       at android.view.View.measure(View.java:23869)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
       at android.view.View.measure(View.java:23869)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6862)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:23869)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6862)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
       at android.view.View.measure(View.java:23869)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6862)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:23869)
```

#### Steps to reproduce the problem

1. Open the app and the list of forms.
2. Minimize the app and revert storage permission.
3. Get back to the app.
4. Rotate your device on when you see the permission dialog and click `allow`.
5. Try to sort forms.

**Comment by grzesiek2010** [comment]
I investigated the issue and it''s a broader problem related to https://github.com/Karumi/Dexter similar to https://github.com/getodk/collect/issues/2571 since it's something difficult to reproduce in real life and we will be able to get rid of storage permission once we switch to scoped storage (in ~4 months) I would mark it as won't fix.

**Comment by grzesiek2010** [comment]
@seadowg @lognaturel If you have something against the new label I created `won't fix` or maybe you don't agree with the fact it's used here, let me know.

**Comment by kkrawczyk123** [comment]
@grzesiek2010 I have tried to reproduce the issue with turning on/off storage permissions manually on my Androids 7.1 and 9.0 without success. The issue does not occur anymore as the permission dialog does not display and there is no way to enable it using Collect. I think that we should close this one.
