### ISSUE TITLE
NPE in isQuestionRecalculated (FormEntryActivity.java:2884)

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3902]
#### Software and hardware versions 
Collect v1.27.1 and older versions

#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/1ea0f53adf72eb6a2ee9793ce03db64b?time=last-seven-days&sessionId=5ED7E64A006200011FF9EF3EF4ED2576_DNE_0_v2

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at org.odk.collect.android.activities.FormEntryActivity.isQuestionRecalculated(FormEntryActivity.java:2884)
       at org.odk.collect.android.activities.FormEntryActivity.saveAnswersForCurrentScreen(FormEntryActivity.java:1101)
       at org.odk.collect.android.activities.FormEntryActivity.updateFieldListQuestions(FormEntryActivity.java:2829)
       at org.odk.collect.android.activities.FormEntryActivity.widgetValueChanged(FormEntryActivity.java:2798)
       at org.odk.collect.android.formentry.ODKView.widgetValueChanged(ODKView.java:663)
       at org.odk.collect.android.widgets.QuestionWidget.widgetValueChanged(QuestionWidget.java:539)
       at org.odk.collect.android.widgets.AbstractSelectOneWidget.onClick(AbstractSelectOneWidget.java:141)
       at org.odk.collect.android.adapters.SelectOneListAdapter.onClick(SelectOneListAdapter.java:69)
       at android.view.View.performClick(View.java:6294)
       at android.widget.CompoundButton.performClick(CompoundButton.java:134)
       at android.view.View$PerformClick.run(View.java:24770)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

#### Steps to reproduce the problem
I'm on it

**Comment by grzesiek2010** [comment]
Ok I was able to reproduce the issue, steps:
1. Open the form: 
[field-list.xlsx](https://github.com/getodk/collect/files/4731534/field-list.xlsx)
2. Pass any value to the first question.
3. Remove the answer
