### ISSUE TITLE
NPE in FormSaveViewModel

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4036]
From https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/8ca03d40871475f87917f721719cd4aa?time=last-seven-days&sessionId=5F429670034E0001384141414334DC52_DNE_0_v2

#### Software and hardware versions 
Collect v1.28.0-beta.1

#### Problem description

Stacktrace:

```java
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'org.odk.collect.android.formentry.audit.AuditEventLogger org.odk.collect.android.javarosawrapper.FormController.getAuditEventLogger()' on a null object reference
       at org.odk.collect.android.formentry.saving.FormSaveViewModel.getAuditEventLogger(FormSaveViewModel.java:253)
       at org.odk.collect.android.formentry.QuitFormDialogFragment.lambda$onCreateDialog$0(QuitFormDialogFragment.java:93)
       at org.odk.collect.android.formentry.-$$Lambda$QuitFormDialogFragment$kkJKBUgJhZUYv_cQAWuh7PWDoCM.onItemClick(-.java:8)
       at android.widget.AdapterView.performItemClick(AdapterView.java:321)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1217)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3203)
       at android.widget.AbsListView$3.run(AbsListView.java:4151)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

#### Steps to reproduce the problem

My guess it that somehow the form is being quit before the `formController` has been set on the `FormSaveViewModel`.

#### Expected behavior

A `null` `formController` shouldn't cause a crash (as much as it wants to).

#### Other information 

I think a good fix for this kind of thing is to move the logging logic to the view model so that it can just no-op on a `null` `formController`. A good idea for this specific one would be to create a `quit` or `ignore` action on the `FormSaveViewModel` that could take care of logging and removing temp instances etc.

**Comment by lognaturel** [comment]
Every single time this has happened it's after a load from savepoint. There's also generally a `Ended up with a bad language. null` in the logs. I did a little experimentation with savepoints and nothing I could think of triggered the issue, though.
