### ISSUE TITLE
Collect is crashing on filling indefinite repeat form

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#4092]
#### Software and hardware versions 
Collect v1.28.x, Android v all device used...

#### Problem description
I have noticed weird behavior when filling [indefinite.xml.txt](https://github.com/getodk/collect/files/5223962/indefinite.xml.txt) form. I was actually able to fill it just once but app froze on saving/finalizing form. I was not able to get back to form as app crashed. 
![ezgif com-video-to-gif (29)](https://user-images.githubusercontent.com/33342488/93194167-1168ac80-f748-11ea-8c42-49d8d2e12826.gif)

#### Steps to reproduce the problem
1. Open attached form
2. Try to fill
3. Try to open again

#### Expected behavior
- Collect should not crash
- User should be able to fill fotm

#### Other information 
stacktrace:
`2020-09-15 09:55:35.112 11587-11944/? E/whs: Job(ItemMessageAttachmentsCacheEvictorJob#0.26) Enqueued job 'ItemMessageAttachmentsCacheEvictorJob' failed
    java.lang.IllegalArgumentException: Attachment cache cannot be null.
        at oqn.a(Unknown Source)
        at osb.a(Unknown Source)
        at xgs.a(SourceFile:2)
        at whe.b(SourceFile:2)
        at whf.a(Unknown Source)
        at xgs.a(SourceFile:2)
        at xfz.run(SourceFile:1)
        at vyg.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)`

- i was not able to reproduce the same behavior on 1.27

@getodk-bot label "regression"

**Comment by seadowg** [comment]
For me the easiest way to reproduce is to hit the arrow (↘️) to get to the hierarchy view.

**Comment by grzesiek2010** [comment]
I added the fix from https://forum.getodk.org/t/infinite-loop-and-dynamically-delete-already-selected-options-from-list/25902/7?u=ln and the form seems to work. @kkrawczyk123 please confirm it was just a bug in the form, here is a fixed version: 
[indefinite_fixed.xml.txt](https://github.com/getodk/collect/files/5225822/indefinite_fixed.xml.txt)

**Comment by kkrawczyk123** [comment]
@grzesiek2010 I've just checked - form that you attached works for me.
