### ISSUE TITLE
Prevent crashes when there are errors talking to SQLite database

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4108]
We run into a few different crashes when trying to read or write to/from the database on device:

https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5974a495deaaafc213c6857985557684?time=last-ninety-days&versions=v2021.2.2%20(4256)&sessionEventKey=610BA6A002AE00014A23B626FE362FE0_1571311994101282197

https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/b88555ad2701253e0177019be276acff?time=last-ninety-days&versions=v2021.2.2%20(4256)&sessionEventKey=610BA5FE01140001472DB626FE362FE0_1571311629015343902

This a mixture of the database being full or not accessible. There isn't much we can do to recover from these but we could give the user some instructions:

* `SQLiteFullException` - "Device storage is full. Try deleting some things and then try again"
* `SQLiteReadOnlyDatabaseException` - "Collect's database is corrupt. Try submitting forms and then reinstalling."

**Comment by lognaturel** [comment]
[`SQLiteCantOpenDatabaseException`](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/07cccfa2bbf3b4e0e4fed4f0a9fcbd76?time=last-seven-days&versions=v2021.2-beta.1%20(4192);v2021.2-beta.2%20(4197)&sessionEventKey=60D76B4C025F00012FFEA13DD6BCFDF0_1556615409982040868)

**Comment by seadowg** [comment]
A significant amount of these crashes are now captured in:

* `DatabaseConnection#getReadableDatabase`: https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/07cccfa2bbf3b4e0e4fed4f0a9fcbd76?time=last-seven-days&sessionEventKey=616E95CF00E3000109388B15C00852C2_1599161892004634493

* `DatabaseConnection#getWriteableDatabase`: https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/07cccfa2bbf3b4e0e4fed4f0a9fcbd76?time=last-seven-days&sessionEventKey=616E95CF00E3000109388B15C00852C2_1599161892004634493

It could be that we might stop seeing these errors so much in v2021.3 due to https://github.com/getodk/collect/pull/4777 - if this is due to directories being deleted that will now be fixed. We should wait to see what happens with that.

**Comment by grzesiek2010** [comment]
This one seems to be more common now https://console.firebase.google.com/u/2/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/3f88593bf6c5048b6bafb939dea1a6dd?time=last-seven-days&versions=v2021.3.2%20(4321)&sessionEventKey=619F7911019000010B741A86B159F455_1612920484697648443

which happens when we try to move cursor position.

**Comment by seadowg** [comment]
Yup that's the most common now I think. Looking at the ones that have hit multiple people we have:

#### 1. `android.database.sqlite.SQLiteDiskIOException` from `DatabaseConnection.getReadableDatabase`

Crash report: https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/07cccfa2bbf3b4e0e4fed4f0a9fcbd76?time=last-seven-days&versions=v2021.3.2%20(4321)&sessionEventKey=61A60DAB01880001768BF608B390ADAF_1614772110752545119

Stacktrace:

```java
Fatal Exception: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 776)
       at android.database.sqlite.SQLiteConnection.nativeExecuteForLong(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:598)
       at android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:652)
       at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:107)
       at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:879)
       at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:867)
       at android.database.sqlite.SQLiteDatabase.getVersion(SQLiteDatabase.java:864)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:241)
       at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
       at org.odk.collect.android.database.DatabaseConnection.getReadableDatabase(DatabaseConnection.java:27)
       at org.odk.collect.android.database.instances.DatabaseInstancesRepository.query(DatabaseInstancesRepository.java:217)
       at org.odk.collect.android.database.instances.DatabaseInstancesRepository.getCursorForAllByStatus(DatabaseInstancesRepository.java:213)
       at org.odk.collect.android.database.instances.DatabaseInstancesRepository.getCountByStatus(DatabaseInstancesRepository.java:108)
       at org.odk.collect.android.formmanagement.InstancesAppState.update(InstancesAppState.java:36)
       at org.odk.collect.android.activities.viewmodels.MainMenuViewModel.lambda$refreshInstances$0(MainMenuViewModel.java:121)
       at org.odk.collect.android.activities.viewmodels.MainMenuViewModel.$r8$lambda$YcoOrSsMfVfE3us74hHtJ7C_gUA(MainMenuViewModel.java)
       at org.odk.collect.android.activities.viewmodels.MainMenuViewModel$$InternalSyntheticLambda$0$eda4732b51dcabe3c3f222886d16e879715dfe375e22c95a52c50d613ad65981$0.get(MainMenuViewModel.java)
       at org.odk.collect.async.CoroutineScheduler$immediate$1$result$1.invokeSuspend(CoroutineScheduler.java:16)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)
```

Reason:  Looking at the [docs for the 776 error code](https://sqlite.org/rescode.html#readonly_rollback), it sounds like this could be caused by the application crashing during a DB transaction and then recovering. This would a crash as the db needs to rollback but can't because the connection is readonly.

Solution: We could potentially catch an `SQLiteDiskIOException` when opening a readonly DB and fallback to opening a writeable connection instead (which should allow the DB to sort itself out).

#### 2. `android.database.sqlite.SQLiteDiskIOException` from `DatabaseInstancesRepository.getInstancesFromCursor`

Crash report: https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/3f88593bf6c5048b6bafb939dea1a6dd?time=last-seven-days&versions=v2021.3.2%20(4321)&sessionEventKey=61A77C9A037400013D051A86B159F455_1615178320852968981

Stacktrace:

```java
Fatal Exception: android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802)
#################################################################
Error Code : 1802 (SQLITE_IOERR_FSTAT)
Caused By : Failed to get database file information with system call stat(). Please confirm whether database file has been removed.
	(disk I/O error (code 1802))
#################################################################
       at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:918)
       at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
       at org.odk.collect.android.database.instances.DatabaseInstancesRepository.getInstancesFromCursor(DatabaseInstancesRepository.java:272)
       at org.odk.collect.android.database.instances.DatabaseInstancesRepository.getOneByPath(DatabaseInstancesRepository.java:76)
       at org.odk.collect.android.instancemanagement.InstanceDiskSynchronizer.doInBackground(InstanceDiskSynchronizer.java:111)
       at org.odk.collect.android.activities.viewmodels.MainMenuViewModel.lambda$refreshInstances$0(MainMenuViewModel.java:120)
       at org.odk.collect.android.activities.viewmodels.MainMenuViewModel.$r8$lambda$YcoOrSsMfVfE3us74hHtJ7C_gUA(MainMenuViewModel.java)
       at org.odk.collect.android.activities.viewmodels.MainMenuViewModel$$InternalSyntheticLambda$0$eda4732b51dcabe3c3f222886d16e879715dfe375e22c95a52c50d613ad65981$0.get(MainMenuViewModel.java)
       at org.odk.collect.async.CoroutineScheduler$immediate$1$result$1.invokeSuspend(CoroutineScheduler.java:16)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)
```

Reason: it sounds like in this case the DB has been deleted or the filesystem isn't available but I'm not exactly sure how we'd get into that situation. I tried to recreate this by deleting the DB (or its directory) while debugging the app but couldn't make this happen. I'm guessing this could be happening when resuming the app if storage isn't available in some way?

Solution: We could add our storage availability check to `MainMenuActivity#onResume` to catch cases where storage has become unavailable while the app is still running. This wouldn't solve the issue (there would be very little we could do in that case anyway) but it would give us a clearer exception.

#### 3. `SQLiteFullException` from `DatabaseFormsRepository.deleteForms` and `DatabaseInstancesRepository.update`

Crash reports:
* https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/a467b1eac326971ceff88bf4d379e43c?time=last-seven-days&versions=v2021.3.2%20(4321)&sessionEventKey=61A5319402DB00013C8BB74D00B5AC38_1614530562031305422
* https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/b88555ad2701253e0177019be276acff?time=last-seven-days&versions=v2021.3.2%20(4321)&sessionEventKey=61A49701004100010E84893DA30F0682_1614360167135082483

Reason: This could be that we're exceeding the max DB size somehow but I'm not sure how credible that is (SO on that [here](https://stackoverflow.com/questions/2777954/is-there-a-limit-to-the-size-of-a-sqlite-database)). More likely, the device disk is just full.

Solution: Not much we can do to fix this but we could potentially check and warn the user (using [StateFS](https://developer.android.com/reference/android/os/StatFs.html)) about a full disk.

I'm thinking we could implement the proposed solutions for 1 and 2 and maybe just leave 3 for now?

**Comment by seadowg** [comment]
@lognaturel @grzesiek2010 thoughts on the above comment?
