### ISSUE TITLE
NPE in GoogleMapFragment

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4116]
#### Software and hardware versions 
Collect v1.28.0

#### Problem description

From Crashlytics: https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/ea904558a5c9cad08261a77ab7f7eded?time=last-seven-days&sessionId=5F6C4C2601B8000157C1F75A2BB0A2F9_DNE_0_v2

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'double org.odk.collect.android.geo.MapPoint.lat' on a null object reference
       at org.odk.collect.android.geo.GoogleMapFragment.toLatLng(GoogleMapFragment.java:468)
       at org.odk.collect.android.geo.GoogleMapFragment.createMarker(GoogleMapFragment.java:599)
       at org.odk.collect.android.geo.GoogleMapFragment.access$000(GoogleMapFragment.java:72)
       at org.odk.collect.android.geo.GoogleMapFragment$MarkerFeature.<init>(GoogleMapFragment.java:666)
       at org.odk.collect.android.geo.GoogleMapFragment.addMarker(GoogleMapFragment.java:247)
       at org.odk.collect.android.activities.GeoPointMapActivity.placeMarker(GeoPointMapActivity.java:381)
       at org.odk.collect.android.activities.GeoPointMapActivity.lambda$initMap$1(GeoPointMapActivity.java:192)
       at org.odk.collect.android.activities.-$$Lambda$GeoPointMapActivity$K-P88m9xDxzogm7HCcOxCkqGFpM.onClick(-.java:2)
       at android.view.View.performClick(View.java:6613)
       at android.view.View.performClickInternal(View.java:6586)
       at android.view.View.access$3100(View.java:780)
       at android.view.View$PerformClick.run(View.java:26102)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6724)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
```

#### Other information

**Comment by grzesiek2010** [comment]
Just to clarify it's not new It has existed for a longer time.
