### ISSUE TITLE
Fetching a form list from a "legacy" server when a form has no id causes a crash

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4126]
Originally from Firebase:

https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/7409d125f244c8b834ac812b15bf055e?time=last-seven-days&versions=v1.28.1%20(3923)&sessionEventKey=5F7169A000AB000145A2EF6EB0435A52_1455839903049595768

#### Software and hardware versions 
Collect v1.28.0+

#### Problem description

It looks like trying to fetch the list of forms (clicking Get Blank Form while connected to the internet) causes a crash if one of the forms in the list has a `null` (missing) id. This doesn't quite make sense though as the `OpenRosaFormListApi` should never return a `FormListItem` with a `null` id (line 234).

Update: My mistake. It is possible to return a `FormListItem` for servers that are using an unrecognized (or no) Open Rosa version as we use `OpenRosaFormListApi#parseLegacyFormList` which does not have a null check for the id. It looks like we're seeing the "unrecognized version" log in the crash as well.

#### Steps to reproduce the problem

I didn't have access to a server that would allow `null` ids but I experimented with a test for `DatabaseFormRepository` that threw the same error to verify the theory:

```java
@Test
public void getByJrFormIdNotDeleted_whenIdIsNull_returnsEmptyList() {
     FormsRepository formsRepository = buildSubject();

     List<Form> forms = formsRepository.getByJrFormIdNotDeleted(null);
     assertThat(forms.isEmpty(), is(true));
}
```

This throws the same `IllegalArgumentException` we're seeing in Firebase.

#### Expected behavior

No sure yet!

#### Other information 

Stacktrace:

```java
Caused by java.lang.IllegalArgumentException: the bind value at index 1 is null
       at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:176)
       at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:212)
       at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1711)
       at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:399)
       at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:294)
       at org.odk.collect.android.provider.FormsProvider.query(FormsProvider.java:141)
       at android.content.ContentProvider.query(ContentProvider.java:1028)
       at android.content.ContentProvider$Transport.query(ContentProvider.java:243)
       at android.content.ContentResolver.query(ContentResolver.java:536)
       at android.content.ContentResolver.query(ContentResolver.java:478)
       at org.odk.collect.android.dao.FormsDao.getFormsCursor(FormsDao.java:50)
       at org.odk.collect.android.dao.FormsDao.getFormsCursor(FormsDao.java:46)
       at org.odk.collect.android.database.DatabaseFormsRepository.queryForForms(DatabaseFormsRepository.java:152)
       at org.odk.collect.android.database.DatabaseFormsRepository.getByJrFormIdNotDeleted(DatabaseFormsRepository.java:35)
       at org.odk.collect.android.formmanagement.ServerFormsDetailsFetcher.isThisFormAlreadyDownloaded(ServerFormsDetailsFetcher.java:98)
       at org.odk.collect.android.formmanagement.ServerFormsDetailsFetcher.fetchFormDetails(ServerFormsDetailsFetcher.java:64)
       at org.odk.collect.android.tasks.DownloadFormListTask.doInBackground(DownloadFormListTask.java:63)
       at org.odk.collect.android.tasks.DownloadFormListTask.doInBackground(DownloadFormListTask.java:39)
       at android.os.AsyncTask$2.call(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```

**Comment by seadowg** [comment]
Marking this as won't fix for the moment as there needs to be a problem at the form and the server level for this to happen. If people start running into it, we can look at it again.

**Comment by ItloMd9** [comment]
@seadowg ,

I have the same issue with my custom server.
So the expected behaviour is that it returns to the overview screen (with buttons to select either filling forms, getting blank forms or deleted forms etc)

With 2nd attempt to get blank forms, a popup will display with 2 options of either to wait or close app.(screen shot to be submitted later)

I assume now that there is a response mismatch between Collect and my custom server (with no openrosa version
With this assumption, I would consider to update the response of my custom server
But I could not find the correct, specified repsonse format for this.

Do we have such specification defined anywhere @seadowg ? That would be very much appreciated

**Comment by lognaturel** [comment]
Sorry you’re having this issue, @ItloMd9. Could you please tell us more about how you came to implement the API you did? As you say, it’s not documented and not intended for use. 

The thread starting at https://github.com/getodk/collect/issues/4176#issuecomment-723964437 should help. I’m guessing you’re also not specifying formId in your URLs.

**Comment by ItloMd9** [comment]
Thanks @lognaturel,

I will try to append FormID to the url from my custom server and see whether it works.

**Comment by ItloMd9** [comment]
@lognaturel ,

I just had a quick code review and see this regarding to the format you suggested:

![Screenshot_2020-11-12 getodk collect-1.png](https://user-images.githubusercontent.com/21131109/98843076-0c408900-247d-11eb-88ac-f51482cda035.png)

So, with "formID" considered as the same type with "form", I dont think that appending "formId" into "url" attribute of "form" would help ??!!!!???

Could you please take a look @lognaturel @seadowg ? 
Thanks

**Comment by lognaturel** [comment]
I’ll look at it again hopefully later this week. In the mean time, the ideal would be to implement the supported, documented OpenRosa API. Is that something you could do? This will be the long term solution.

**Comment by lognaturel** [comment]
I believe that @ItloMd9 has been able to implement the OpenRosa API so this can be closed.
