### ISSUE TITLE
Value of URL widget should be lowercased before passing to intent constructor

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#4319]
#### Problem description

https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/180c16234b393c9cafa478d82823aa53?time=last-seven-days&versions=v1.29.0-beta.2%20(4026)&sessionEventKey=5FD8F75B022F00016340020A0EBAE189_1484987790261810522

```
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=Https://google.com/... (has extras) }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2067)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
       at android.app.Activity.startActivityForResult(Activity.java:5320)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
       at android.app.Activity.startActivityForResult(Activity.java:5278)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
       at android.app.Activity.startActivity(Activity.java:5664)
       at androidx.core.content.ContextCompat.startActivity(ContextCompat.java:251)
       at androidx.browser.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:331)
       at org.odk.collect.android.utilities.CustomTabHelper.openUri(CustomTabHelper.java:99)
       at org.odk.collect.android.widgets.UrlWidget.onButtonClick(UrlWidget.java:87)
       at org.odk.collect.android.widgets.UrlWidget.lambda$onCreateAnswerView$0(UrlWidget.java:48)
       at org.odk.collect.android.widgets.UrlWidget.lambda$onCreateAnswerView$0$UrlWidget(UrlWidget.java)
       at org.odk.collect.android.widgets.-$$Lambda$UrlWidget$BgNotkrxtDDsnKOwingp922zQms.onClick(-.java:2)
       at android.view.View.performClick(View.java:7448)
```

**Comment by lognaturel** [comment]
You probably saw the note in Firebase -- that was me. We've never seen it before so it doesn't feel critical. I think the action to take is to lowercase the value of the widget but I wanted to take some time to think through what we really want this widget to do. I was experimenting with dynamic values for it which is quite powerful. We can also launch other apps. I think it would be great to document the extent of what is possible here.

**Comment by lognaturel** [comment]
https://developer.android.com/reference/android/content/IntentFilter describes that scheme matching is case-sensitive.

**Comment by grzesiek2010** [comment]
>  We've never seen it before so it doesn't feel critical

I agree that it's not critical but I thing I have seen something like that before...

> I think the action to take is to lowercase the value of the widget

Hmm i tested it and worked fine but now I created another device and capital letters make difference strange you are right.

**Comment by lognaturel** [comment]
Yeah, it's super unexpected. Probably just a bug that can't be fixed because implementations rely on it.

**Comment by grzesiek2010** [comment]
In this case look like we need [normalizeScheme()](https://developer.android.com/reference/android/net/Uri#normalizeScheme()) 
I updated the pr.
