### ISSUE TITLE
App crashes when user clicks on stop and pause at the same time while recording `voice-only` quality audio

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4368]
#### Software and hardware versions 
Collect v1.29.0 (older versions were not verified), Android v8.1

#### Problem description
Collect crashes when user tries to click on the pause and stop button at the same time while recording `voice-only` quality audio

#### Steps to reproduce the problem
1. Start recording using an internal recorder with `voice-only` quality [AllQ4222AudioQuality.xml.txt](https://github.com/getodk/collect/files/5893626/AllQ4222AudioQuality.xml.txt)
2. Tap on stop and pause at the same

#### Expected behavior
* Collect should not crash
* Using pause and stop buttons at once should be blocked

#### Other information 
Similar issue #4287 
Discovered during testing #4365 

@getodk-bot label "Specific to Android version"

**Comment by seadowg** [comment]
@mmarciniak90 just to double-check: you didn't see this with the other quality levels?

**Comment by mmarciniak90** [comment]
> you didn't see this with the other quality levels?

Crash doesn't occur for normal and low quality and when quality is not defined.
I only notice this crash when using `voice-only` quality.

**Comment by kkrawczyk123** [comment]
@seadowg @mmarciniak90 Unfortunately, it looks like this issue is not specific to Android 8.1 version only. I've just tried the Play Store Collect version with all 3 audio types in the same form on my devices with Android 7.1 and 9.0. My results:
- I was able to reproduce the crash on all: voice-only, normal and low on Android 7.1
- I was also able to reproduce the crash on all: voice-only, normal and low on Android 9.0 but here it was extremely hard to induce it on normal type - it has taken the biggest number of tries.

**Comment by seadowg** [comment]
@kkrawczyk123 @mmarciniak90 are you seeing a crash in the logs you could post?

**Comment by kkrawczyk123** [comment]
@seadowg I have:

`2021-01-29 14:12:19.452 9205-9205/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.odk.collect.android, PID: 9205
    java.lang.IllegalArgumentException
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:71)
        at org.odk.collect.android.widgets.AudioWidget.getDurationOfFile(SourceFile:255)
        at org.odk.collect.android.widgets.AudioWidget.updatePlayerMedia(SourceFile:221)
        at org.odk.collect.android.widgets.AudioWidget.setData(SourceFile:173)
        at org.odk.collect.android.widgets.AudioWidget.lambda$new$2(SourceFile:101)
        at org.odk.collect.android.widgets.AudioWidget.lambda$new$2$AudioWidget(SourceFile)
        at org.odk.collect.android.widgets.-$$Lambda$AudioWidget$uPVjCz_-O_39_HWjN9ITYQcq_9A.accept(SourceFile)
        at org.odk.collect.android.widgets.utilities.InternalRecordingRequester.lambda$null$2(SourceFile:89)
        at org.odk.collect.android.widgets.utilities.InternalRecordingRequester.lambda$null$2$InternalRecordingRequester(SourceFile)
        at org.odk.collect.android.widgets.utilities.-$$Lambda$InternalRecordingRequester$f3BuN0NNUjh-Cut7bpxCtXjqa5A.onChanged(SourceFile)
        at androidx.lifecycle.LiveData.considerNotify(SourceFile:131)
        at androidx.lifecycle.LiveData.dispatchingValue(SourceFile:149)
        at androidx.lifecycle.LiveData.setValue(SourceFile:307)
        at androidx.lifecycle.MutableLiveData.setValue(SourceFile:50)
        at org.odk.collect.android.formentry.saving.FormSaveViewModel.lambda$createAnswerFile$1(SourceFile:358)
        at org.odk.collect.android.formentry.saving.FormSaveViewModel.lambda$createAnswerFile$1$FormSaveViewModel(SourceFile)
        at org.odk.collect.android.formentry.saving.-$$Lambda$FormSaveViewModel$ZXoLeFuwlAoyYphZqJO0HWAhhQ4.accept(SourceFile)
        at org.odk.collect.async.CoroutineScheduler$immediate$1.invokeSuspend(SourceFile:17)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
        at kotlinx.coroutines.DispatchedTask.run(SourceFile:56)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6165)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)`

**Comment by seadowg** [comment]
@kkrawczyk123 thanks! I'm going to investigate.

**Comment by seadowg** [comment]
@mmarciniak90 @kkrawczyk123 I've put a draft PR up (#4372) that hopefully fixes the problems. I was able to reproduce the crashes before but can't now. I've marked the PR as "needs testing" as I think it's better to see if you're able to break it before we go through a review.
