### ISSUE TITLE
App crashes when trying to download a form without a hash

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4444]
#### Software and hardware versions 
Collect v1.30.0-beta.1

#### Problem description

The app tries to query the database to check if a form exists before downloading it or not. It uses the hash for this lookup so if the server didn't return a hash in the form list there will be a crash at the query level.

#### Steps to reproduce the problem

1. Set up a server to return without a hash for a form in the form list (easier to do this by modifying code)
2. Try to download that form

#### Expected behavior

We decided on Slack that instead of crashing we should try and look the form up by form version/id if there isn't hash and then deprecate "legacy" servers (and open rosa servers that don't include hash in form list) in version 1.31.

#### Other information 

Firebase crash here: https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/54fa1494150c042de3392317c1ba9c6e?time=last-seven-days&versions=v1.30.0-beta.1%20(4089)&sessionEventKey=60330A9F03DD00013B6E79E44280133C_1510441552822286565

Stacktrace:

```java
Caused by java.lang.IllegalArgumentException: the bind value at index 1 is null
       at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:183)
       at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:219)
       at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:49)
       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1959)
       at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:604)
       at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:475)
       at org.odk.collect.android.provider.FormsProvider.query(FormsProvider.java:148)
       at android.content.ContentProvider.query(ContentProvider.java:1235)
       at android.content.ContentProvider.query(ContentProvider.java:1328)
       at android.content.ContentProvider$Transport.query(ContentProvider.java:267)
       at android.content.ContentResolver.query(ContentResolver.java:951)
       at android.content.ContentResolver.query(ContentResolver.java:887)
       at android.content.ContentResolver.query(ContentResolver.java:843)
       at org.odk.collect.android.dao.FormsDao.getFormsCursor(FormsDao.java:53)
       at org.odk.collect.android.dao.FormsDao.getFormsCursorForMd5Hash(FormsDao.java:184)
       at org.odk.collect.android.database.DatabaseFormsRepository.getOneByMd5Hash(DatabaseFormsRepository.java:70)
       at org.odk.collect.android.formmanagement.ServerFormDownloader.downloadForm(ServerFormDownloader.java:58)
       at org.odk.collect.android.tasks.DownloadFormsTask.doInBackground(DownloadFormsTask.java:61)
       at org.odk.collect.android.tasks.DownloadFormsTask.doInBackground(DownloadFormsTask.java:40)
       at android.os.AsyncTask$3.call(AsyncTask.java:378)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by seadowg** [comment]
@lognaturel @grzesiek2010 interested in your thoughts on this

**Comment by grzesiek2010** [comment]
Maybe we should look at it even broader. This month I had a user on the forum who had problems with forms that were constantly displayed as outdated. It turned out that the problem was lack of form version https://forum.getodk.org/t/issue-with-pulldata-update-of-form-you-have/32282/9?u=grzesiek2010

maybe we should go through the whole response (list of forms) and validate it.
Maybe the form version is not a good example because, in fact, it can be empty the problem was that it was empty in the list of forms but the form itself had its number so it would be difficult to validate but some other fields we could validate.

**Comment by seadowg** [comment]
Yeah, that makes sense to me. Right now we validate id, name and download URL but according to the [Open Rosa docs](https://docs.getodk.org/openrosa-form-list/#successful-response-document) we should expect a version and hash as well.

The change here could be to validate all the Open Rosa required fields and change the error messages, so it's clearer there is a problem with the form list (right now I think it will just say "Form list download failed" if we made the parser stricter).

**Comment by lognaturel** [comment]
I saw the stack trace too and was not going to file the issue. I think our first responsibility is to users of known-compatible servers. If folks want to build their own servers and run into issues then they hopefully will work to figure out what went wrong and fix it on their end.

**Comment by grzesiek2010** [comment]
Just wanted to add here what I said during our meeting:
I agree this is low priority but the advantage would be that users would immediately know what's going on and wouldn't ask us to check if it's a bug on our side. So we might add such validation in the future.

**Comment by lognaturel** [comment]
We had never seen this crash before and are now seeing it surprisingly frequently from the release ([Crashlytics](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/54fa1494150c042de3392317c1ba9c6e?time=last-seven-days&versions=v1.30.0%20(4092)&sessionEventKey=60356D1D0396000148EDDE271A93CD63_1511013561937455599)). It's possible that someone has just started experimenting with a new server but it seems that if form download didn't work they wouldn't have rolled it out to 6+ people.

I see [in these log details](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/54fa1494150c042de3392317c1ba9c6e?time=last-seven-days&sessionEventKey=603569D70397000144E9DE271A93CD63_1511011602640964196) that the user was getting `FetchError`s. That could possibly point to a bad server. I do also see `X-OpenRosa-Version unrecognized version(s): 1` from [this log](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/54fa1494150c042de3392317c1ba9c6e?time=last-seven-days&versions=v1.30.0%20(4092)&sessionEventKey=603555F6038C000143619B59A7911386_1510987681107759223). So I do think it's still likely that this is due to a bad server but we should really keep an eye on it.

**Comment by seadowg** [comment]
Ah it looks like if we get a non open rosa response for the form list the hash will always be null as in `OpenRosaFormSource#parseLegacyFormList` we do:

```
formList.add(new FormListItem(downloadUrl, formId, null, null, formName, null));
```

I'm going to do more digging but this would lead me to believe that the app is currently broken for anyone returning a form list without the correct open rosa headers.

**Comment by grzesiek2010** [comment]
Yes but OpenRosaResponseParserImpl#parseFormList also might return null hash if the received value is null or empty:
```
                        hash = XFormParser.getXMLText(child, true);
                        if (hash != null && hash.length() == 0) {
                            hash = null;
                        }
```

**Comment by seadowg** [comment]
@grzesiek2010 yeah sorry it can also happen if the response does include open rosa headers but not a hash.
