### ISSUE TITLE
Crash: Non-Question object at the form index

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#445]
#### Software and hardware versions 
Collect v1.4.15

#### Problem description
Seeing a crash in the Play Store Console related to recent changes in #406

#### Other information 
```
java.lang.RuntimeException: Invalid query for Question prompt. Non-Question object at the form index
	at org.javarosa.form.api.FormEntryModel.getQuestionPrompt(FormEntryModel.java:166)
	at org.javarosa.form.api.FormEntryModel.getQuestionPrompt(FormEntryModel.java:178)
	at org.odk.collect.android.logic.FormController.getQuestionPrompt(FormController.java:898)
	at org.odk.collect.android.widgets.QuestionWidget.clearNextLevelsOfCascadingSelect(QuestionWidget.java:401)
	at org.odk.collect.android.widgets.SelectOneWidget.onCheckedChanged(SelectOneWidget.java:203)
	at android.widget.CompoundButton.setChecked(CompoundButton.java:127)
	at android.widget.CompoundButton.toggle(CompoundButton.java:87)
	at android.widget.RadioButton.toggle(RadioButton.java:76)
	at android.widget.CompoundButton.performClick(CompoundButton.java:99)
	at android.view.View$PerformClick.run(View.java:18815)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5359)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by grzesiek2010** [comment]
This problem occurs only with select one widget and only if we use field-list (all on one page).
here is a form:
[form.txt](https://github.com/opendatakit/collect/files/789813/form.txt)
