### ISSUE TITLE
Investigate existing project import performance

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4578]
Blocked by #4544 

Currently, we import the "existing" project for upgrades as part of the app boot up in `ApplicationInitializer`. We should do some research and testing to work out if this could be slow and should really happen off the UI thread. 

It might be that we look at just moving our entire execution of `ApplicationInitlizer#init` off the UI thread and block the app (on the splash screen) until it's finished. It looks like doing this would actually fit pretty well into the new Splash Screen API (an example of keeping the splash screen up while doing initialization is [here](https://developer.android.com/about/versions/12/features/splash-screen#suspend-drawing)).

The goal of this task should just to be to work out our best next step.

**Comment by lognaturel** [comment]
What do you think about @getodk/testers doing a first pass to push some many thousands of instances to v1.30.1, then upgrade and report what happens?

**Comment by seadowg** [comment]
@lognaturel yup! That makes sense. @getodk/testers Just to be clear this isn't merged yet so don't start on that 😆

**Comment by seadowg** [comment]
@mmarciniak90 @kkrawczyk123 I think we're in a place where we're ready to check this!

**Comment by kkrawczyk123** [comment]
@seadowg @lognaturel I have just tried update from 1.30 to the newest beta. I had 90 forms, 1000+ submissions and also added offline layers. Everything went well on all my devices (Androids: 8.1, 10 and 11) except the device with Android 5.1 where I wasn't able to open Collect after updating it. I have tried to build the newest master by myself and I was able to use app. Then I tried just to install the app from play store on that device it installed successfully but also not run, it looks like it's crashing right after trying to run it. The issue occurs only on the build from the store. I have also tried the update on the device with Android 7.1 and I wasn't able to reproduce that issue. 

I was able to get stacktrace:
`06-18 15:13:57.114 21911-21911/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.odk.collect.android, PID: 21911
    java.lang.RuntimeException: Unable to create application org.odk.collect.android.application.Collect: java.lang.RuntimeException: Cannot create directory: /storage/emulated/0/Android/data/org.odk.collect.android/files/projects
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4597)
        at android.app.ActivityThread.access$1400(ActivityThread.java:155)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5298)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
     Caused by: java.lang.RuntimeException: Cannot create directory: /storage/emulated/0/Android/data/org.odk.collect.android/files/projects
        at org.odk.collect.android.utilities.FileUtils.createDir(SourceFile:573)
        at org.odk.collect.android.storage.StorageInitializer.createOdkDirsOnStorage(SourceFile:16)
        at org.odk.collect.android.application.initialization.ApplicationInitializer.initializeStorage(SourceFile:73)
        at org.odk.collect.android.application.initialization.ApplicationInitializer.initialize(SourceFile:58)
        at org.odk.collect.android.application.Collect.onCreate(SourceFile:122)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
        at android.app.ActivityThread.access$1400(ActivityThread.java:155) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5298) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706) 
`

**Comment by seadowg** [comment]
@kkrawczyk123 are you saying this happens in 5.1 all the time - not just when upgrading?

**Comment by lognaturel** [comment]
On my Android 5.1 Galaxy Tab A, I've tried a clean install straight to v2021.2 from the Play Store as well as v1.30.1 -> v2021.2 from Play Store. Both work without problems so it looks like it has to do with the device status in some way. @kkrawczyk123 could you please check with `adb` whether `/storage/emulated/0/Android/data/org.odk.collect.android/files/projects` exists already? If so, is it possibly a file rather than a folder?

**Comment by kkrawczyk123** [comment]
It is something extra weird! When I installed Collect from Play store and tried to run it - I don't even have projects folder created on that device with Android 5.1 - app doesn't run like I mentioned before. I tried to restart the device and I was able to run Collect! I checked with adb that project folder has been created. See it on my screenshot - in first check files folder is empty, and in the second after restarting device project folder is visible:
![Screenshot from 2021-06-21 12-59-32](https://user-images.githubusercontent.com/33342488/122753497-a4fc7a00-d292-11eb-9c5e-1b57504af38b.png)

It is a kind of workaround, after reset I am able to use Collect. 

The result of updating scenario is exactly the same: 
![Screenshot from 2021-06-21 13-28-01](https://user-images.githubusercontent.com/33342488/122754984-a169f280-d294-11eb-8218-1dde14e6d4a5.png)

I compared with other devices and project folder in created when updated in all tries. As  @lognaturel device with Android 5.1 works well it might be connected to the specific device then.

**Comment by seadowg** [comment]
@kkrawczyk123 is that consistent for that device? You always have to restart it to get Collect working? Is that just when you install the new version as an update/upgrade or does it also happen when you install fresh?

**Comment by kkrawczyk123** [comment]
@seadowg with a fresh install of the newest beta and when update older versions with beta, both. After resetting the device I am able to use Collect. I don't have to reset the device after opening app again or after killing it.

**Comment by seadowg** [comment]
@kkrawczyk123 really weird. I guess the problem is that that launching the app won't work if we can't create that directory anyway, so if it's just that device, I'm not sure what we can do to fix it...
