### ISSUE TITLE
BaseEncoding$DecodingException

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#4740]
#### Software and hardware versions 
Collect v2021.2.0

#### Problem description
https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/af3e3def7568395f1fe76cadafc4bb5a?time=last-seven-days&versions=v2021.2.0%20(4242)&sessionEventKey=61009DC6028300010C4FE545FB872E17_1568208913187990777

```
Caused by com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: :
       at com.google.common.io.BaseEncoding$Alphabet.decode(BaseEncoding.java:492)
       at com.google.common.io.BaseEncoding$Base64Encoding.decodeTo(BaseEncoding.java:974)
       at com.google.common.io.BaseEncoding.decodeChecked(BaseEncoding.java:233)
       at com.google.common.io.BaseEncoding.decode(BaseEncoding.java:217)
       at com.google.api.client.util.Base64.decodeBase64(Base64.java:104)
       at org.odk.collect.android.utilities.CompressionUtils.decompress(CompressionUtils.java:74)
       at org.odk.collect.android.projects.QrCodeProjectCreatorDialog$startScanning$1.onChanged(QrCodeProjectCreatorDialog.java:219)
       at org.odk.collect.android.projects.QrCodeProjectCreatorDialog$startScanning$1.onChanged(QrCodeProjectCreatorDialog.java:41)
       at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
       at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
       at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
       at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
       at org.odk.collect.android.views.BarcodeViewDecoder$1.barcodeResult(BarcodeViewDecoder.java:21)
       at com.journeyapps.barcodescanner.DecoratedBarcodeView$WrappedCallback.barcodeResult(DecoratedBarcodeView.java:50)
       at com.journeyapps.barcodescanner.BarcodeView$1.handleMessage(BarcodeView.java:52)
```

**Comment by grzesiek2010** [comment]
To reproduce the issue try adding a new project scanning QR codes that does not contain our settings like:
https://en.wikipedia.org/wiki/QR_code#/media/File:QR_code_for_mobile_English_Wikipedia.svg
