### ISSUE TITLE
EDIT action for forms will crash if there are no projects

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4743]
#### Software and hardware versions 
Collect v2021.2

#### Problem description

Trying to open a form from a URI or shortcut when there are no projects causes a crash.

#### Steps to reproduce the problem

1. Create a shortcut for a form
2. Delete all the projects in Collect
3. Click on shortcut

#### Expected behavior

Collect should a warning dialog and then close when the dialog is dismissed.

#### Other information 

Crashlytics report: https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/7abd65245bbd49ab8e4cd8acb06ad287?time=last-seven-days&versions=v2021.2.0%20(4242)&sessionEventKey=61012C22032C00010321849F7FC5E726_1568363353904663998

Stacktrace:

```
Caused by java.util.NoSuchElementException: List is empty.
       at kotlin.collections.CollectionsKt___CollectionsKt.first(CollectionsKt___CollectionsKt.java:212)
       at kotlin.collections.CollectionsKt.first(CollectionsKt.java)
       at org.odk.collect.android.external.FormUriActivity.onCreate(FormUriActivity.java:28)
       at android.app.Activity.performCreate(Activity.java:7895)
       at android.app.Activity.performCreate(Activity.java:7883)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3310)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3491)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2055)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7649)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by seadowg** [comment]
This is related to #4744 but warrants being called out separately seeing as it can be reproduced using shortcuts (rather than an external app).

**Comment by seadowg** [comment]
Moving this into the 2021.3 mileston as it's hitting a few people in 2021.2 and feels like it would be nice to solve. My thinking is that Collect should just show a warning and close.
