### ISSUE TITLE
Exception: java.net.MalformedURLException: no protocol: /formList

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#4760]
#### Software and hardware versions 
Collect v1.30.0+

#### Problem description
https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/0eb21b2826f841ac4546edde025cef48?time=last-seven-days&versions=v2021.2.0%20(4242)&sessionEventKey=6102F10300F000011AF48BD27C5DA83F_1568862901923153964

```
Non-fatal Exception: java.net.MalformedURLException: no protocol: /formList
       at java.net.URL.<init>(URL.java:590)
       at java.net.URL.<init>(URL.java:487)
       at java.net.URL.<init>(URL.java:436)
       at org.odk.collect.android.openrosa.OpenRosaXmlFetcher.fetch(OpenRosaXmlFetcher.java:93)
       at org.odk.collect.android.openrosa.OpenRosaXmlFetcher.getXML(OpenRosaXmlFetcher.java:54)
       at org.odk.collect.android.openrosa.OpenRosaFormSource.lambda$fetchFormList$0(OpenRosaFormSource.java:42)
       at org.odk.collect.android.openrosa.OpenRosaFormSource.lambda$fetchFormList$0$OpenRosaFormSource(OpenRosaFormSource.java)
       at org.odk.collect.android.openrosa.-$$Lambda$OpenRosaFormSource$oHfwyAcGQVxhQTD7_HASB3hwlMU.call(-.java:2)
       at org.odk.collect.android.openrosa.OpenRosaFormSource.mapException(OpenRosaFormSource.java:130)
       at org.odk.collect.android.openrosa.OpenRosaFormSource.fetchFormList(OpenRosaFormSource.java:42)
```

**Comment by grzesiek2010** [comment]
This exception is thrown if url is empty or with no protocol. We are protected against cases like that if we add a new project manually or if we set url in server settings but not if we scan a QR code where that value is invalid.

There are two options:
1. We can validate urls that come from qr codes and do not set if they are invalid - I'm not sure if I like it because then users might think that there is something wrong with ODK Collect not their QR codes.
2. We can catch this case and display a better message than: `If you keep having this problem, report it to the person who asked you to collect data.`

What do you think?
