### ISSUE TITLE
Repeats in 'field-list' groups are not supported

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#4765]
#### Problem description
https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/44e210b9709c05e63a7a9b8906186ff0?time=last-seven-days&versions=v2021.2.0%20(4242)&sessionEventKey=6102364401A700014F16018A0C782435_1568721843148212031

```
Non-fatal Exception: java.lang.RuntimeException: Repeats in 'field-list' groups are not supported. Please update the form design to remove the following repeat from a field list: /data/g2/g03/c06
       at org.odk.collect.android.formentry.audit.AuditUtils.logCurrentScreen(AuditUtils.java:28)
       at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1108)
       at org.odk.collect.android.activities.FormEntryActivity.animateToNextView(FormEntryActivity.java:1384)
       at org.odk.collect.android.activities.FormEntryActivity.onScreenChange(FormEntryActivity.java:1350)
       at org.odk.collect.android.formentry.FormIndexAnimationHandler.handle(FormIndexAnimationHandler.java:34)
       at org.odk.collect.android.activities.FormEntryActivity$3$1.lambda$run$0(FormEntryActivity.java:1623)
       at org.odk.collect.android.activities.FormEntryActivity$3$1.lambda$run$0$FormEntryActivity$3$1(FormEntryActivity.java)
       at org.odk.collect.android.activities.-$$Lambda$FormEntryActivity$3$1$90F3IbGPo_zO8Zgl29VDQyPAMYI.run(-.java:2)
```

**Comment by grzesiek2010** [comment]
It's a form design issue that we are able to identify so I think we shouldn't log it as error. Do you agree?

**Comment by seadowg** [comment]
I think it is interesting to see how often it happens. Maybe it should be an analytics event instead?

**Comment by seadowg** [comment]
I think we should go with an analytics event for this. That will make it easier to track between versions (currently the crash can "move" if anything in the stack trace changes). If we feel like the numbers are low enough we can just get rid of the event.

**Comment by lognaturel** [comment]
@seadowg I don't think having an analytics event will change our behavior. What do you see us doing differently if it happens a lot? https://github.com/getodk/collect/pull/4913#discussion_r753379568

**Comment by seadowg** [comment]
> @seadowg I don't think having an analytics event will change our behavior. What do you see us doing differently if it happens a lot? #4913 (comment)

Potentially link to docs? I don't have anything convincing, but it felt like it might be nice to keep track of it. I don't have any strong feelings here, and we can always assume we'll get complaints on the forum if people really need this. I'm happy with removing the analytics.
