### ISSUE TITLE
Permission denied when attempting to load settings barcode image to create project

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#4771]
#### Software and hardware versions 
Collect v2021.2.0

#### Problem description
https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/da090a79d435fa34b7094f7d3e6377b6?time=last-seven-days&versions=v2021.2.1%20(4250)&sessionEventKey=6106E410007B00015CF0CF03527E49C5_1569972022866465907

```
Caused by java.io.FileNotFoundException: /storage/emulated/0/GBWhatsApp/Media/GBWhatsApp Images/IMG-20210801-WA0010.jpg (Permission denied)
       at java.io.FileInputStream.open0(FileInputStream.java)
       at java.io.FileInputStream.open(FileInputStream.java:200)
       at java.io.FileInputStream.<init>(FileInputStream.java:150)
       at java.io.FileInputStream.<init>(FileInputStream.java:103)
       at android.content.ContentResolver.openInputStream(ContentResolver.java:965)
       at org.odk.collect.android.projects.QrCodeProjectCreatorDialog$imageQrCodeImportResultLauncher$1.onActivityResult(QrCodeProjectCreatorDialog.java:86)
       at org.odk.collect.android.projects.QrCodeProjectCreatorDialog$imageQrCodeImportResultLauncher$1.onActivityResult(QrCodeProjectCreatorDialog.java:41)
       at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:148)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
       at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
       at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
```

**Comment by grzesiek2010** [comment]
@seadowg in firebase note you said that it's about missing files but in fact I think it's more about permission and maybe we could try fixing it by using our `requestReadUriPermission()` method: https://github.com/grzesiek2010/collect/commit/12a0d13f1681dc22c6d8f3de91204f8543553e96
we do the same in other places where we access files. What do you think?

**Comment by lognaturel** [comment]
@grzesiek2010 Have you tried to reproduce? I wonder whether this could be related to some weird storage usage that GBWhatsApp makes.

I only considered getting an image from `Downloads` or some other public space. I'm surprised that the file picker will list files into other apps' space. And I'd expect that if the file picker could access it then the app that called the file picker would also have permissions. But I've learned to not ask too many questions when it comes to these file permissions things because the answers don't make sense to me. If your proposed fix works, I think we should go for it and not worry too much about why it's needed.

**Comment by lognaturel** [comment]
Do you think your fix would address something like [this](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/da090a79d435fa34b7094f7d3e6377b6?time=last-seven-days&versions=v2021.2.1%20(4250);v2021.2.0%20(4242)&sessionEventKey=61055BD7017E000134DF22C55568F18E_1569540585939609229)?

**Comment by grzesiek2010** [comment]
> Have you tried to reproduce?

No I haven't.

> Do you think your fix would address something like this?

Yeah I think it should handle that case.

I think we can give it a try it's a safe fix.

**Comment by lognaturel** [comment]
Let’s do it!

**Comment by grzesiek2010** [comment]
Ok I'll create a pull request
