### ISSUE TITLE
Collect crashes when use Mapbox and open any geo map widget on Android 11

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#4851]
#### Software and hardware versions 
Collect v2021.3.1 - store version and master Android v 11 device used...

#### Problem description
When testing #4829 I have noticed crash when use Mapbox and try to use any Geo widgets that uses map view. After investigation it turned out to be visible also on store version and master also and it's not a regression connected to PR's changes.

#### Steps to reproduce the problem
1. Set Mapbox in map settings
2. Click on start button on any Geo widget with map type/Geo trace/Geo shape

#### Expected behavior
Collect should not crash, user should be able to use all Geo widgets when Mapbox is selected.

#### Other information 
- issue does not occur for Google or OSM 
- issue does not occur on other Androids 
- stacktrace:
`2021-10-08 11:32:24.765 18128-18128/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.odk.collect.android, PID: 18128
    java.lang.SecurityException: getDataNetworkTypeForSubscriber
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3021)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2985)
        at com.mapbox.android.telemetry.TelemetryUtils.obtainCellularNetworkType(TelemetryUtils.java:165)
        at com.mapbox.mapboxsdk.module.telemetry.PhoneState.<init>(PhoneState.java:39)
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.onAppUserTurnstileEvent(TelemetryImpl.java:46)
        at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:303)
        at org.odk.collect.android.geo.mapboxsdk.MapFragment.onViewCreated(MapFragment.java:123)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8024)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`
- Logged on Firebase [here](https://github.com/getodk/collect/issues/4851).

**Comment by seadowg** [comment]
@kkrawczyk123 does this happen in v2021.2 as well or is it a regression?

**Comment by kkrawczyk123** [comment]
@seadowg definitely a regression! It works well on v2021.3.0 and older ones.

**Comment by seadowg** [comment]
> definitely a regression! It works well on v2021.3.0 and older ones.

Do you mean v2021.2?

**Comment by kkrawczyk123** [comment]
Yes, I tried on v2021.2.x and it works. It is broken on v2021.3-beta.1.
