### ISSUE TITLE
java.lang.RuntimeException: Could not allocate dup blob fd.

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5007]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/bb3de6a367388d12a48d24f90bab97a6?versions=v2022.1.0%20(4359)&time=last-seven-days&types=crash&sessionEventKey=61F6AB76002B000177D2525D3AABD425_1637466206334167960

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {org.odk.collect.android/org.odk.collect.android.activities.FormMapActivity}: java.lang.RuntimeException: Could not allocate dup blob fd.
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4559)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4591)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2151)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:250)
       at android.app.ActivityThread.main(ActivityThread.java:7844)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
```

```
Caused by java.lang.RuntimeException: Could not allocate dup blob fd.
       at android.graphics.Bitmap.nativeCreateFromParcel(Bitmap.java)
       at android.graphics.Bitmap.access$000(Bitmap.java:48)
       at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:2132)
       at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:2124)
       at ars.a(ars.java:2)
       at com.google.android.gms.maps.model.internal.a.bj(a.java:7)
       at arr.onTransact(arr.java:4)
       at android.os.Binder.transact(Binder.java:1052)
       at com.google.android.gms.internal.maps.zza.zzH(com.google.android.gms:play-services-maps@@18.0.0:2)
       at com.google.android.gms.internal.maps.zzg.zzg(com.google.android.gms:play-services-maps@@18.0.0:3)
       at com.google.android.gms.maps.model.BitmapDescriptorFactory.fromBitmap(com.google.android.gms:play-services-maps@@18.0.0:2)
```

**Comment by grzesiek2010** [comment]
The issue still exists:
https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/87d21f6b7611bc856af0b068eb341413?time=last-seven-days&types=crash&versions=v2022.3.2%20(4485)&sessionEventKey=630394DE015E0001132FB6D48A9C9B20_1713157071423182612
