### ISSUE TITLE
Unable to start activity ComponentInfo{org.odk.collect.android/org.odk.collect.errors.ErrorActivity}: java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.List<org.odk.collect.errors.ErrorItem>

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5015]
#### Software and hardware versions 
Collect v2022.1

#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/9f0addc78d6a8dfa56e0bf2535dc87ff?time=last-thirty-days&versions=v2022.1.0%20(4359)&types=crash&sessionEventKey=61FA4ACD026700014BDEF8B8134D7F66_1638483213915582049

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.odk.collect.android/org.odk.collect.errors.ErrorActivity}: java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.List<org.odk.collect.errors.ErrorItem>
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3827)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4003)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8595)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
```

**Comment by grzesiek2010** [comment]
This is a weird crash I tried to reproduce it but to no avail and also I can't see anything wrong in `ErrorActivity`.
@seadowg any idea?

**Comment by seadowg** [comment]
Yeah, I can't find a case where we pass anything nullable in as `ErrorActivity.EXTRA_ERRORS`. The only thing I can think of is that there might be some Activity recreation scenario where we get a new `Intent` rather than the original one. Not quite sure if that's a real thing though. Did you play around with "Don't keep Activities" enabled?

**Comment by grzesiek2010** [comment]
Yes I tried `Don't keep Activities` and also disabling background processes.

**Comment by seadowg** [comment]
I've asked a question on SO about this as I can't work it out: https://stackoverflow.com/questions/71884458/activity-intent-sometimes-has-null-extra. In addition, I'll make the Activity able to cope with this scenario - we can just finish if the extra is `null`.
