### ISSUE TITLE
Crash after selecting feature using osmdroid 

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5074]
#### Problem description

```
java.lang.NullPointerException: Attempt to invoke interface method 'void org.osmdroid.api.IMapController.stopAnimation(boolean)' on a null object reference
	at org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.disableFollowLocation(MyLocationNewOverlay.java:408)
	at org.odk.collect.android.geo.OsmDroidMapFragment.enableLocationUpdates(OsmDroidMapFragment.java:438)
	at org.odk.collect.android.geo.OsmDroidMapFragment.onPause(OsmDroidMapFragment.java:155)
	at androidx.fragment.app.Fragment.performPause(Fragment.java:3200)
	at androidx.fragment.app.FragmentStateManager.pause(FragmentStateManager.java:630)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:293)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
```

#### Steps to reproduce the problem
The only way I've found to reproduce is to set the basemap as osm, use a form for selecting a feature (e.g. [this one](https://docs.google.com/spreadsheets/d/191Taxl2BU1UmBPpU4SLXEiP2cnhVx7mSe8TJeKnEDAI/edit#gid=0)) with https://github.com/getodk/collect/pull/5073 and select a feature. @seadowg mentioned [here](https://github.com/getodk/collect/pull/5073#issuecomment-1079742986) that it's existing behavior so it may be reproducible with the form instance map.

#### Expected behavior
No crash.

#### Other information 
The selection seems to work, there's just a crash after.

**Comment by seadowg** [comment]
I've filed an [issue](https://github.com/osmdroid/osmdroid/issues/1783) with OSM for the issue we're running into here, but I've got a work around as well.

**Comment by seadowg** [comment]
Got the syntax wrong on the PR so closing this manually.
