### ISSUE TITLE
RuntimeException in GoogleMapFragment.getBitmapDescriptor(GoogleMapFragment.java:648)

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5109]
#### Software and hardware versions 
Collect v2022.2

#### Problem description
https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/04475f973b9e0984b3bb866519df895d?time=last-ninety-days&versions=v2022.2.0%20(4418)&types=crash&sessionEventKey=625DAE1F028300013BFCF7D414D4A4F7_1666461187049181304

```
Fatal Exception: java.lang.RuntimeException: Could not copy bitmap to parcel blob.
       at android.graphics.Bitmap.nativeWriteToParcel(Bitmap.java)
       at android.graphics.Bitmap.writeToParcel(Bitmap.java:2140)
       at com.google.android.gms.internal.maps.zzc.zzd(com.google.android.gms:play-services-maps@@18.0.0:3)
       at com.google.android.gms.internal.maps.zzg.zzg(com.google.android.gms:play-services-maps@@18.0.0:2)
       at com.google.android.gms.maps.model.BitmapDescriptorFactory.fromBitmap(com.google.android.gms:play-services-maps@@18.0.0:2)
       at org.odk.collect.android.geo.GoogleMapFragment.getBitmapDescriptor(GoogleMapFragment.java:648)
       at org.odk.collect.android.geo.GoogleMapFragment.createMarker(GoogleMapFragment.java:625)
       at org.odk.collect.android.geo.GoogleMapFragment.access$000(GoogleMapFragment.java:70)
       at org.odk.collect.android.geo.GoogleMapFragment$MarkerFeature.<init>(GoogleMapFragment.java:688)
       at org.odk.collect.android.geo.GoogleMapFragment.addMarker(GoogleMapFragment.java:263)
       at org.odk.collect.geo.selection.SelectionMapFragment.updateFeatures(SelectionMapFragment.kt:361)
```

**Comment by grzesiek2010** [comment]
I can't reproduce the issue. There is also nothing bad in our implementation that we could improve. Since it's not new and we have only 2 affected users let's leave it for now and monitor.
