### ISSUE TITLE
OSM causes a crash on loading the map in geojson form with thousand points

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5174]
**Software and hardware versions**

Android all versions

**Problem description**

When OSM is used as a source of maps on geojson form , it causes an instant crash after clicking „Select place”.

**Steps to reproduce the problem**

    1. Select OpenStreetMap in Settings -> Maps 
    2. Download geojson form with thousand points
    
[geojson.xml.txt](https://github.com/getodk/collect/files/9046406/geojson.xml.txt)
[thousand-points.geojson.txt](https://github.com/getodk/collect/files/9046407/thousand-points.geojson.txt)

    3. Click Select place
   
       
**Expected behavior**

Map should load. The app doesn’t crash.

**Other information**

Checked on geojson form with thousand points. Works well on Google Maps. 

OSM crash on Android 11 in Logcat

`2022-07-05 11:27:48.212 10466-10466/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.odk.collect.android, PID: 10466
    java.lang.IllegalArgumentException: north must be in [-85.05112877980658,85.05112877980658]
        at org.osmdroid.util.BoundingBox.set(BoundingBox.java:74)
        at org.osmdroid.util.BoundingBox.<init>(BoundingBox.java:49)
        at org.osmdroid.views.overlay.Marker.setPosition(Marker.java:192)
        at org.odk.collect.osmdroid.OsmDroidMapFragment.createMarker(OsmDroidMapFragment.java:557)
        at org.odk.collect.osmdroid.OsmDroidMapFragment.access$400(OsmDroidMapFragment.java:84)
        at org.odk.collect.osmdroid.OsmDroidMapFragment$MarkerFeature.<init>(OsmDroidMapFragment.java:697)
        at org.odk.collect.osmdroid.OsmDroidMapFragment.addMarker(OsmDroidMapFragment.java:276)
        at org.odk.collect.geo.selection.SelectionMapFragment.updateFeatures(SelectionMapFragment.kt:370)
        at org.odk.collect.geo.selection.SelectionMapFragment.updateItems(SelectionMapFragment.kt:328)
        at org.odk.collect.geo.selection.SelectionMapFragment.initMap$lambda-14(SelectionMapFragment.kt:204)
        at org.odk.collect.geo.selection.SelectionMapFragment.$r8$lambda$SlaLN6kg4v5ozQIoXqTju2L70Dw(Unknown Source:0)
        at org.odk.collect.geo.selection.SelectionMapFragment$$ExternalSyntheticLambda6.onChanged(Unknown Source:6)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
        at org.odk.collect.androidshared.livedata.MutableNonNullLiveData.setValue(NonNullLiveData.kt:22)
        at org.odk.collect.android.widgets.items.SelectChoicesMapData._init_$lambda-1(SelectOneFromMapDialogFragment.kt:153)
        at org.odk.collect.android.widgets.items.SelectChoicesMapData.$r8$lambda$5V0uyUQGGttEA-c1pkszmMf-IO4(Unknown Source:0)
        at org.odk.collect.android.widgets.items.SelectChoicesMapData$$ExternalSyntheticLambda0.accept(Unknown Source:6)
        at org.odk.collect.async.CoroutineScheduler$immediate$1.invokeSuspend(CoroutineScheduler.kt:17)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
        Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@298d609, Dispatchers.Main]
`

**Comment by seadowg** [comment]
@lognaturel the problem here is specific points being beyond the poles right? I thought we already had an issue for that, but I can't find it?

**Comment by lognaturel** [comment]
Yes, it’s described at https://github.com/osmdroid/osmdroid/issues/1339#issuecomment-491519929 and we mentioned it at https://github.com/getodk/collect/issues/5075, https://github.com/getodk/collect/pull/5073#issuecomment-1080952039, https://github.com/getodk/collect/pull/5098#issuecomment-1097946404

Best might be to stop using that form.
