### ISSUE TITLE
IllegalStateException: Slider value(2.0) must be greater or equal to valueFrom(15.0), and lower or equal to valueTo(45.0)

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5234]
#### Problem description
https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/2d03a4f4e7ea859107ad4726c6007309?time=last-seven-days&versions=v2022.3.0%20(4477)&types=crash&sessionEventKey=62E92B9C029900017320226734DBC038_1705722385288083823

```
Fatal Exception: java.lang.IllegalStateException: Slider value(2.0) must be greater or equal to valueFrom(15.0), and lower or equal to valueTo(45.0)
       at com.google.android.material.slider.BaseSlider.validateValues(BaseSlider.java:549)
       at com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty(BaseSlider.java:602)
       at com.google.android.material.slider.BaseSlider.maybeCalculateTicksCoordinates(BaseSlider.java:1488)
       at com.google.android.material.slider.BaseSlider.updateTrackWidth(BaseSlider.java:1509)
       at com.google.android.material.slider.BaseSlider.onSizeChanged(BaseSlider.java:1479)
       at android.view.View.sizeChange(View.java:22738)
       at android.view.View.setFrame(View.java:22690)
       at android.view.View.layout(View.java:22547)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:22550)
       at android.view.ViewGroup.layout(ViewGroup.java:6369)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:22550)
       at android.view.ViewGroup.layout(ViewGroup.java:6369)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
       at android.view.View.layout(View.java:22550)
       at android.view.ViewGroup.layout(ViewGroup.java:6369)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:22550)
       at android.view.ViewGroup.layout(ViewGroup.java:6369)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:22550)
       at android.view.ViewGroup.layout(ViewGroup.java:6369)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
```

#### Other information 
In firebase it's marked as fresh issue in v2022.3 but I'm pretty sure it's not a new regression

**Comment by grzesiek2010** [comment]
I figured out how to reproduce the issue:
1. Open the attached form [rangeWidgetBug.xlsx](https://github.com/getodk/collect/files/9250936/rangeWidgetBug.xlsx)
2. In the first question pass value > 5 or < 1
3. Swipe to the next question with range widget
