### ISSUE TITLE
Crash when restoring to some form entry screens

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5240]
~~Blocked by #5338 (which adds testing for the flows we're changing)~~

Covers this [crash report](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/7ef6006d57c29eff231ee9f78d2f188e?time=last-seven-days&versions=v2022.3.0%20(4477)&types=crash&sessionEventKey=62EB9C8D00D100017025055AC3E08E99_1706408576049390202) (and [this one](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/7ef6006d57c29eff231ee9f78d2f188e?time=last-seven-days&versions=v2022.3.0%20(4477)&types=crash&sessionEventKey=62EB9C8D00D100017025055AC3E08E99_1706408576049390202)).

#### ODK Collect version

v2022.2.3+

#### Android version

Reproduced on Android 10, but likely a problem in all versions

#### Device used

Pixel 2 emulator

#### Problem description

The app crashes when "restoring" (being reopened after being kicked out of memory rather than closed by the user) if the user was last on some form entry screens. An example is the Select One From Map map view (used in the example below).

#### Steps to reproduce the problem

1. Set "Background process limit" to "No background processes" in Developer Options
2. Open a form with a Select One From Map question
3. Go to question and click "Select Place"
4. Switch to another app and then back again

The app crashes. This also happens (or the app behaves weirdly) when restoring to the:

* Quit form dialog - will show the hierarchy and then the dialog when you exit the hierarchy. Additionally, the dialog title will just be "no form loaded".
* The form hierarchy - will show normal form entry instead of the hierarchy
* Form saving in progress (harder to reproduce but does [happen in reality](https://console.firebase.google.com/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/b7ee403472493aaecd327e67d5560ce7?time=last-seven-days&versions=v2022.4.1%20(4543)&types=crash&sessionEventKey=63971D31037100013CB113600829941E_1754682268331899682)) - will crash

#### Expected behavior

For the moment, we're going to avoid restoring view state when we do a process restore. This means that, to the user, the flow will look exactly the same as loading a form from a save point. To be explicit, in the case where a user is filling a form:

1. User answers some questions
2. Process is killed (either via background process kill or changing permissions in Android settings)
3. User navigates back to app
4. User sees hierarchy and pressing back takes them to the first question of the form (no dialogs etc are restored)

We'll need to be able to detect that a restore is happening for this to work.
 
#### Other information 

Restoring from background is a flow we've mostly forgotten about. @getodk/testers this (enabling "No background processes" and then switching apps) is a good way to find bugs/crashes that we probably miss while developing features.

The stack trace for the crash is:

```java
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'org.javarosa.form.api.FormEntryPrompt org.odk.collect.android.javarosawrapper.FormController.getQuestionPrompt(org.javarosa.core.model.FormIndex)' on a null object reference
       at org.odk.collect.android.formentry.FormEntryViewModel.getQuestionPrompt(FormEntryViewModel.java:237)
       at org.odk.collect.android.widgets.items.SelectOneFromMapDialogFragment.onAttach(SelectOneFromMapDialogFragment.kt:58)
       at androidx.fragment.app.Fragment.performAttach(Fragment.java:2954)
       at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:463)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:254)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
       at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2773)
       at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:251)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:252)
       at org.odk.collect.android.activities.CollectAbstractActivity.onCreate(CollectAbstractActivity.java:42)
       at org.odk.collect.android.activities.FormEntryActivity.onCreate(FormEntryActivity.java:383)
```

**Comment by seadowg** [comment]
@lognaturel @grzesiek2010 I think we should definitely look at this for the next release and consider it as a hotfix if it fits into one.

**Comment by seadowg** [comment]
I've moved this into "Hotfix" as it feels like it has potential to disrupt people during form entry (if they're multi tasking).
