### ISSUE TITLE
Removing one of the groups in nested repeats forms and clicking the back button causes the crash of the app

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5264]
**Software and hardware versions** 

Collect v2021.1.2,  Android probably all

**Problem description**

When the user removes a group (one of at least 2 groups) in a nested repeats form, clicking the device back button causes a crash. On Android 5.1 clicking the back button instead of crashing restores the removed group. On Android 12 the user needs to remove 2 groups to cause the crash of the app.

**Steps to reproduce the problem**

1. Go to nested-repeats form.
[nested-repeats.xml.txt](https://github.com/getodk/collect/files/9425583/nested-repeats.xml.txt)
2. Add a "Friend".
3. Enter a name.
4. Click next.
5. Add a "Pet".
6. Enter a name.
7. Click next.
8. Do not add another pet.
9. Add a "Friend".
10. Enter a name.
11.Click next.
12. Add a "Pet".
13. Enter a name.
14. Go to the hierarchy view.
15. Click the vertical arrow twice (so that you can see: "What is friend#2’s name?" and "Pets – Repeatable Group").
16. Click the bin.
17. Click remove group.
18. Click the device back button.

https://user-images.githubusercontent.com/56479916/186692360-5c90d0bb-4874-49d9-aca8-858cc81636d9.mp4

**Expected behavior**

The group should be removed. The app shouldn’t crash.

**Other information**

I haven’t checked earlier versions of ODK Collect than v2021.1.2.
The crash in Logcat from Android 11:

`2022-08-25 10:46:20.112 25127-25127/? E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.javarosa.core.model.instance.TreeElement.isRelevant()' on a null object reference
        at org.javarosa.core.model.FormDef.isRepeatRelevant(FormDef.java:548)
        at org.javarosa.form.api.FormEntryModel.isIndexRelevant(FormEntryModel.java:383)
        at org.javarosa.form.api.FormEntryController.stepEvent(FormEntryController.java:217)
        at org.javarosa.form.api.FormEntryController.stepToPreviousEvent(FormEntryController.java:198)
        at org.odk.collect.android.javarosawrapper.FormController.stepToPreviousEvent(FormController.java:785)
        at org.odk.collect.android.activities.FormHierarchyActivity.navigateToTheLastRelevantIndex(FormHierarchyActivity.java:775)
        at org.odk.collect.android.activities.FormHierarchyActivity.onBackPressed(FormHierarchyActivity.java:749)
        at android.app.Activity.onKeyUp(Activity.java:3841)
        at android.view.KeyEvent.dispatch(KeyEvent.java:3648)
        at android.app.Activity.dispatchKeyEvent(Activity.java:4147)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:599)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3090)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:758)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:7365)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7191)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6595)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6786)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6843)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6819)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:7007)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3624)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:3163)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:3154)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3601)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)`

**Comment by grzesiek2010** [comment]
I have a fix for this issue in javarosa https://github.com/getodk/javarosa/pull/710

**Comment by lognaturel** [comment]
@getodk/testers I'll reopen this so you can track it!

**Comment by srujner** [comment]
**Tested with Success!**

Verified on Android 12 and 13 on master: fb41bbe48afad425ae68aca14f5233e35e024084

Issue is no longer reproducing

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Android 10
