### ISSUE TITLE
Rotating the screen while a list is opened in select one widget with minimal appearance crashes the app

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5311]
#### ODK Collect version
master 454905f139520d061c45c7c38adde11ee1bddc7b
#### Android version
8.1, 10, 11, 13 (probably all)
#### Device used
Nexus 5X, Redmi 9T, Galaxy M12, Pixel 6a
#### Problem description
Collect crashes when the user rotates the screen while a list is opened in select one widget with minimal appearance.
#### Steps to reproduce the problem
1. Open the demo project.
2. Go to All widgets form.
3. Go to Select one minimal widget.
4. Tap to open the list.
5. Rotate the screen.
#### Expected behavior
The app shouldn’t crash.
#### Other information 
On the store version (2022.3.6) the crash doesn’t occur.

**Comment by dbemke** [comment]
Logs from the crash
`2022-10-18 15:18:11.832 6659-6659/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.odk.collect.android, PID: 6659
    java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.lifecycle.Lifecycle.addObserver(androidx.lifecycle.LifecycleObserver)' on a null object reference
        at org.odk.collect.android.audio.AudioHelper.registerLifecycleCallbacks(AudioHelper.java:98)
        at org.odk.collect.android.audio.AudioHelper.<init>(AudioHelper.java:57)
        at org.odk.collect.android.formentry.media.ScreenContextAudioHelperFactory.create(ScreenContextAudioHelperFactory.java:24)
        at org.odk.collect.android.fragments.dialogs.SelectMinimalDialog.initRecyclerView(SelectMinimalDialog.java:143)
        at org.odk.collect.android.fragments.dialogs.SelectMinimalDialog.onViewCreated(SelectMinimalDialog.java:76)
        at org.odk.collect.android.fragments.dialogs.SelectOneMinimalDialog.onViewCreated(SelectOneMinimalDialog.java:31)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3019)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at org.odk.collect.android.activities.FormEntryActivity.onStart(FormEntryActivity.java:1863)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
        at android.app.Activity.performStart(Activity.java:7946)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3346)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2058)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:226)
        at android.app.ActivityThread.main(ActivityThread.java:7592)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`
