### ISSUE TITLE
The app crashes in select place if in xml file there is a blank space in geometry values

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5372]
#### ODK Collect version
master 7daeabb6b3aa06f9363185b512f0f3a4e83bb7c3
#### Android version
10, 13 (probably all)
#### Device used
Redmi 9T, Pixel 6a
#### Problem description
Leaving a blank space in geometry values for "select place” included in xml file of a form crashes the app.
#### Steps to reproduce the problem
1. Go to the form with empty geometry value.
[mapinternalselectlocalizedchanged.xml.txt](https://github.com/getodk/collect/files/10183487/mapinternalselectlocalizedchanged.xml.txt)
2. Tap "select place”
#### Expected behavior
The app shouldn’t crash.

**Comment by lognaturel** [comment]
```
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.javarosa.core.model.data.IAnswerData.getDisplayText()' on a null object reference
 	at org.javarosa.core.model.SelectChoice.getChild(SelectChoice.java:125)
 	at org.odk.collect.android.widgets.items.SelectChoicesMapData.loadItemsFromChoices(SelectOneFromMapDialogFragment.kt:138)
 	at org.odk.collect.android.widgets.items.SelectChoicesMapData._init_$lambda-0(SelectOneFromMapDialogFragment.kt:123)
 	at org.odk.collect.android.widgets.items.SelectChoicesMapData.$r8$lambda$yC8Gq2u6TtxrrmK1U7cVeBP_s2c(SelectOneFromMapDialogFragment.kt)
 	at org.odk.collect.android.widgets.items.SelectChoicesMapData$$ExternalSyntheticLambda0.get(R8$$SyntheticClass)
 	at org.odk.collect.async.CoroutineScheduler$immediate$1$result$1.invokeSuspend(CoroutineScheduler.kt:16)
 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c500340, Dispatchers.Main]
```
