### ISSUE TITLE
NullPointerException in BaseImageWidget

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5430]
#### Problem description
https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/78ca0cb8bd09a651b334fd7d7ea20045?time=last-seven-days&versions=v2022.4.4%20(4565)&types=crash&sessionEventKey=63D8ED90020C000178639D742F856A00_1773207245904388188

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
       at org.odk.collect.android.widgets.BaseImageWidget$1.onLoadSucceeded(BaseImageWidget.java:152)
       at org.odk.collect.imageloader.GlideImageLoader$loadImage$2.onResourceReady(GlideImageLoader.kt:81)
       at org.odk.collect.imageloader.GlideImageLoader$loadImage$2.onResourceReady(GlideImageLoader.kt:63)
       at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:648)
       at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:596)
       at com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:159)
       at com.bumptech.glide.load.engine.EngineJob$CallResourceReady.run(EngineJob.java:428)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:7912)
       at java.lang.reflect.Method.invoke(Method.java)
```

**Comment by grzesiek2010** [comment]
I was able to reproduce the issue so here are the steps:
1. Install the ODK Collect and download a form with an Image Widget
2. Try to attach an image that is broken like: ![broken](https://user-images.githubusercontent.com/3276264/216419214-bdb7f88d-e21d-49fe-b840-69ddcf58bd88.png)
3. The image should not be attached and there should be an error message
4. Try to attach/take a valid image
