### ISSUE TITLE
Clicking the back button in Geoshape and Geotrace widget crashes the app

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5453]
#### ODK Collect version
master version 30a0e140bb024f781b952af3155951eaa7fb3659
#### Android version
8.1, 10, 13
#### Device used
Naxus 5X, Redmi 9T, Galaxy A32
#### Problem description
If the user clicks the device back button while the map is opened in Goeshape or Geotrace widget the app crashes. It occurs in all sources of maps.
#### Steps to reproduce the problem
1. Go to All widgets form.
2. Go to Geoshape/ Geotrace widget.
3. Tap "Start Geoshape”/”Start Geotrace”.
4. (Wait until the maps loads) Click the device back button.
#### Expected behavior
The map should close. The app shouldn’t crash.
#### Other information 
The issue doesn’t occur in the store version 2022.4.4.
The issue doesn’t occur if the user click the device back button in a form map, geopoint widget with maps or form Select one from map.
Logs from the crash:
`java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.equals(java.lang.Object)' on a null object reference
                                                                                                    	at org.odk.collect.geo.geopoly.GeoPolyActivity.onBackPressed(GeoPolyActivity.java:315)
                                                                                                    	at android.app.Activity.onKeyUp(Activity.java:3714)
                                                                                                    	at android.view.KeyEvent.dispatch(KeyEvent.java:2847)
                                                                                                    	at android.app.Activity.dispatchKeyEvent(Activity.java:4043)
                                                                                                    	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:126)
                                                                                                    	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:86)
                                                                                                    	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:144)
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:601)
                                                                                                    	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)
                                                                                                    	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3106)
                                                                                                    	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:380)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5797)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5646)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5132)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5185)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5151)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5291)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5159)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5348)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5132)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5185)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5151)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5159)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5132)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5185)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5151)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5324)
                                                                                                    	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5500)
                                                                                                    	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3072)
                                                                                                    	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2615)
                                                                                                    	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2606)
                                                                                                    	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3049)
                                                                                                    	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:336)
                                                                                                    	at android.os.Looper.loop(Looper.java:183)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7592)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`

**Comment by seadowg** [comment]
This is fixed by #5448
