### ISSUE TITLE
NullPointerException: Attempt to get length of null array in GeoPointWidget.java:80

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5532]
### ODK Collect version
v2023.1

#### Problem description
https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/4119e46f0db56faa60366cecc3c2a5eb?time=last-seven-days&versions=v2023.1.0%20(4611)&types=crash&sessionEventKey=64256BC3002B00011051E358219E22AF_1794739939514916490

```
Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
       at org.javarosa.core.model.data.GeoPointData.fillArray(GeoPointData.java:76)
       at org.javarosa.core.model.data.GeoPointData.<init>(GeoPointData.java:71)
       at org.odk.collect.android.widgets.GeoPointWidget.getAnswer(GeoPointWidget.java:80)
       at org.odk.collect.android.formentry.ODKView.getAnswers(ODKView.java:328)
       at org.odk.collect.android.activities.FormEntryActivity.getAnswers(FormEntryActivity.java:2640)
       at org.odk.collect.android.activities.FormEntryActivity.moveScreen(FormEntryActivity.java:1400)
       at org.odk.collect.android.activities.FormEntryActivity.onSwipeForward(FormEntryActivity.java:1363)
       at org.odk.collect.android.activities.FormEntryActivity.lambda$onCreate$6(FormEntryActivity.java:452)
       at android.view.View.performClick(View.java:7156)
       at android.view.View.performClickInternal(View.java:7129)
```

**Comment by seadowg** [comment]
Yeah this looks like it's related to the geometry parsing changes in https://github.com/getodk/collect/pull/5395
