### ISSUE TITLE
Removing a group in nested-indexed-repeat causes the crash of the app after tapping the device back button

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5539]
#### ODK Collect version
2022.4.4, 2023.1.0, the master version 5c8f9d88711cc210faf34ac47461a3f02a866af4
#### Android version
10, 13
#### Device used
Redmi 9T, Galaxy A32
#### Problem description
Removing a group with repeatable group and counting a value in nested-indexed-repeat form causes the crash of the app after tapping the device back button.
#### Steps to reproduce the problem
1. Go to nested-indexed-repeat form.
[nested-indexed-repeat.xml.txt](https://github.com/getodk/collect/files/11157156/nested-indexed-repeat.xml.txt)
2. Tap "add”.
3. Enter a friend’s name.
4. In next question enter a number (how many pets).
5. In following question enter a name of a pet (or leave the answer empty).
6. Go to the hierarchy view.
7. Tap the arrow twice (so that you can see "What is friend name, How many pets.., Pets repeatable group”).
8. Tap the bin icon and confirm in the dialog to remove the group.
9. When questions appear tap the device back button.
#### Expected behavior
The app shouldn’t crash.
#### Other information 
After reopening the form, the removed group (entered names) are still visible.

**Comment by seadowg** [comment]
@dbemke could you attach a stack trace for the crash here please?

**Comment by dbemke** [comment]
`java.lang.RuntimeException: Could not locate the repeat count value expected at /nested-indexed-repeat/friends/pets_count
                                                                                                    	at org.javarosa.core.model.FormDef.canCreateRepeat(FormDef.java:579)
                                                                                                    	at org.javarosa.form.api.FormEntryModel.isIndexRelevant(FormEntryModel.java:382)
                                                                                                    	at org.javarosa.form.api.FormEntryController.stepEvent(FormEntryController.java:231)
                                                                                                    	at org.javarosa.form.api.FormEntryController.stepToPreviousEvent(FormEntryController.java:202)
                                                                                                    	at org.odk.collect.android.javarosawrapper.JavaRosaFormController.stepToPreviousEvent(JavaRosaFormController.java:652)
                                                                                                    	at org.odk.collect.android.activities.FormHierarchyActivity.navigateToTheLastRelevantIndex(FormHierarchyActivity.java:825)
                                                                                                    	at org.odk.collect.android.activities.FormHierarchyActivity.onBackPressed(FormHierarchyActivity.java:799)
                                                                                                    	at android.app.Activity.onKeyUp(Activity.java:3714)
                                                                                                    	at android.view.KeyEvent.dispatch(KeyEvent.java:2847)
                                                                                                    	at android.app.Activity.dispatchKeyEvent(Activity.java:4043)
                                                                                                    	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:126)
                                                                                                    	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:86)
                                                                                                    	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:144)
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
                                                                                                    	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)
                                                                                                    	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3413)
                                                                                                    	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:380)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5797)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5646)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5132)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5185)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5151)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5291)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5159)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5348)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5132)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5185)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5151)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5159)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5132)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5185)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5151)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5324)
                                                                                                    	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5500)
                                                                                                    	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3072)
                                                                                                    	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2615)
                                                                                                    	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2606)
                                                                                                    	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3049)
                                                                                                    	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:336)
                                                                                                    	at android.os.Looper.loop(Looper.java:183)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7592)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2023-05-08 12:22:01.095 29671-29671 AndroidRuntime          org.odk.collect.android              E  FATAL EXCEPTION: main
                                                                                                    Process: org.odk.collect.android, PID: 29671
                                                                                                    java.lang.RuntimeException: Could not locate the repeat count value expected at /nested-indexed-repeat/friends/pets_count
                                                                                                    	at org.javarosa.core.model.FormDef.canCreateRepeat(FormDef.java:579)
                                                                                                    	at org.javarosa.form.api.FormEntryModel.isIndexRelevant(FormEntryModel.java:382)
                                                                                                    	at org.javarosa.form.api.FormEntryController.stepEvent(FormEntryController.java:231)
                                                                                                    	at org.javarosa.form.api.FormEntryController.stepToPreviousEvent(FormEntryController.java:202)
                                                                                                    	at org.odk.collect.android.javarosawrapper.JavaRosaFormController.stepToPreviousEvent(JavaRosaFormController.java:652)
                                                                                                    	at org.odk.collect.android.activities.FormHierarchyActivity.navigateToTheLastRelevantIndex(FormHierarchyActivity.java:825)
                                                                                                    	at org.odk.collect.android.activities.FormHierarchyActivity.onBackPressed(FormHierarchyActivity.java:799)
                                                                                                    	at android.app.Activity.onKeyUp(Activity.java:3714)
                                                                                                    	at android.view.KeyEvent.dispatch(KeyEvent.java:2847)
                                                                                                    	at android.app.Activity.dispatchKeyEvent(Activity.java:4043)
                                                                                                    	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:126)
                                                                                                    	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:86)
                                                                                                    	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:144)
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
                                                                                                    	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)
                                                                                                    	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3413)
                                                                                                    	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:380)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5797)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5646)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5132)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5185)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5151)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5291)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5159)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5348)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5132)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5185)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5151)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5159)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5132)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5185)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5151)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5324)
                                                                                                    	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5500)
                                                                                                    	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3072)
                                                                                                    	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2615)
                                                                                                    	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2606)
                                                                                                    	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3049)
                                                                                                    	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:336)
                                                                                                    	at android.os.Looper.loop(Looper.java:183)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7592)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2023`

**Comment by lognaturel** [comment]
I've verified https://github.com/getodk/javarosa/pull/734/files in Collect and merged it. It should be available in any builds of Collect that happen after now.

**Comment by dbemke** [comment]
**Tested with success!** 
Verified on a device with Android 10

**Comment by srujner** [comment]
Tested with success!
Verified on a device with Android 13
