### ISSUE TITLE
Crash when using external action without project configured

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#6026]
#### ODK Collect version

v2024.1.2

#### Problem description

Collect crashes if it's opened by an external action like `PICK` for forms if no project has been configured yet.

#### Steps to reproduce the problem

1. Install Collect without setting up a project
2. Use an external app (like [Collect Tester](https://github.com/grzesiek2010/collectTester)) to choose a form or an instance

#### Expected behavior

Collect should show an error dialog that then closes the app when dismissed.

#### Other information 

We're seeing this in the wild in [this crash report](https://console.firebase.google.com/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/9c2579e8d6ed64f9ba941680b873299a?time=last-seven-days&versions=v2024.1.2%20(4804)&types=crash&sessionEventKey=65FBC4F001A9000117FC44A48C016272_1927135983332568553):

```
Caused by java.lang.IllegalStateException: No current project!
       at org.odk.collect.android.projects.ProjectsDataService.getCurrentProject(ProjectsDataService.kt:52)
       at org.odk.collect.android.storage.StoragePathProvider.getProjectRootDirPath(StoragePathProvider.kt)
       at org.odk.collect.android.storage.StoragePathProvider.getProjectRootDirPath(StoragePathProvider.kt)
       at org.odk.collect.android.storage.StoragePathProvider.getOdkDirPath(StoragePathProvider.kt)
       at org.odk.collect.android.storage.StoragePathProvider.getOdkDirPath(StoragePathProvider.kt)
       at org.odk.collect.android.utilities.InstancesRepositoryProvider.get(InstancesRepositoryProvider.kt)
       at org.odk.collect.android.utilities.InstancesRepositoryProvider.get(InstancesRepositoryProvider.kt)
       at org.odk.collect.android.utilities.InstancesRepositoryProvider.get$default(InstancesRepositoryProvider.kt:5)
       at org.odk.collect.android.utilities.InstancesRepositoryProvider.get(InstancesRepositoryProvider.kt)
       at org.odk.collect.android.utilities.InstancesRepositoryProvider.get(InstancesRepositoryProvider.kt)
       at org.odk.collect.android.injection.config.AppDependencyModule.providesBlankFormListViewModel(AppDependencyModule.java:2)
       at org.odk.collect.android.injection.config.AppDependencyModule_ProvidesBlankFormListViewModelFactory.providesBlankFormListViewModel(AppDependencyModule_ProvidesBlankFormListViewModelFactory.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.blankFormListViewModelFactory(DaggerAppDependencyComponent.java:40)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.injectBlankFormListActivity(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.injection.config.DaggerAppDependencyComponent$AppDependencyComponentImpl.inject(DaggerAppDependencyComponent.java)
       at org.odk.collect.android.formlists.blankformlist.BlankFormListActivity.onCreate(BlankFormListActivity.kt:7)
```

**Comment by grzesiek2010** [comment]
The crash might occur not only if you try to open a form (blank or saved) from an external app (without any project configured) but also if you open one of the activities we export. There are a couple of them and [Collect Tester](https://github.com/grzesiek2010/collectTester) demonstrates it. Do you think we should create one base Activity for those exported ones and verify there's at least one project present? Alternatively, if we don't want to create a hierarchy of activities we can one object that would look for projects and would be injected into every exported list separately.

**Comment by seadowg** [comment]
> Alternatively, if we don't want to create a hierarchy of activities we can one object that would look for projects and would be injected into every exported list separately.

Yeah I think that's what I'd prefer. Some kind of helper that we can insert into the top of the `onCreate` of all of these.
