### ISSUE TITLE
Occasional crash in form with many audio questions that autoplay

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#6085]
#### ODK Collect version
v2024.1.0 - v2024.1.3 ([Crashlytics](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/04af9a6161835d2221134d97d1479a0a?time=last-ninety-days&types=crash&sessionEventKey=660F9F2E025D0001163775502B98BE34_1935004671239229137))

#### Android version
87% Android 13 since start (but also some 9, 12, 14 so maybe it's just the devices that happen to have forms that trigger this)

#### Device used
91% Samsung since start, reported by a user with a fleet of `Galaxy Tab S7 5G`, 82% of occurrences are with `Galaxy Tab Active3` (probably just happens to be those devices that have forms that trigger this)

#### Problem description
A user reports seemingly-random crashes while navigating through the section of a form that is many select questions with autoplay audio media. Users don't see any crash message when Collect restarts.

<details>
<summary>Crashlytics shows two stacktraces from crashes from `mediaplayer.prepare` and `mediaplayer.setDataSource`</summary>
```javarosa
Fatal Exception: java.lang.IllegalStateException:
       at android.media.MediaPlayer._prepare(MediaPlayer.java)
       at android.media.MediaPlayer.prepare(MediaPlayer.java:1435)
       at org.odk.collect.audioclips.AudioClipViewModel.loadNewClip$lambda$3(AudioClipViewModel.kt:26)
       at org.odk.collect.async.CoroutineScheduler$immediate$1$result$1.invokeSuspend(CoroutineScheduler.kt:12)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:11)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:98)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:3)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt)
```

```javarosa
Fatal Exception: java.lang.IllegalStateException:
       at android.media.MediaPlayer._setDataSource(MediaPlayer.java)
       at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1251)
       at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1234)
       at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1188)
       at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1164)
       at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1131)
       at org.odk.collect.audioclips.AudioClipViewModel.loadNewClip$lambda$3(AudioClipViewModel.kt:23)
       at org.odk.collect.async.CoroutineScheduler$immediate$1$result$1.invokeSuspend(CoroutineScheduler.kt:12)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:11)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:98)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:3)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt)
```
</details>

We always call
```
mediaPlayer.reset()
mediaPlayer.setDataSource(uri)
mediaPlayer.prepare()
```

which should put the player in the correct states according to [the state diagram](https://developer.android.com/reference/android/media/MediaPlayer#StateDiagram).

#### Steps to reproduce the problem
It can't be reproduced systematically.

I've used [audio crash.zip](https://github.com/getodk/collect/files/14950890/audio.crash.zip) to try to reproduce but can't.

#### Expected behavior
No crash.

#### Other information 
Presumably introduced by https://github.com/getodk/collect/pull/5836/files#diff-dd7070cc2905fbf7e644eac39e7590ff53ccf92fc0dfb39512a55315099e9619

I'm opening this issue to have a record of what we've considered/discovered here. I think it's likely there's some weird Samsung-Android 13 platform bug that we're hitting so I don't think we need to take immediate action.

Another idea is that mediaplayer is not threadsafe. Is there a way we could somehow be calling mediaplayer methods from different threads under some conditions?

**Comment by seadowg** [comment]
> Another idea is that mediaplayer is not threadsafe. Is there a way we could somehow be calling mediaplayer methods from different threads under some conditions?

This seems pretty possible. As far as I can see, actually starting and stopping media should be originating from the UI so should be mostly "thread safe", but as we load the actual media into the `MediaPlayer` on a background thread (to avoid ANRs) so we could end up in trouble that way. I think a first pass solution here would be to make clip loading thread safe in `AudioClipViewModel`.

**Comment by seadowg** [comment]
I'm prioritizing this for a hotfix after we've seen a spike in crashes.
