### ISSUE TITLE
Crash of the app after sending a draft version of trees update form

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6109]
#### ODK Collect version
the master version d27f63e28a4ab6592653f2ec7f84f93ddc3ff4d5
#### Android version
10,14
#### Device used
Redmi 9t, Pixel 7a
#### Problem description
There is a crash after sending a submission of a draft version of a trees update form.
https://test.getodk.cloud/#/projects/530/forms/trees_update/draft/testing
#### Steps to reproduce the problem
1. Create a project in Central.
2. Upload the form.
[Trees update.xlsx.txt](https://github.com/getodk/collect/files/15096198/Trees.update.xlsx.txt)
3. Go to the testing tab in the draft section and scan the QR code.
4. Fill the form (with no tree as there are no options) and send the submission.
#### Expected behavior
The form should be finalized/submitted successfully and no local entity should be created.
#### Other information 
The issue doesn't occur in the store version.

**Comment by WKobus** [comment]
Here is a callstack from logcat

`FATAL EXCEPTION: AsyncTask #1
Process: org.odk.collect.android, PID: 2652
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method org.odk.collect.entities.Entity.<init>, parameter id
	at org.odk.collect.entities.Entity.<init>(Unknown Source:7)
	at org.odk.collect.android.javarosawrapper.JavaRosaFormController.lambda$getEntities$0(Unknown Source:17)
	at org.odk.collect.android.javarosawrapper.JavaRosaFormController.$r8$lambda$sdKMRboIE2w5nAHI5mamjpJ_k0c(SourceFile:0)
	at org.odk.collect.android.javarosawrapper.JavaRosaFormController$$ExternalSyntheticLambda0.apply(SourceFile:0)
	at j$.util.stream.ReferencePipeline$3$1.accept(Unknown Source:6)
	at j$.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source:19)
	at j$.util.stream.AbstractPipeline.copyInto(Unknown Source:22)
	at j$.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source:10)
	at j$.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source:0)
	at j$.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source:0)
	at j$.util.stream.AbstractPipeline.evaluate(Unknown Source:34)
	at j$.util.stream.ReferencePipeline.forEach(Unknown Source:5)
	at org.odk.collect.android.tasks.SaveFormToDisk.saveForm(Unknown Source:77)
	at org.odk.collect.android.formentry.saving.DiskFormSaver.save(Unknown Source:25)
	at org.odk.collect.android.formentry.saving.FormSaveViewModel$SaveTask.doInBackground(SourceFile:0)
	at org.odk.collect.android.formentry.saving.FormSaveViewModel$SaveTask.doInBackground(SourceFile:0)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)`

**Comment by seadowg** [comment]
@dbemke can you check if this still happens in #6108?

**Comment by dbemke** [comment]
@WKobus Could you try and reproduce it the way Callum suggested? If not, I'll do it next week

**Comment by WKobus** [comment]
@seadowg I've reproduced this and it still occurs in #6108

**Comment by seadowg** [comment]
@seadowg @WKobus just to confirm: you're not selecting a tree (in the question "Select a tree to update") when filling the form (as there isn't any)? Also, this form won't load in Enketo right?

**Comment by WKobus** [comment]
@seadowg Yeah, I'm not selecting a tree in "Select a tree to update" question, since there isn't any, I've tried opening this form in Enketo and there is loading error.

**Comment by seadowg** [comment]
@lognaturel we should discuss how Collect should behave in this situation (an empty entity list). Granted this form should probably make the "Select a tree to update" question required (it's broken otherwise), but we should definitely avoid a crash. My thinking is that filling this form should work given the fact that we're supporting empty/missing entity lists.

**Comment by lognaturel** [comment]
Does the issue happen at form finalization time because it tries to update an entity with a blank entity id? I agree that this is mostly a form design issue. I think we should probably catch all of these kinds of finalization issues, maybe log them (something like "failed to update entity with id "" from submission "2345-23423..."), and still finalize/submit. It feels like this class of issue is best dealt with on the server where there is already specialized error handling. We could even consider showing some kind of warning message but I don't think we should block submission.

**Comment by seadowg** [comment]
Agreed! I'll update the issue description.
