### ISSUE TITLE
Crash when finalizing an entity form that doesn't use a `string` label

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#6167]
#### ODK Collect version

v2024.2.0-beta.1

#### Problem description

Forms that have an entity label expression that doesn't result in a `string` type will cause a crash when Collect finalizes them.

#### Steps to reproduce the problem

1. Create a form that with a label expression like `/data/field` where `/data/field` is an `int` type question.
2. Attempt to fill and finalize the form

#### Expected behavior

The value should be converted to a string and still used as a label.

#### Other information 

This has been seen in the wild in [this crash report](https://console.firebase.google.com/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/fed71ddc21e85b094ac0e611ad88b263?time=last-thirty-days&versions=v2024.2.0-beta.1%20(4863)&types=crash&sessionEventKey=665DC3B300FD00013C6D31980FC7620B_1954713438301672487)

The stack trace for the crash is:

```
Caused by java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
       at org.javarosa.entities.internal.EntityFormParser.parseLabel(EntityFormParser.java:16)
       at org.javarosa.entities.EntityFormFinalizationProcessor.createEntity(EntityFormFinalizationProcessor.java:28)
       at org.javarosa.entities.EntityFormFinalizationProcessor.processForm(EntityFormFinalizationProcessor.java:46)
       at org.javarosa.form.api.FormEntryController.lambda$finalizeFormEntry$0(FormEntryController.java:2)
       at j$.util.AbstractList$RandomAccessSpliterator.forEachRemaining(:19)
       at j$.util.stream.ReferencePipeline$Head.forEach(:10)
       at org.javarosa.form.api.FormEntryController.finalizeFormEntry(FormEntryController.java:20)
       at org.odk.collect.android.javarosawrapper.JavaRosaFormController.finalizeForm(JavaRosaFormController.java:2)
       at org.odk.collect.android.formentry.FormEntryUseCases.finalizeFormController(FormEntryUseCases.kt:10)
       at org.odk.collect.android.tasks.SaveFormToDisk.saveForm(SaveFormToDisk.java:60)
       at org.odk.collect.android.formentry.saving.DiskFormSaver.save(DiskFormSaver.java:25)
       at org.odk.collect.android.formentry.saving.FormSaveViewModel$SaveTask.doInBackground(FormSaveViewModel.java)
       at org.odk.collect.android.formentry.saving.FormSaveViewModel$SaveTask.doInBackground(FormSaveViewModel.java)
       at org.odk.collect.android.formentry.saving.FormSaveViewModel$SaveTask.doInBackground(FormSaveViewModel.java)
       at org.odk.collect.android.formentry.saving.FormSaveViewModel$SaveTask.doInBackground(FormSaveViewModel.java)
       at android.os.AsyncTask$3.call(AsyncTask.java:389)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:292)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:929)
```

**Comment by seadowg** [comment]
@lognaturel let me know if the "Expected behaviour" sounds correct or not!

**Comment by lognaturel** [comment]
Yes, I agree 100%!

**Comment by seadowg** [comment]
Realized this should be a v2024.2 issue as it doesn't require offline entities being in use to trigger.
