### ISSUE TITLE
App crashes with monkey runner test

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#622]
Run the below command in your terminal to initiate the basic money runner test:
`adb shell monkey -p org.odk.collect.android -v 5000`

The app crashes with the following stack trace:
>03-16 03:00:45.130 13279-13279/org.odk.collect.android W/System.err: java.lang.NullPointerException
03-16 03:00:45.135 13279-13279/org.odk.collect.android W/System.err:     at org.odk.collect.android.activities.FormEntryActivity$18.onClick(FormEntryActivity.java:2172)
03-16 03:00:45.135 13279-13279/org.odk.collect.android W/System.err:     at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
03-16 03:00:45.136 13279-13279/org.odk.collect.android W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
03-16 03:00:45.136 13279-13279/org.odk.collect.android W/System.err:     at android.os.Looper.loop(Looper.java:193)
03-16 03:00:45.136 13279-13279/org.odk.collect.android W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5292)
03-16 03:00:45.136 13279-13279/org.odk.collect.android W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
03-16 03:00:45.136 13279-13279/org.odk.collect.android W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
03-16 03:00:45.136 13279-13279/org.odk.collect.android W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
03-16 03:00:45.136 13279-13279/org.odk.collect.android W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
03-16 03:00:45.136 13279-13279/org.odk.collect.android W/System.err:     at dalvik.system.NativeStart.main(Native Method)
03-16 03:00:45.136 13279-13279/org.odk.collect.android W/dalvikvm: threadid=1: calling UncaughtExceptionHandler
03-16 03:00:45.137 13279-13279/org.odk.collect.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: org.odk.collect.android, PID: 13279
                                                                         java.lang.NullPointerException
                                                                             at org.odk.collect.android.activities.FormEntryActivity$18.onClick(FormEntryActivity.java:2172)
                                                                             at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                             at android.os.Looper.loop(Looper.java:193)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
                                                                             at dalvik.system.NativeStart.main(Native Method)
03-16 03:00:45.257 13279-15751/org.odk.collect.android D/dalvikvm: GC_FOR_ALLOC freed 2943K (44633), 29% free 8691K/12216K, paused 36ms, total 36ms

**Comment by rockydcoder** [comment]
@shobhitagarwal1612 is there a pattern to this behaviour? I tried it for a couple of times and it ran successfully.

**Comment by lognaturel** [comment]
@rockydcoder It happens when monkey runner happens to click the same button twice in quick sequence when its action hasn't completed yet. It's generally not possible to reproduce at human speeds.

@shobhitagarwal1612 Do you think we should keep this open? We identified one case in the GDrive list where it could happen at human speeds and fixed it. Are there likely to be more we should investigate?

**Comment by shobhitagarwal1612** [comment]
This can be safely closed as the issue is resolved now.
But it would be great if we mention it somewhere to be run this test occasionally. In README maybe?
