### ISSUE TITLE
XPath evaluation crash after wrong if function

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6418]
#### ODK Collect version
the master version 66e9c1f10f707b803654bc57f7930b805edf2742
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
There’s a crash( Xpath evaluation) after opening a form with a wrong if statement. I’m not sure what should be expected – should an error appear on opening the form or if there’s other way to prevent the crash.
![childUpdateCrash](https://github.com/user-attachments/assets/216ec2c1-0d50-4647-9548-c461360ff565)

It’s a form with the new spec so I attach both xml (to upload to Central) and
[child updateCOnst.xml.txt](https://github.com/user-attachments/files/17012721/child.updateCOnst.xml.txt)
 xlsx.
[child updateCOnst.xlsx.txt](https://github.com/user-attachments/files/17012699/child.updateCOnst.xlsx.txt)

#### Steps to reproduce the problem
1. Download the form.
2. Open child update with const filter form

**Comment by lognaturel** [comment]
I agree that it's surprising that it takes down the whole app. I would have expected the exception to be caught and shown in a dialog.

I'm not really understanding where the call originates from. Something in the background?
```
org.javarosa.xpath.XPathUnhandledException: XPath evaluation: cannot handle function 'if'. Requires 3 arguments but 1 provided.
	at org.javarosa.xpath.expr.XPathFuncExpr.assertArgsCount(XPathFuncExpr.java:540)
	at org.javarosa.xpath.expr.XPathFuncExpr.eval(XPathFuncExpr.java:165)
	at org.javarosa.core.model.condition.RawFilterStrategy.filter(RawFilterStrategy.java:32)
	at org.javarosa.core.model.condition.EvaluationContext.filterWithPredicate(EvaluationContext.java:382)
	at org.javarosa.core.model.condition.EvaluationContext.lambda$filterWithPredicate$0$org-javarosa-core-model-condition-EvaluationContext(EvaluationContext.java:383)
	at org.javarosa.core.model.condition.EvaluationContext$$ExternalSyntheticLambda0.get(D8$$SyntheticClass)
	at org.javarosa.core.model.ComparisonExpressionCacheFilterStrategy.filter(ComparisonExpressionCacheFilterStrategy.java:55)
	at org.javarosa.core.model.condition.EvaluationContext.filterWithPredicate(EvaluationContext.java:382)
	at org.javarosa.core.model.condition.EvaluationContext.lambda$filterWithPredicate$0$org-javarosa-core-model-condition-EvaluationContext(EvaluationContext.java:383)
	at org.javarosa.core.model.condition.EvaluationContext$$ExternalSyntheticLambda0.get(D8$$SyntheticClass)
	at org.javarosa.core.model.EqualityExpressionIndexFilterStrategy.filter(EqualityExpressionIndexFilterStrategy.java:33)
	at org.javarosa.core.model.condition.EvaluationContext.filterWithPredicate(EvaluationContext.java:382)
	at org.javarosa.core.model.condition.EvaluationContext.lambda$filterWithPredicate$0$org-javarosa-core-model-condition-EvaluationContext(EvaluationContext.java:383)
	at org.javarosa.core.model.condition.EvaluationContext$$ExternalSyntheticLambda0.get(D8$$SyntheticClass)
	at org.odk.collect.entities.javarosa.filter.LocalEntitiesFilterStrategy.filter(LocalEntitiesFilterStrategy.kt:66)
	at org.javarosa.core.model.condition.EvaluationContext.filterWithPredicate(EvaluationContext.java:382)
	at org.javarosa.core.model.condition.EvaluationContext.filterWithPredicate(EvaluationContext.java:377)
	at org.javarosa.core.model.condition.EvaluationContext.expandReferenceAccumulator(EvaluationContext.java:343)
	at org.javarosa.core.model.condition.EvaluationContext.expandReference(EvaluationContext.java:250)
	at org.javarosa.core.model.condition.EvaluationContext.expandReference(EvaluationContext.java:219)
	at org.javarosa.xpath.expr.XPathPathExprEval.eval(XPathPathExprEval.java:34)
	at org.javarosa.xpath.expr.XPathPathExpr.eval(XPathPathExpr.java:213)
	at org.javarosa.xpath.XPathConditional.evalNodeset(XPathConditional.java:94)
	at org.javarosa.core.model.ItemsetBinding.getChoices(ItemsetBinding.java:125)
	at org.javarosa.form.api.FormEntryPrompt.getSelectChoices(FormEntryPrompt.java:222)
	at org.javarosa.form.api.FormEntryPrompt.getAnswerValue(FormEntryPrompt.java:98)
	at org.odk.collect.android.formentry.audit.AuditUtils.logCurrentScreen(AuditUtils.kt:21)
	at org.odk.collect.android.formentry.FormEntryViewModel.updateIndex(FormEntryViewModel.java:351)
	at org.odk.collect.android.formentry.FormEntryViewModel.lambda$refresh$7(FormEntryViewModel.java:318)
	at org.odk.collect.android.formentry.FormEntryViewModel.$r8$lambda$IkEKpMouzOlAseG821xo_liby6A(FormEntryViewModel.java)
	at org.odk.collect.android.formentry.FormEntryViewModel$$ExternalSyntheticLambda10.get(D8$$SyntheticClass)
	at org.odk.collect.async.CoroutineScheduler$immediate$1$result$1.invokeSuspend(CoroutineScheduler.kt:18)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
```

**Comment by lognaturel** [comment]
@grzegorz mentions there was a recent change to how exceptions are handled in this area. We should at least explore whether this is a change in behavior.

**Comment by lognaturel** [comment]
I ran into this again recently with another form design issue. I do think the previous experience of seeing a dialog and being sent back to `Start new form` after dismissing the dialog felt better. When this happened, I was very disoriented and I couldn't immediately remember which form I had been trying to open. When it was a dialog, the form title was visible which gave useful context. I believe this experience also means that there's a crash logged to Crashlytics but there's nothing we can do about it.

I briefly asked @seadowg about this and he thinks this change of behavior is likely due to a combination of removing a blanket try/catch and moving form loading off the UI thread.

Ideally we could wrap form loading with a try/catch for just `XPathException` and show a dialog with the error text.
