### ISSUE TITLE
Double clicking on folder in Google Drive listing results in crash

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#651]
#### Software and hardware versions 
Collect v1.4.16

#### Problem description
Double clicking on a folder in "Get Blank Form" when protocol is "Google Sheets, Google Drive" results in crash.

#### Steps to reproduce the problem
1. Set protocol to "Google Sheets, Google Drive"
1. Select a Google account that has at least one folder in its GDrive
1. Tap on "Get Blank Form"
1. Tap "My Drive"
1. Double tap on a folder in the drive

#### Expected behavior
The app should not crash.

#### Other information 
I think this is happening because listing a directory is a time-consuming action and shouldn't be triggered again before completion. This should be fixable by disabling tapping on items in the list until the operation requested completes.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.odk.collect.android.logic.DriveListItem org.odk.collect.android.adapters.FileArrayAdapter.getItem(int)' on a null object reference
E/AndroidRuntime(17777):     at org.odk.collect.android.activities.GoogleDriveActivity.onListItemClick(GoogleDriveActivity.java:371)
E/AndroidRuntime(17777):     at android.app.ListActivity$2.onItemClick(ListActivity.java:319)
E/AndroidRuntime(17777):     at android.widget.AdapterView.performItemClick(AdapterView.java:305)
E/AndroidRuntime(17777):     at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
E/AndroidRuntime(17777):     at android.widget.AbsListView$PerformClick.run(AbsListView.java:3053)
E/AndroidRuntime(17777):     at android.widget.AbsListView$3.run(AbsListView.java:3860)
E/AndroidRuntime(17777):     at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(17777):     at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(17777):     at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(17777):     at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(17777):     at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17777):     at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(17777):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(17777):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/ActivityManager( 4192):   Force finishing activity 1 org.odk.collect.android/.activities.GoogleDriveActivity
```

**Comment by pratikmjoshi** [comment]
@lognaturel Can I work on this?

**Comment by lognaturel** [comment]
@pratikmjoshi Sounds good!
