### ISSUE TITLE
Crash when user selects video that was just recorded

### ISSUE THREAD

**Issue by rajatthakur** [getodk/collect#691]
#### Software and hardware versions 
Collect v1.4.16, Android v6.0, Nexus 5

#### Problem description

Crash after choosing a recorded video.

#### Steps to reproduce the problem

1)Record a video.
2)Click on choose button.
3)Select the video that you just recorded.

#### Expected behavior

The recorded video should be played like any other video.

#### Other information 
I discovered this issue while trying to fix #660 and I feel the two are somewhat related.

```
E/ODKView: Attempt to invoke virtual method 'int java.lang.String.lastIndexOf(java.lang.String)' on a null object reference
           java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.lastIndexOf(java.lang.String)' on a null object reference
               at org.odk.collect.android.widgets.VideoWidget.setBinaryData(VideoWidget.java:282)
               at org.odk.collect.android.views.ODKView.setBinaryData(ODKView.java:316)
               at org.odk.collect.android.activities.FormEntryActivity.saveAudioVideoAnswer(FormEntryActivity.java:798)
               at org.odk.collect.android.activities.FormEntryActivity.onActivityResult(FormEntryActivity.java:717)
               at android.app.Activity.dispatchActivityResult(Activity.java:6428)
               at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
               at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
               at android.app.ActivityThread.-wrap16(ActivityThread.java)
               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
               at android.os.Handler.dispatchMessage(Handler.java:102)
               at android.os.Looper.loop(Looper.java:148)
               at android.app.ActivityThread.main(ActivityThread.java:5417)
               at java.lang.reflect.Method.invoke(Native Method)
               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by shobhitagarwal1612** [comment]
@lognaturel Fixed in #692
