### ISSUE TITLE
Audio recording widget doesn't work with Sony Audio Recorder app

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#705]
#### Software and hardware versions 
v1.4.16-113-g3f707159, Android v6.0.1, Nexus 5, Sony Audio Recorder 2.00.30

#### Problem description
Crash when trying to use Sony Audio Recorder app from audio widget.

#### Steps to reproduce the problem
1. Open a form with an audio widget such as Widgets from the test server
1. Launch a recording application such as Sony Audio Recorder from the "record audio" button
1. Record audio
1. Go back to Collect

#### Expected behavior
If the audio type can't be handled or some other such problem occurs, Collect should show an appropriate error message rather than crashing.

#### Other information 
```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=3, result=-1, data=Intent { dat=content://com.sonymobile.androidapp.audiorecorder.content/audio/1 typ=audio/raw }} to activity {org.odk.collect.android/org.odk.collect.android.activities.FormEntryActivity}: java.lang.UnsupportedOperationException: You cannot use this method
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
	at android.app.ActivityThread.-wrap16(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.UnsupportedOperationException: You cannot use this method
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.delete(ContentProviderNative.java:544)
	at android.content.ContentResolver.delete(ContentResolver.java:1327)
	at org.odk.collect.android.activities.FormEntryActivity.onActivityResult(FormEntryActivity.java:713)
	at android.app.Activity.dispatchActivityResult(Activity.java:6456)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
	... 9 more
   Force finishing activity org.odk.collect.android/.activities.FormEntryActivity
```

**Comment by getsanjeev** [comment]
@lognaturel I would like to look into it.

**Comment by lognaturel** [comment]
@getsanjeev Just in case you didn't see my thumbs up -- please do!

**Comment by getsanjeev** [comment]
@lognaturel Sorry I didn't notice it. I will start by now.

**Comment by getsanjeev** [comment]
@lognaturel Not only your crash, When I try to record an audio on my android (4.4.2) with sony audio recorder app (2.00.30) the audio is not saved, though app does not crash. I will fix it soon.

**Comment by kkrawczyk123** [comment]
Crash reproduced on Androids: 6.0, 7.0 and 8.1
App did not crash but audio file not saved on Androids: 4.1, 4.2 and 4.4

**Comment by grzesiek2010** [comment]
Fixed in: https://github.com/opendatakit/collect/pull/2613
