### ISSUE TITLE
Cursor not closed 

### ISSUE THREAD

**Issue by getsanjeev** [getodk/collect#757]
#### Software and hardware versions 
Collect v1.4.16, Android v4.4.2, device used...

#### Problem description
PossibleCursorLeak:content://org.odk.collect.android.provider.odk.instances/instances,QueryCounter:5
                                                                             android.database.sqlite.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
                                                                                 at android.content.ContentResolver.query(ContentResolver.java:491)
                                                                                 at android.content.ContentResolver.query(ContentResolver.java:405)
                                                                                 at org.odk.collect.android.tasks.InstanceSyncTask.doInBackground(InstanceSyncTask.java:99)
                                                                                 at org.odk.collect.android.tasks.InstanceSyncTask.doInBackground(InstanceSyncTask.java:48)
                                                                                 at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                 at java.lang.Thread.run(Thread.java:841)

#### Steps to reproduce the problem
Click on edit saved forms in main menu activity.

#### Expected behavior
No error should be thrown. Database cursor should be closed when data access is complete.

**Comment by lognaturel** [comment]
Yes, and I believe it's not the only one! I think if you just navigate around the app with logcat running for a bit you'll see several more examples of the same.

**Comment by rockydcoder** [comment]
Could not reproduce this in Android 6.0. Is it version specific?

**Comment by getsanjeev** [comment]
@rockydcoder I have not given much thoughts to it till now. I will come back to you in a while. What I think is it shouldnt.

**Comment by udhay24** [comment]
@opendatakit-bot claim

**Comment by shobhitagarwal1612** [comment]
Unable to reproduce the issue

**Comment by grzesiek2010** [comment]
We have solved a few such issues (not closed cursor) so probably it's fixed, otherwise, it would be visible in our reports.
