### ISSUE TITLE
Crash when pausing Collect on GoogleDriveActivity

### ISSUE THREAD

**Issue by nribeka** [getodk/collect#770]
#### Software and hardware versions 
Latest build from master, Android 6.0, Moto X Pure

#### Problem description
The app crash when pausing the activity after listing out the drive content.

#### Steps to reproduce the problem
* Change platform to Google Drive, Google Sheets in general settings
* Go to get blank form section
* Press the button to pause activity (option button)

#### Expected behavior
* App will pause but not crashing

#### Other information 
    03-24 14:51:58.397 2070-2070/org.odk.collect.android E/AndroidRuntime: FATAL EXCEPTION: main
       Process: org.odk.collect.android, PID: 2070
       java.lang.NullPointerException: Attempt to invoke virtual method 'long com.google.api.client.util.DateTime.getValue()' on a null object reference
       at org.odk.collect.android.logic.DriveListItem.writeToParcel(DriveListItem.java:108)
       at android.os.Parcel.writeParcelable(Parcel.java:1416)
       at android.os.Parcel.writeValue(Parcel.java:1322)
       at android.os.Parcel.writeList(Parcel.java:738)
       at android.os.Parcel.writeValue(Parcel.java:1344)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:665)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330)
       at android.os.Bundle.writeToParcel(Bundle.java:1079)
       at android.os.Parcel.writeBundle(Parcel.java:690)
       at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3196)
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3438)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by lakshyagupta21** [comment]
Can I work on this issue ?

**Comment by lognaturel** [comment]
Yes, please, @lakshyagupta21!

**Comment by grzesiek2010** [comment]
@lakshyagupta21 please look at #771 as well.
