### ISSUE TITLE
Crash when try to open a folder form GDrive after removing access

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#771]
#### Software and hardware versions 
Current master branch

#### Problem description
Crash when try to open a folder form GDrive after removing access.

#### Steps to reproduce the problem
1. In general settings, change the platform to "Google Drive, Google Sheets"
2. Select your primary gmail account for the google account.
3. Go to get blank form section
4. Wait for files
4. Remove access for ODK Collect [Google Account Permissions](https://myaccount.google.com/permissions)
5. Click on one of your folders

#### Other information 

> FATAL EXCEPTION: main
                                                                         Process: org.odk.collect.android, PID: 13184
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'long com.google.api.client.util.DateTime.getValue()' on a null object reference
                                                                             at org.odk.collect.android.logic.DriveListItem.writeToParcel(DriveListItem.java:108)
                                                                             at android.os.Parcel.writeParcelable(Parcel.java:1357)
                                                                             at android.os.Parcel.writeValue(Parcel.java:1262)
                                                                             at android.os.Parcel.writeList(Parcel.java:711)
                                                                             at android.os.Parcel.writeValue(Parcel.java:1284)
                                                                             at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
                                                                             at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
                                                                             at android.os.Bundle.writeToParcel(Bundle.java:1096)
                                                                             at android.os.Parcel.writeBundle(Parcel.java:663)
                                                                             at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3115)
                                                                             at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3781)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:145)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5951)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by grzesiek2010** [comment]
I realized that the same stacktraces are in https://github.com/opendatakit/collect/issues/770
My steps are different but probably it's one issue.
