### ISSUE TITLE
FormEntryActivityRuleTest sometimes failing on CircleCI

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#796]
Builds such as [this one](https://circleci.com/gh/opendatakit/collect/300#artifacts/containers/0) occasionally crash on a `NullPointerException` in FormEntryActivityRuleTest:
```
java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.content.SharedPreferences.getBoolean(java.lang.String, boolean)' on a null object reference
at org.odk.collect.android.activities.FormEntryActivity.onPrepareOptionsMenu(FormEntryActivity.java:863)
at android.app.Activity.onPreparePanel(Activity.java:2841)
at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:577)
at com.android.internal.policy.impl.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:921)
at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:259)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

This is not systematic and I have not been able to reproduce it locally. Rebuilding fixes it.

**Comment by shobhitagarwal1612** [comment]
MainMenuActivityTest is also seen to be failing such as [here](https://circleci.com/gh/opendatakit/collect/313?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by lognaturel** [comment]
This happens at a high enough frequency that it's getting really hard to know if there is an actual problem with a build or not. We should try getting [ssh access to the build](https://circleci.com/docs/1.0/ssh-build/) so we can get access to more detailed logs. Unfortunately I think it will require running the build over and over again until the problem occurs.

@sanovikov71 @yadav-rahul do you happen to have any ideas of what might be causing these tests to occasionally fail with `NullPointerExceptions`?

**Comment by lognaturel** [comment]
Could this be related to #622? Perhaps things are just happening too quickly somehow?

**Comment by sanovikov71** [comment]
It is not clear what is the root cause now.
But after reading [this article](https://jabknowsnothing.wordpress.com/2015/11/05/activitytestrule-espressos-test-lifecycle/) I think that the tests were factored not the best way.
Using of custom ActivityTestRule's and overriding of the method #beforeActivityLaunched should be considered instead of using @Before annotation in the test. The third parameter of the rule constructor, that defines if the activity is launched automatically or not, can also be changed - to the true. Looks like there are no reasons to start it manually. I am going to investigate ActivityTestRule code a bit more thoroughly and implement some adjustments.

**Comment by lognaturel** [comment]
Very interesting, @sanovikov71. Thank you for looking into it!

**Comment by lognaturel** [comment]
Unfortunately, it looks like these tests are still occasionally failing. The failure is different, though:
```
junit.framework.AssertionFailedError: File /storage/sdcard/odk/.cachedoes not exist
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.assertTrue(Assert.java:20)
at org.odk.collect.android.externalintents.ExportedActivitiesUtils.testDirectories(ExportedActivitiesUtils.java:35)
at org.odk.collect.android.externalintents.FormEntryActivityTest.formEntryActivityMakesDirsTest(FormEntryActivityTest.java:24)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:270)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)
```
from [here](https://circleci.com/gh/opendatakit/collect/359#artifacts/containers/0)

**Comment by sanovikov71** [comment]
Hi, it looks that adding of tests that work directly with SD cards was not the best idea, because it is unclear how  these tests work on CI server. I think we should consider removing these tests as they give more problems, than advantages. On the other hand, it was difficult to test this logic differently, because of a static method Collect.createODKDirs() that can not be mocked without refactoring.

**Comment by lognaturel** [comment]
Thanks @sanovikov71, I have suppressed it for now so we can keep thinking about it and seeing if we can come up with a solution.

**Comment by lognaturel** [comment]
The test structure has changed a ton and flaky test issues are being actively monitored so we can close this.
