### ISSUE TITLE
App crashes when listing blank forms from Google Drive without API auth

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#869]
#### Software and hardware versions 
Current master branch

#### Problem description
App crashes when I try to open my google drive

#### Steps to reproduce the problem
1. In "General Settings" set platform to "Google Drive, Google Sheets"
2. Click on "Get Blank Form" from Main menu

#### Other information 

> Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
                                                       at android.os.Handler.<init>(Handler.java:200)
                                                       at android.os.Handler.<init>(Handler.java:114)
                                                       at android.app.Dialog.<init>(Dialog.java:113)
                                                       at android.app.AlertDialog.<init>(AlertDialog.java:125)
                                                       at android.app.AlertDialog$Builder.create(AlertDialog.java:968)
                                                       at org.odk.collect.android.activities.GoogleDriveActivity.createAlertDialog(GoogleDriveActivity.java:529)
                                                       at org.odk.collect.android.activities.GoogleDriveActivity.access$500(GoogleDriveActivity.java:96)
                                                       at org.odk.collect.android.activities.GoogleDriveActivity$RetrieveDriveFileContentsAsyncTask.doInBackground(GoogleDriveActivity.java:797)
                                                       at org.odk.collect.android.activities.GoogleDriveActivity$RetrieveDriveFileContentsAsyncTask.doInBackground(GoogleDriveActivity.java:766)

**Comment by grzesiek2010** [comment]
It has been added [#790](https://github.com/grzesiek2010/collect/commit/02f9a43e94c2e09227af05651bc67381e3dd5b69#diff-4843e9d988e60283c4c8967d83b05c0bR796)
@saurabhjn76 have you tested this?

**Comment by lognaturel** [comment]
Oh wow, you are absolutely right, @grzesiek2010! Apologies, I thought I had tried it out but evidently not. @saurabhjn76 it would be great if you could look into this. To try it out, you can disable the Drive API [here](https://console.developers.google.com/apis/api/drive/). It will take a couple moments before the auth updates.

**Comment by saurabhjn76** [comment]
Apologies for responding late, I am busy with my semester exams and would take me a couple of weeks before I could look into this.

**Comment by grzesiek2010** [comment]
@saurabhjn76 it's added to April Release so if you are too busy me or somebody else will fix it.

**Comment by saurabhjn76** [comment]
@grzesiek2010 yeah, it would be better if somebody else take it.
